// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ap_hccd_report.proto

package proto

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApHccdClientReportConnection struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Client MAC address
	// @since 3.6
	ClientMac *string `protobuf:"bytes,1,opt,name=client_mac,json=clientMac" json:"client_mac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Timestamp for starting to record this client session
	// @since 3.6
	Timestamp *uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Client session connection status (success or failure)
	// @since 3.6
	ConnectionStatus *int32 `protobuf:"varint,3,opt,name=connection_status,json=connectionStatus" json:"connection_status,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Message ID to indicate what failures step in whole connection
	// @since 3.6
	FailedMsgId *int32 `protobuf:"varint,4,opt,name=failed_msg_id,json=failedMsgId" json:"failed_msg_id,omitempty"`
	//*
	// @property Serialization
	// @aggregation NULL
	// @description A sequence of message ID are recorded for this client session
	// @since 3.6
	MessageIds []int32 `protobuf:"varint,5,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description WLAN Id that is connected by client
	// @since 3.6
	WlanId *uint32 `protobuf:"varint,6,opt,name=wlan_id,json=wlanId" json:"wlan_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Radio Id that is connected by client
	// @since 3.6
	RadioId *uint32 `protobuf:"varint,7,opt,name=radio_id,json=radioId" json:"radio_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description SSID that is connected by client
	// @since 3.6
	Ssid *string `protobuf:"bytes,8,opt,name=ssid" json:"ssid,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Wlan type (open, WPA, etc) - not used now
	// @since 3.6
	WlanType *string `protobuf:"bytes,9,opt,name=wlanType" json:"wlanType,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Client lastest frame SNR value - not used now
	// @since 3.6
	Snr *float32 `protobuf:"fixed32,10,opt,name=snr" json:"snr,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Classify this failure client session belong to which failure case(auth, assoc, eap, radio, dhcp)
	// @since 3.6
	FailureType *int32 `protobuf:"varint,11,opt,name=failure_type,json=failureType" json:"failure_type,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Vlan ID is used by client
	// @since 3.6
	Vlan *int32 `protobuf:"varint,12,opt,name=vlan" json:"vlan,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Reason code for deauth/disassoc frame
	// @since 3.6
	ReasonCode *int32 `protobuf:"varint,13,opt,name=reason_code,json=reasonCode" json:"reason_code,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Client session disconnection description
	// @since 3.6
	Info *string `protobuf:"bytes,14,opt,name=info" json:"info,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description the time is spent for this failure connection
	// @since 5.1.1
	TTF *uint64 `protobuf:"varint,15,opt,name=TTF" json:"TTF,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description a flag to indicate this connection session is roaming or new join
	// @since 5.1.1
	IsRoaming            *int32   `protobuf:"varint,16,opt,name=isRoaming" json:"isRoaming,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApHccdClientReportConnection) Reset()         { *m = ApHccdClientReportConnection{} }
func (m *ApHccdClientReportConnection) String() string { return proto.CompactTextString(m) }
func (*ApHccdClientReportConnection) ProtoMessage()    {}
func (*ApHccdClientReportConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f99bccf30629fc, []int{0}
}
func (m *ApHccdClientReportConnection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApHccdClientReportConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApHccdClientReportConnection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApHccdClientReportConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApHccdClientReportConnection.Merge(m, src)
}
func (m *ApHccdClientReportConnection) XXX_Size() int {
	return m.Size()
}
func (m *ApHccdClientReportConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_ApHccdClientReportConnection.DiscardUnknown(m)
}

var xxx_messageInfo_ApHccdClientReportConnection proto.InternalMessageInfo

func (m *ApHccdClientReportConnection) GetClientMac() string {
	if m != nil && m.ClientMac != nil {
		return *m.ClientMac
	}
	return ""
}

func (m *ApHccdClientReportConnection) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetConnectionStatus() int32 {
	if m != nil && m.ConnectionStatus != nil {
		return *m.ConnectionStatus
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetFailedMsgId() int32 {
	if m != nil && m.FailedMsgId != nil {
		return *m.FailedMsgId
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetMessageIds() []int32 {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *ApHccdClientReportConnection) GetWlanId() uint32 {
	if m != nil && m.WlanId != nil {
		return *m.WlanId
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetRadioId() uint32 {
	if m != nil && m.RadioId != nil {
		return *m.RadioId
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetSsid() string {
	if m != nil && m.Ssid != nil {
		return *m.Ssid
	}
	return ""
}

func (m *ApHccdClientReportConnection) GetWlanType() string {
	if m != nil && m.WlanType != nil {
		return *m.WlanType
	}
	return ""
}

func (m *ApHccdClientReportConnection) GetSnr() float32 {
	if m != nil && m.Snr != nil {
		return *m.Snr
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetFailureType() int32 {
	if m != nil && m.FailureType != nil {
		return *m.FailureType
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetVlan() int32 {
	if m != nil && m.Vlan != nil {
		return *m.Vlan
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetReasonCode() int32 {
	if m != nil && m.ReasonCode != nil {
		return *m.ReasonCode
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func (m *ApHccdClientReportConnection) GetTTF() uint64 {
	if m != nil && m.TTF != nil {
		return *m.TTF
	}
	return 0
}

func (m *ApHccdClientReportConnection) GetIsRoaming() int32 {
	if m != nil && m.IsRoaming != nil {
		return *m.IsRoaming
	}
	return 0
}

type ApHccdReportMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP HCCD version
	// @since 3.6
	Version *uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP MAC address
	// @since 3.6
	ApMac *string `protobuf:"bytes,2,opt,name=ap_mac,json=apMac" json:"ap_mac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Timestamp to generate this stats report
	// @since 3.6
	Timestamp *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Sequence number to identify this stats report
	// @since 3.6
	SeqNumber *uint64 `protobuf:"varint,4,opt,name=seqNumber" json:"seqNumber,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone UUID
	// @since 3.6
	ZoneId *string `protobuf:"bytes,5,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description  AP gorup UUID
	// @since 3.6
	ApgroupId *string `protobuf:"bytes,6,opt,name=apgroup_id,json=apgroupId" json:"apgroup_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Cluster UUID
	// @since 3.6
	ClusterId *string `protobuf:"bytes,7,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain UUID
	// @since 3.6
	DomainId *string `protobuf:"bytes,8,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP tenant UUID
	// @since 3.6
	AptenantId *string `protobuf:"bytes,9,opt,name=aptenant_id,json=aptenantId" json:"aptenant_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description MAP UUID
	// @since 3.6
	MapId *string `protobuf:"bytes,10,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP device name
	// @since 3.6
	DeviceName *string `protobuf:"bytes,11,opt,name=deviceName" json:"deviceName,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP tenant name
	// @since 3.6
	AptenantName *string `protobuf:"bytes,12,opt,name=aptenant_name,json=aptenantName" json:"aptenant_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone name
	// @since 3.6
	ZoneName *string `protobuf:"bytes,13,opt,name=zone_name,json=zoneName" json:"zone_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP group name
	// @since 3.6
	ApgroupName *string `protobuf:"bytes,14,opt,name=apgroup_name,json=apgroupName" json:"apgroup_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain name
	// @since 3.6
	DomainName *string `protobuf:"bytes,15,opt,name=domain_name,json=domainName" json:"domain_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Timestamp for generating this report
	// @since 3.6
	SampleTime *uint64 `protobuf:"varint,16,opt,name=sampleTime" json:"sampleTime,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Interval time for aggregrating stats data
	// @since 3.6
	AggregationInterval *uint32 `protobuf:"varint,17,opt,name=aggregationInterval" json:"aggregationInterval,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP IPv4 address
	// @since 3.6
	ApIpAddress *string `protobuf:"bytes,18,opt,name=apIpAddress" json:"apIpAddress,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP IPv6 address
	// @since 3.6
	ApIpv6Address *string `protobuf:"bytes,19,opt,name=apIpv6Address" json:"apIpv6Address,omitempty"`
	//*
	// @property Serialization
	// @aggregation NULL
	// @description serialization data for failure client session record
	// @since 3.6
	ApHccdClients        []*ApHccdClientReportConnection `protobuf:"bytes,20,rep,name=apHccdClients" json:"apHccdClients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ApHccdReportMessage) Reset()         { *m = ApHccdReportMessage{} }
func (m *ApHccdReportMessage) String() string { return proto.CompactTextString(m) }
func (*ApHccdReportMessage) ProtoMessage()    {}
func (*ApHccdReportMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_85f99bccf30629fc, []int{1}
}
func (m *ApHccdReportMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApHccdReportMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApHccdReportMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApHccdReportMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApHccdReportMessage.Merge(m, src)
}
func (m *ApHccdReportMessage) XXX_Size() int {
	return m.Size()
}
func (m *ApHccdReportMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApHccdReportMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApHccdReportMessage proto.InternalMessageInfo

func (m *ApHccdReportMessage) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ApHccdReportMessage) GetApMac() string {
	if m != nil && m.ApMac != nil {
		return *m.ApMac
	}
	return ""
}

func (m *ApHccdReportMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ApHccdReportMessage) GetSeqNumber() uint64 {
	if m != nil && m.SeqNumber != nil {
		return *m.SeqNumber
	}
	return 0
}

func (m *ApHccdReportMessage) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *ApHccdReportMessage) GetApgroupId() string {
	if m != nil && m.ApgroupId != nil {
		return *m.ApgroupId
	}
	return ""
}

func (m *ApHccdReportMessage) GetClusterId() string {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return ""
}

func (m *ApHccdReportMessage) GetDomainId() string {
	if m != nil && m.DomainId != nil {
		return *m.DomainId
	}
	return ""
}

func (m *ApHccdReportMessage) GetAptenantId() string {
	if m != nil && m.AptenantId != nil {
		return *m.AptenantId
	}
	return ""
}

func (m *ApHccdReportMessage) GetMapId() string {
	if m != nil && m.MapId != nil {
		return *m.MapId
	}
	return ""
}

func (m *ApHccdReportMessage) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *ApHccdReportMessage) GetAptenantName() string {
	if m != nil && m.AptenantName != nil {
		return *m.AptenantName
	}
	return ""
}

func (m *ApHccdReportMessage) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *ApHccdReportMessage) GetApgroupName() string {
	if m != nil && m.ApgroupName != nil {
		return *m.ApgroupName
	}
	return ""
}

func (m *ApHccdReportMessage) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *ApHccdReportMessage) GetSampleTime() uint64 {
	if m != nil && m.SampleTime != nil {
		return *m.SampleTime
	}
	return 0
}

func (m *ApHccdReportMessage) GetAggregationInterval() uint32 {
	if m != nil && m.AggregationInterval != nil {
		return *m.AggregationInterval
	}
	return 0
}

func (m *ApHccdReportMessage) GetApIpAddress() string {
	if m != nil && m.ApIpAddress != nil {
		return *m.ApIpAddress
	}
	return ""
}

func (m *ApHccdReportMessage) GetApIpv6Address() string {
	if m != nil && m.ApIpv6Address != nil {
		return *m.ApIpv6Address
	}
	return ""
}

func (m *ApHccdReportMessage) GetApHccdClients() []*ApHccdClientReportConnection {
	if m != nil {
		return m.ApHccdClients
	}
	return nil
}

func init() {
	proto.RegisterType((*ApHccdClientReportConnection)(nil), "proto.ApHccdClientReportConnection")
	proto.RegisterType((*ApHccdReportMessage)(nil), "proto.ApHccdReportMessage")
}

func init() { proto.RegisterFile("ap_hccd_report.proto", fileDescriptor_85f99bccf30629fc) }

var fileDescriptor_85f99bccf30629fc = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xc1, 0x6e, 0xe3, 0x36,
	0x10, 0x86, 0x2b, 0xdb, 0xb2, 0xad, 0xb1, 0xdd, 0x24, 0x4c, 0x8a, 0xb2, 0x49, 0xea, 0x28, 0x49,
	0x0f, 0x06, 0x0a, 0x18, 0x6d, 0x0f, 0xbd, 0x16, 0x49, 0x80, 0xa2, 0x3a, 0x24, 0x28, 0x54, 0xdf,
	0x05, 0x46, 0x64, 0x54, 0xa2, 0x12, 0xa9, 0x92, 0x92, 0x83, 0xf6, 0x31, 0x7a, 0xea, 0xe3, 0xf4,
	0xd8, 0xe3, 0xbe, 0xc1, 0x2e, 0xb2, 0x2f, 0xb2, 0xe0, 0xd0, 0xb2, 0x93, 0xdd, 0xc5, 0x9e, 0x4c,
	0x7e, 0xff, 0x3f, 0xe4, 0x8c, 0x7e, 0x59, 0x70, 0xc4, 0xea, 0xec, 0xf7, 0x3c, 0xe7, 0x99, 0x11,
	0xb5, 0x36, 0xcd, 0xb2, 0x36, 0xba, 0xd1, 0x24, 0xc4, 0x9f, 0xe3, 0xa9, 0x62, 0x4a, 0xd7, 0xf7,
	0x1e, 0x5e, 0xbc, 0xee, 0xc3, 0xe9, 0x55, 0xfd, 0x4b, 0x9e, 0xf3, 0x9b, 0x52, 0x0a, 0xd5, 0xa4,
	0x58, 0x71, 0xa3, 0x95, 0x12, 0x79, 0x23, 0xb5, 0x22, 0x5f, 0x03, 0xe4, 0xa8, 0x64, 0x15, 0xcb,
	0x69, 0x10, 0x07, 0x8b, 0x28, 0x8d, 0x3c, 0xb9, 0x65, 0x39, 0x39, 0x85, 0xa8, 0x91, 0x95, 0xb0,
	0x0d, 0xab, 0x6a, 0xda, 0x8b, 0x83, 0xc5, 0x20, 0xdd, 0x01, 0xf2, 0x2d, 0x1c, 0xe4, 0xdb, 0xa3,
	0x32, 0xdb, 0xb0, 0xa6, 0xb5, 0xb4, 0x1f, 0x07, 0x8b, 0x30, 0xdd, 0xdf, 0x09, 0xbf, 0x21, 0x27,
	0x17, 0x30, 0x7b, 0x60, 0xb2, 0x14, 0x3c, 0xab, 0x6c, 0x91, 0x49, 0x4e, 0x07, 0x68, 0x9c, 0x78,
	0x78, 0x6b, 0x8b, 0x84, 0x93, 0x33, 0x98, 0x54, 0xc2, 0x5a, 0x56, 0x88, 0x4c, 0x72, 0x4b, 0xc3,
	0xb8, 0xbf, 0x08, 0x53, 0xd8, 0xa0, 0x84, 0x5b, 0xf2, 0x25, 0x8c, 0x1e, 0x4b, 0xa6, 0x5c, 0xf9,
	0x30, 0x0e, 0x16, 0xb3, 0x74, 0xe8, 0xb6, 0x09, 0x27, 0x5f, 0xc1, 0xd8, 0x30, 0x2e, 0xb5, 0x53,
	0x46, 0xa8, 0x8c, 0x70, 0x9f, 0x70, 0x42, 0x60, 0x60, 0xad, 0xe4, 0x74, 0x8c, 0xc3, 0xe1, 0x9a,
	0x1c, 0xc3, 0xd8, 0x15, 0xae, 0xfe, 0xaa, 0x05, 0x8d, 0x90, 0x6f, 0xf7, 0x64, 0x1f, 0xfa, 0x56,
	0x19, 0x0a, 0x71, 0xb0, 0xe8, 0xa5, 0x6e, 0x49, 0xce, 0x61, 0xea, 0xba, 0x6c, 0x8d, 0xc8, 0x1a,
	0x57, 0x31, 0xd9, 0x75, 0xde, 0x1a, 0x81, 0x45, 0x04, 0x06, 0xeb, 0x92, 0x29, 0x3a, 0x45, 0x09,
	0xd7, 0x6e, 0x1a, 0x23, 0x98, 0xd5, 0x2a, 0xcb, 0x35, 0x17, 0x74, 0x86, 0x12, 0x78, 0x74, 0xa3,
	0x39, 0x16, 0x49, 0xf5, 0xa0, 0xe9, 0xe7, 0xbe, 0x33, 0xb7, 0x76, 0xb7, 0xaf, 0x56, 0x3f, 0xd3,
	0x3d, 0x7c, 0xd6, 0x6e, 0xe9, 0x32, 0x90, 0x36, 0xd5, 0xac, 0x92, 0xaa, 0xa0, 0xfb, 0x78, 0xc8,
	0x0e, 0x5c, 0xfc, 0x17, 0xc2, 0xa1, 0x4f, 0xd8, 0x67, 0x7b, 0xeb, 0x1f, 0x16, 0xa1, 0x30, 0x5a,
	0x0b, 0x63, 0xa5, 0x56, 0x98, 0xea, 0x2c, 0xed, 0xb6, 0xe4, 0x0b, 0x18, 0xb2, 0x1a, 0xe3, 0xee,
	0xe1, 0xbd, 0x21, 0xab, 0x3f, 0x88, 0xba, 0xff, 0x7e, 0xd4, 0xa7, 0x10, 0x59, 0xf1, 0xe7, 0x5d,
	0x5b, 0xdd, 0x0b, 0x83, 0xc9, 0x0d, 0xd2, 0x1d, 0x70, 0xb1, 0xfc, 0xad, 0x95, 0x0b, 0x8d, 0x86,
	0x78, 0xe6, 0xd0, 0x6d, 0x13, 0xee, 0x5e, 0x2f, 0x56, 0x17, 0x46, 0xb7, 0x75, 0x17, 0x59, 0x94,
	0x46, 0x1b, 0xe2, 0xe5, 0xbc, 0x6c, 0x6d, 0x23, 0x4c, 0x97, 0x1b, 0xbe, 0x7d, 0x48, 0x12, 0x4e,
	0x4e, 0x20, 0xe2, 0xba, 0x62, 0x12, 0xf3, 0xf6, 0xf1, 0x8d, 0x3d, 0xf0, 0xef, 0x0a, 0xab, 0x1b,
	0xa1, 0x98, 0x6a, 0x9c, 0xec, 0x53, 0x84, 0x0e, 0x25, 0xdc, 0xcd, 0x59, 0x31, 0xbc, 0x17, 0xfc,
	0x9c, 0x15, 0x73, 0x77, 0xce, 0x01, 0xb8, 0x58, 0xcb, 0x5c, 0xdc, 0xb1, 0xca, 0x47, 0x19, 0xa5,
	0xcf, 0x08, 0xb9, 0x84, 0xd9, 0xf6, 0x5c, 0xe5, 0x2c, 0x53, 0xb4, 0x4c, 0x3b, 0x88, 0xa6, 0x13,
	0x88, 0x70, 0x60, 0x34, 0xcc, 0x7c, 0x67, 0x0e, 0xa0, 0x78, 0x0e, 0xd3, 0x6e, 0x68, 0xd4, 0x7d,
	0xbc, 0x93, 0x0d, 0x43, 0xcb, 0x19, 0x4c, 0x36, 0x93, 0xa1, 0x63, 0x6f, 0xd3, 0x05, 0x22, 0x34,
	0xcc, 0x01, 0x2c, 0xab, 0xea, 0x52, 0xac, 0x64, 0x25, 0x30, 0xf5, 0x41, 0xfa, 0x8c, 0x90, 0xef,
	0xe0, 0x90, 0x15, 0x85, 0x11, 0x05, 0x73, 0x7f, 0xb1, 0x44, 0x35, 0xc2, 0xac, 0x59, 0x49, 0x0f,
	0x30, 0xea, 0x8f, 0x49, 0x24, 0x76, 0xcf, 0x2b, 0xa9, 0xaf, 0x38, 0x37, 0xc2, 0x5a, 0x4a, 0xba,
	0xa6, 0xb6, 0x88, 0x7c, 0xe3, 0x26, 0x4f, 0xea, 0xf5, 0x8f, 0x9d, 0xe7, 0x10, 0x3d, 0x2f, 0x21,
	0xf9, 0xd5, 0xb9, 0x76, 0x5f, 0x14, 0x4b, 0x8f, 0xe2, 0xfe, 0x62, 0xf2, 0xc3, 0xa5, 0xff, 0xe2,
	0x2c, 0x3f, 0xf5, 0xb5, 0xb9, 0x0e, 0xff, 0xf9, 0xa9, 0x47, 0x07, 0xe9, 0xcb, 0x03, 0xae, 0xbf,
	0xff, 0xff, 0x69, 0x1e, 0xbc, 0x7a, 0x9a, 0x07, 0x6f, 0x9e, 0xe6, 0xc1, 0xbf, 0x6f, 0xe7, 0x9f,
	0xc1, 0x59, 0xae, 0xab, 0xa5, 0x69, 0xf3, 0x3f, 0x5a, 0xfb, 0x28, 0x8d, 0x28, 0x85, 0xb5, 0x4b,
	0x9b, 0x17, 0xfe, 0x8a, 0xfb, 0xf6, 0xe1, 0x5d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xf1, 0x26,
	0x6d, 0x03, 0x05, 0x00, 0x00,
}

func (m *ApHccdClientReportConnection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApHccdClientReportConnection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApHccdClientReportConnection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.IsRoaming != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.IsRoaming))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.TTF != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.TTF))
		i--
		dAtA[i] = 0x78
	}
	if m.Info != nil {
		i -= len(*m.Info)
		copy(dAtA[i:], *m.Info)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.Info)))
		i--
		dAtA[i] = 0x72
	}
	if m.ReasonCode != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.ReasonCode))
		i--
		dAtA[i] = 0x68
	}
	if m.Vlan != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.Vlan))
		i--
		dAtA[i] = 0x60
	}
	if m.FailureType != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.FailureType))
		i--
		dAtA[i] = 0x58
	}
	if m.Snr != nil {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(*m.Snr))))
		i--
		dAtA[i] = 0x55
	}
	if m.WlanType != nil {
		i -= len(*m.WlanType)
		copy(dAtA[i:], *m.WlanType)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.WlanType)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Ssid != nil {
		i -= len(*m.Ssid)
		copy(dAtA[i:], *m.Ssid)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.Ssid)))
		i--
		dAtA[i] = 0x42
	}
	if m.RadioId != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.RadioId))
		i--
		dAtA[i] = 0x38
	}
	if m.WlanId != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.WlanId))
		i--
		dAtA[i] = 0x30
	}
	if len(m.MessageIds) > 0 {
		for iNdEx := len(m.MessageIds) - 1; iNdEx >= 0; iNdEx-- {
			i = encodeVarintApHccdReport(dAtA, i, uint64(m.MessageIds[iNdEx]))
			i--
			dAtA[i] = 0x28
		}
	}
	if m.FailedMsgId != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.FailedMsgId))
		i--
		dAtA[i] = 0x20
	}
	if m.ConnectionStatus != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.ConnectionStatus))
		i--
		dAtA[i] = 0x18
	}
	if m.Timestamp != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if m.ClientMac != nil {
		i -= len(*m.ClientMac)
		copy(dAtA[i:], *m.ClientMac)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ClientMac)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ApHccdReportMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApHccdReportMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApHccdReportMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ApHccdClients) > 0 {
		for iNdEx := len(m.ApHccdClients) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApHccdClients[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApHccdReport(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xa2
		}
	}
	if m.ApIpv6Address != nil {
		i -= len(*m.ApIpv6Address)
		copy(dAtA[i:], *m.ApIpv6Address)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ApIpv6Address)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.ApIpAddress != nil {
		i -= len(*m.ApIpAddress)
		copy(dAtA[i:], *m.ApIpAddress)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ApIpAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.AggregationInterval != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.AggregationInterval))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.SampleTime != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.SampleTime))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.DomainName != nil {
		i -= len(*m.DomainName)
		copy(dAtA[i:], *m.DomainName)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.DomainName)))
		i--
		dAtA[i] = 0x7a
	}
	if m.ApgroupName != nil {
		i -= len(*m.ApgroupName)
		copy(dAtA[i:], *m.ApgroupName)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ApgroupName)))
		i--
		dAtA[i] = 0x72
	}
	if m.ZoneName != nil {
		i -= len(*m.ZoneName)
		copy(dAtA[i:], *m.ZoneName)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ZoneName)))
		i--
		dAtA[i] = 0x6a
	}
	if m.AptenantName != nil {
		i -= len(*m.AptenantName)
		copy(dAtA[i:], *m.AptenantName)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.AptenantName)))
		i--
		dAtA[i] = 0x62
	}
	if m.DeviceName != nil {
		i -= len(*m.DeviceName)
		copy(dAtA[i:], *m.DeviceName)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.DeviceName)))
		i--
		dAtA[i] = 0x5a
	}
	if m.MapId != nil {
		i -= len(*m.MapId)
		copy(dAtA[i:], *m.MapId)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.MapId)))
		i--
		dAtA[i] = 0x52
	}
	if m.AptenantId != nil {
		i -= len(*m.AptenantId)
		copy(dAtA[i:], *m.AptenantId)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.AptenantId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.DomainId != nil {
		i -= len(*m.DomainId)
		copy(dAtA[i:], *m.DomainId)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.DomainId)))
		i--
		dAtA[i] = 0x42
	}
	if m.ClusterId != nil {
		i -= len(*m.ClusterId)
		copy(dAtA[i:], *m.ClusterId)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ClusterId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ApgroupId != nil {
		i -= len(*m.ApgroupId)
		copy(dAtA[i:], *m.ApgroupId)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ApgroupId)))
		i--
		dAtA[i] = 0x32
	}
	if m.ZoneId != nil {
		i -= len(*m.ZoneId)
		copy(dAtA[i:], *m.ZoneId)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ZoneId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.SeqNumber != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.SeqNumber))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.ApMac != nil {
		i -= len(*m.ApMac)
		copy(dAtA[i:], *m.ApMac)
		i = encodeVarintApHccdReport(dAtA, i, uint64(len(*m.ApMac)))
		i--
		dAtA[i] = 0x12
	}
	if m.Version != nil {
		i = encodeVarintApHccdReport(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApHccdReport(dAtA []byte, offset int, v uint64) int {
	offset -= sovApHccdReport(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ApHccdClientReportConnection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClientMac != nil {
		l = len(*m.ClientMac)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.Timestamp != nil {
		n += 1 + sovApHccdReport(uint64(*m.Timestamp))
	}
	if m.ConnectionStatus != nil {
		n += 1 + sovApHccdReport(uint64(*m.ConnectionStatus))
	}
	if m.FailedMsgId != nil {
		n += 1 + sovApHccdReport(uint64(*m.FailedMsgId))
	}
	if len(m.MessageIds) > 0 {
		for _, e := range m.MessageIds {
			n += 1 + sovApHccdReport(uint64(e))
		}
	}
	if m.WlanId != nil {
		n += 1 + sovApHccdReport(uint64(*m.WlanId))
	}
	if m.RadioId != nil {
		n += 1 + sovApHccdReport(uint64(*m.RadioId))
	}
	if m.Ssid != nil {
		l = len(*m.Ssid)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.WlanType != nil {
		l = len(*m.WlanType)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.Snr != nil {
		n += 5
	}
	if m.FailureType != nil {
		n += 1 + sovApHccdReport(uint64(*m.FailureType))
	}
	if m.Vlan != nil {
		n += 1 + sovApHccdReport(uint64(*m.Vlan))
	}
	if m.ReasonCode != nil {
		n += 1 + sovApHccdReport(uint64(*m.ReasonCode))
	}
	if m.Info != nil {
		l = len(*m.Info)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.TTF != nil {
		n += 1 + sovApHccdReport(uint64(*m.TTF))
	}
	if m.IsRoaming != nil {
		n += 2 + sovApHccdReport(uint64(*m.IsRoaming))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ApHccdReportMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		n += 1 + sovApHccdReport(uint64(*m.Version))
	}
	if m.ApMac != nil {
		l = len(*m.ApMac)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.Timestamp != nil {
		n += 1 + sovApHccdReport(uint64(*m.Timestamp))
	}
	if m.SeqNumber != nil {
		n += 1 + sovApHccdReport(uint64(*m.SeqNumber))
	}
	if m.ZoneId != nil {
		l = len(*m.ZoneId)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.ApgroupId != nil {
		l = len(*m.ApgroupId)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.ClusterId != nil {
		l = len(*m.ClusterId)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.DomainId != nil {
		l = len(*m.DomainId)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.AptenantId != nil {
		l = len(*m.AptenantId)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.MapId != nil {
		l = len(*m.MapId)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.DeviceName != nil {
		l = len(*m.DeviceName)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.AptenantName != nil {
		l = len(*m.AptenantName)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.ZoneName != nil {
		l = len(*m.ZoneName)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.ApgroupName != nil {
		l = len(*m.ApgroupName)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.DomainName != nil {
		l = len(*m.DomainName)
		n += 1 + l + sovApHccdReport(uint64(l))
	}
	if m.SampleTime != nil {
		n += 2 + sovApHccdReport(uint64(*m.SampleTime))
	}
	if m.AggregationInterval != nil {
		n += 2 + sovApHccdReport(uint64(*m.AggregationInterval))
	}
	if m.ApIpAddress != nil {
		l = len(*m.ApIpAddress)
		n += 2 + l + sovApHccdReport(uint64(l))
	}
	if m.ApIpv6Address != nil {
		l = len(*m.ApIpv6Address)
		n += 2 + l + sovApHccdReport(uint64(l))
	}
	if len(m.ApHccdClients) > 0 {
		for _, e := range m.ApHccdClients {
			l = e.Size()
			n += 2 + l + sovApHccdReport(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApHccdReport(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApHccdReport(x uint64) (n int) {
	return sovApHccdReport(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ApHccdClientReportConnection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApHccdReport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApHccdClientReportConnection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApHccdClientReportConnection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClientMac = &s
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionStatus", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ConnectionStatus = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailedMsgId", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FailedMsgId = &v
		case 5:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApHccdReport
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.MessageIds = append(m.MessageIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApHccdReport
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthApHccdReport
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthApHccdReport
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.MessageIds) == 0 {
					m.MessageIds = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowApHccdReport
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.MessageIds = append(m.MessageIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageIds", wireType)
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlanId", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WlanId = &v
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RadioId", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RadioId = &v
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ssid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Ssid = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlanType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.WlanType = &s
			iNdEx = postIndex
		case 10:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snr", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			v2 := float32(math.Float32frombits(v))
			m.Snr = &v2
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailureType", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FailureType = &v
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vlan", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Vlan = &v
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasonCode", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReasonCode = &v
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Info = &s
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TTF", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TTF = &v
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRoaming", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsRoaming = &v
		default:
			iNdEx = preIndex
			skippy, err := skipApHccdReport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApHccdReportMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApHccdReport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApHccdReportMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApHccdReportMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApMac = &s
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeqNumber", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SeqNumber = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneId = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApgroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApgroupId = &s
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClusterId = &s
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainId = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AptenantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AptenantId = &s
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MapId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MapId = &s
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DeviceName = &s
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AptenantName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AptenantName = &s
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneName = &s
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApgroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApgroupName = &s
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainName = &s
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleTime", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SampleTime = &v
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationInterval", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AggregationInterval = &v
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApIpAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApIpAddress = &s
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApIpv6Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApIpv6Address = &s
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApHccdClients", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApHccdReport
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApHccdClients = append(m.ApHccdClients, &ApHccdClientReportConnection{})
			if err := m.ApHccdClients[len(m.ApHccdClients)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApHccdReport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApHccdReport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApHccdReport(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApHccdReport
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApHccdReport
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApHccdReport
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApHccdReport
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApHccdReport
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApHccdReport        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApHccdReport          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApHccdReport = fmt.Errorf("proto: unexpected end of group")
)
