// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ap_mesh.proto

package proto

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type APMeshDownlink struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description MAC address of the mesh downlink AP
	// @since 3.5
	DownMac *string `protobuf:"bytes,1,req,name=downMac" json:"downMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Link status of the mesh downlink AP
	// @since 3.5
	Type *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	//*
	// @property snapshot
	// @aggregation AVG
	// @description RSSI of the mesh downlink AP
	// @since 3.5
	Rssi *int32 `protobuf:"varint,3,opt,name=rssi" json:"rssi,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total size of data and management packets transmitted since the last AP restart
	// @since 3.5
	TxBytes *uint64 `protobuf:"varint,4,opt,name=txBytes" json:"txBytes,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total number of data and management packets transmitted since the last AP restart
	// @since 3.5
	TxFrames *uint64 `protobuf:"varint,5,opt,name=txFrames" json:"txFrames,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total size of data and management packets received since the last AP restart
	// @since 3.5
	RxBytes *uint64 `protobuf:"varint,6,opt,name=rxBytes" json:"rxBytes,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total number of data and management packets received since the last AP restart
	// @since 3.5
	RxFrames             *uint64  `protobuf:"varint,7,opt,name=rxFrames" json:"rxFrames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APMeshDownlink) Reset()         { *m = APMeshDownlink{} }
func (m *APMeshDownlink) String() string { return proto.CompactTextString(m) }
func (*APMeshDownlink) ProtoMessage()    {}
func (*APMeshDownlink) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca2cd363a234d06, []int{0}
}
func (m *APMeshDownlink) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *APMeshDownlink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_APMeshDownlink.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *APMeshDownlink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APMeshDownlink.Merge(m, src)
}
func (m *APMeshDownlink) XXX_Size() int {
	return m.Size()
}
func (m *APMeshDownlink) XXX_DiscardUnknown() {
	xxx_messageInfo_APMeshDownlink.DiscardUnknown(m)
}

var xxx_messageInfo_APMeshDownlink proto.InternalMessageInfo

func (m *APMeshDownlink) GetDownMac() string {
	if m != nil && m.DownMac != nil {
		return *m.DownMac
	}
	return ""
}

func (m *APMeshDownlink) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *APMeshDownlink) GetRssi() int32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *APMeshDownlink) GetTxBytes() uint64 {
	if m != nil && m.TxBytes != nil {
		return *m.TxBytes
	}
	return 0
}

func (m *APMeshDownlink) GetTxFrames() uint64 {
	if m != nil && m.TxFrames != nil {
		return *m.TxFrames
	}
	return 0
}

func (m *APMeshDownlink) GetRxBytes() uint64 {
	if m != nil && m.RxBytes != nil {
		return *m.RxBytes
	}
	return 0
}

func (m *APMeshDownlink) GetRxFrames() uint64 {
	if m != nil && m.RxFrames != nil {
		return *m.RxFrames
	}
	return 0
}

type APMeshUplink struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description MAC address of the mesh uplink AP
	// @since 3.5
	UpMac *string `protobuf:"bytes,1,req,name=upMac" json:"upMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Link status of the mesh uplink AP
	// @since 3.5
	Type *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	//*
	// @property snapshot
	// @aggregation AVG
	// @description RSSI of the mesh uplink AP
	// @since 3.5
	Rssi *int32 `protobuf:"varint,3,opt,name=rssi" json:"rssi,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total size of data and management packets transmitted since the last AP restart
	// @since 3.5
	TxBytes *uint64 `protobuf:"varint,4,opt,name=txBytes" json:"txBytes,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total number of data and management packets transmitted since the last AP restart
	// @since 3.5
	TxFrames *uint64 `protobuf:"varint,5,opt,name=txFrames" json:"txFrames,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total size of data and management packets received  since the last AP restart
	// @since 3.5
	RxBytes *uint64 `protobuf:"varint,6,opt,name=rxBytes" json:"rxBytes,omitempty"`
	//*
	// @property snapshot
	// @aggregation SUM
	// @description Total number of data and management packets received since the last AP restart
	// @since 3.5
	RxFrames             *uint64  `protobuf:"varint,7,opt,name=rxFrames" json:"rxFrames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APMeshUplink) Reset()         { *m = APMeshUplink{} }
func (m *APMeshUplink) String() string { return proto.CompactTextString(m) }
func (*APMeshUplink) ProtoMessage()    {}
func (*APMeshUplink) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca2cd363a234d06, []int{1}
}
func (m *APMeshUplink) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *APMeshUplink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_APMeshUplink.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *APMeshUplink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APMeshUplink.Merge(m, src)
}
func (m *APMeshUplink) XXX_Size() int {
	return m.Size()
}
func (m *APMeshUplink) XXX_DiscardUnknown() {
	xxx_messageInfo_APMeshUplink.DiscardUnknown(m)
}

var xxx_messageInfo_APMeshUplink proto.InternalMessageInfo

func (m *APMeshUplink) GetUpMac() string {
	if m != nil && m.UpMac != nil {
		return *m.UpMac
	}
	return ""
}

func (m *APMeshUplink) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *APMeshUplink) GetRssi() int32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *APMeshUplink) GetTxBytes() uint64 {
	if m != nil && m.TxBytes != nil {
		return *m.TxBytes
	}
	return 0
}

func (m *APMeshUplink) GetTxFrames() uint64 {
	if m != nil && m.TxFrames != nil {
		return *m.TxFrames
	}
	return 0
}

func (m *APMeshUplink) GetRxBytes() uint64 {
	if m != nil && m.RxBytes != nil {
		return *m.RxBytes
	}
	return 0
}

func (m *APMeshUplink) GetRxFrames() uint64 {
	if m != nil && m.RxFrames != nil {
		return *m.RxFrames
	}
	return 0
}

type APMeshNeighbor struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description MAC address of the neigboring AP
	// @since 3.5
	Mac *string `protobuf:"bytes,1,req,name=mac" json:"mac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description RSSI of the neighboring AP
	// @since 3.5
	Rssi                 *int32   `protobuf:"varint,2,opt,name=rssi" json:"rssi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APMeshNeighbor) Reset()         { *m = APMeshNeighbor{} }
func (m *APMeshNeighbor) String() string { return proto.CompactTextString(m) }
func (*APMeshNeighbor) ProtoMessage()    {}
func (*APMeshNeighbor) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca2cd363a234d06, []int{2}
}
func (m *APMeshNeighbor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *APMeshNeighbor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_APMeshNeighbor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *APMeshNeighbor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APMeshNeighbor.Merge(m, src)
}
func (m *APMeshNeighbor) XXX_Size() int {
	return m.Size()
}
func (m *APMeshNeighbor) XXX_DiscardUnknown() {
	xxx_messageInfo_APMeshNeighbor.DiscardUnknown(m)
}

var xxx_messageInfo_APMeshNeighbor proto.InternalMessageInfo

func (m *APMeshNeighbor) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *APMeshNeighbor) GetRssi() int32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

type APMeshStats struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Mesh stats version
	// @since 3.5
	Version *uint32 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description MAC address of the AP
	// @since 3.5
	Ap *string `protobuf:"bytes,2,req,name=ap" json:"ap,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Date and time these statistics were generated
	// @since 3.5
	Timestamp *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Counter for generating mesh statistics. The count increases by one whenever the AP generates mesh statistics. When the AP restarts, the counter also resets to zero (0).
	// @since 3.5
	SeqNumber *uint64 `protobuf:"varint,4,opt,name=seqNumber" json:"seqNumber,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Unique zone ID (for example, b381206b-2e5d-43dc-b249-e36ffae9855c) assigned by the controller
	// @since 3.5
	ZoneId *string `protobuf:"bytes,5,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Role of the AP on the mesh network (if mesh networking is enabled). Possible values include: (0:MESH_DISABLED, 1: MESH_RAP, 2:MESH_MAP, 3:MESH_EAP, 4:MESH_DOWN, 5: MESH_UNDEFINED)
	// @since 3.5
	MeshRole *int32 `protobuf:"varint,6,opt,name=meshRole" json:"meshRole,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description SSID of the mesh network
	// @since 3.5
	MeshSSID *string `protobuf:"bytes,7,opt,name=meshSSID" json:"meshSSID,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Passphrase required for the AP to join the mesh network
	// @since 3.5
	MeshPassphraseMD5 *string `protobuf:"bytes,8,opt,name=meshPassphraseMD5" json:"meshPassphraseMD5,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Depth or number of hops between this AP and its parent root AP
	// @since 3.5
	Hops *int32 `protobuf:"varint,9,opt,name=hops" json:"hops,omitempty"`
	//*
	// @property Serialization
	// @aggregation NULL
	// @description Serialization neighbors data
	// @since 3.5
	Neighbor []*APMeshNeighbor `protobuf:"bytes,10,rep,name=neighbor" json:"neighbor,omitempty"`
	//*
	// @property Serialization
	// @aggregation NULL
	// @description Serialization mesh uplink data
	// @since 3.5
	Uplink []*APMeshUplink `protobuf:"bytes,11,rep,name=uplink" json:"uplink,omitempty"`
	//*
	// @property Serialization
	// @aggregation NULL
	// @description serialization mesh downlink data
	// @since 3.5
	Downlink []*APMeshDownlink `protobuf:"bytes,12,rep,name=downlink" json:"downlink,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP group UUID
	// @since 3.5
	ApgroupId *string `protobuf:"bytes,13,opt,name=apgroup_id,json=apgroupId" json:"apgroup_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Cluster UUID
	// @since 3.5
	ClusterId *string `protobuf:"bytes,14,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain UUID
	// @since 3.5
	DomainId *string `protobuf:"bytes,15,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP tenant UUID
	// @since 3.5
	AptenantId *string `protobuf:"bytes,16,opt,name=aptenant_id,json=aptenantId" json:"aptenant_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description MAP UUID
	// @since 3.5
	MapId *string `protobuf:"bytes,17,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP tenant name
	// @since 3.5
	AptenantName *string `protobuf:"bytes,18,opt,name=aptenant_name,json=aptenantName" json:"aptenant_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone name
	// @since 3.5
	ZoneName *string `protobuf:"bytes,19,opt,name=zone_name,json=zoneName" json:"zone_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP group name
	// @since 3.5
	ApgroupName *string `protobuf:"bytes,20,opt,name=apgroup_name,json=apgroupName" json:"apgroup_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain name
	// @since 3.5
	DomainName *string `protobuf:"bytes,21,opt,name=domain_name,json=domainName" json:"domain_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Timestamp for generating this stats report
	// @since 3.5
	SampleTime *uint64 `protobuf:"varint,22,opt,name=sampleTime" json:"sampleTime,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Interval time to aggregate data
	// @since 3.5
	AggregationInterval *uint32 `protobuf:"varint,23,opt,name=aggregationInterval" json:"aggregationInterval,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description An indicate for mesh status
	// @since 3.5
	IsMeshEnable *bool `protobuf:"varint,24,opt,name=isMeshEnable" json:"isMeshEnable,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description The serial number in AP borad data
	// @since 5.1.1
	SerialNumber         *string  `protobuf:"bytes,25,opt,name=serialNumber" json:"serialNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APMeshStats) Reset()         { *m = APMeshStats{} }
func (m *APMeshStats) String() string { return proto.CompactTextString(m) }
func (*APMeshStats) ProtoMessage()    {}
func (*APMeshStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_cca2cd363a234d06, []int{3}
}
func (m *APMeshStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *APMeshStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_APMeshStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *APMeshStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APMeshStats.Merge(m, src)
}
func (m *APMeshStats) XXX_Size() int {
	return m.Size()
}
func (m *APMeshStats) XXX_DiscardUnknown() {
	xxx_messageInfo_APMeshStats.DiscardUnknown(m)
}

var xxx_messageInfo_APMeshStats proto.InternalMessageInfo

func (m *APMeshStats) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *APMeshStats) GetAp() string {
	if m != nil && m.Ap != nil {
		return *m.Ap
	}
	return ""
}

func (m *APMeshStats) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *APMeshStats) GetSeqNumber() uint64 {
	if m != nil && m.SeqNumber != nil {
		return *m.SeqNumber
	}
	return 0
}

func (m *APMeshStats) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *APMeshStats) GetMeshRole() int32 {
	if m != nil && m.MeshRole != nil {
		return *m.MeshRole
	}
	return 0
}

func (m *APMeshStats) GetMeshSSID() string {
	if m != nil && m.MeshSSID != nil {
		return *m.MeshSSID
	}
	return ""
}

func (m *APMeshStats) GetMeshPassphraseMD5() string {
	if m != nil && m.MeshPassphraseMD5 != nil {
		return *m.MeshPassphraseMD5
	}
	return ""
}

func (m *APMeshStats) GetHops() int32 {
	if m != nil && m.Hops != nil {
		return *m.Hops
	}
	return 0
}

func (m *APMeshStats) GetNeighbor() []*APMeshNeighbor {
	if m != nil {
		return m.Neighbor
	}
	return nil
}

func (m *APMeshStats) GetUplink() []*APMeshUplink {
	if m != nil {
		return m.Uplink
	}
	return nil
}

func (m *APMeshStats) GetDownlink() []*APMeshDownlink {
	if m != nil {
		return m.Downlink
	}
	return nil
}

func (m *APMeshStats) GetApgroupId() string {
	if m != nil && m.ApgroupId != nil {
		return *m.ApgroupId
	}
	return ""
}

func (m *APMeshStats) GetClusterId() string {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return ""
}

func (m *APMeshStats) GetDomainId() string {
	if m != nil && m.DomainId != nil {
		return *m.DomainId
	}
	return ""
}

func (m *APMeshStats) GetAptenantId() string {
	if m != nil && m.AptenantId != nil {
		return *m.AptenantId
	}
	return ""
}

func (m *APMeshStats) GetMapId() string {
	if m != nil && m.MapId != nil {
		return *m.MapId
	}
	return ""
}

func (m *APMeshStats) GetAptenantName() string {
	if m != nil && m.AptenantName != nil {
		return *m.AptenantName
	}
	return ""
}

func (m *APMeshStats) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *APMeshStats) GetApgroupName() string {
	if m != nil && m.ApgroupName != nil {
		return *m.ApgroupName
	}
	return ""
}

func (m *APMeshStats) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *APMeshStats) GetSampleTime() uint64 {
	if m != nil && m.SampleTime != nil {
		return *m.SampleTime
	}
	return 0
}

func (m *APMeshStats) GetAggregationInterval() uint32 {
	if m != nil && m.AggregationInterval != nil {
		return *m.AggregationInterval
	}
	return 0
}

func (m *APMeshStats) GetIsMeshEnable() bool {
	if m != nil && m.IsMeshEnable != nil {
		return *m.IsMeshEnable
	}
	return false
}

func (m *APMeshStats) GetSerialNumber() string {
	if m != nil && m.SerialNumber != nil {
		return *m.SerialNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*APMeshDownlink)(nil), "proto.APMeshDownlink")
	proto.RegisterType((*APMeshUplink)(nil), "proto.APMeshUplink")
	proto.RegisterType((*APMeshNeighbor)(nil), "proto.APMeshNeighbor")
	proto.RegisterType((*APMeshStats)(nil), "proto.APMeshStats")
}

func init() { proto.RegisterFile("ap_mesh.proto", fileDescriptor_cca2cd363a234d06) }

var fileDescriptor_cca2cd363a234d06 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcf, 0x6e, 0x13, 0x3f,
	0x10, 0xfe, 0x6d, 0x9a, 0xa4, 0xd9, 0x49, 0xd2, 0x5f, 0xeb, 0xb6, 0xd4, 0xfc, 0x4b, 0x43, 0xb8,
	0x44, 0x02, 0x45, 0x14, 0x09, 0xee, 0x54, 0x05, 0x69, 0x0f, 0xad, 0x2a, 0x17, 0xce, 0x95, 0x93,
	0x35, 0xc9, 0xaa, 0xeb, 0x5d, 0x63, 0x7b, 0xfb, 0x87, 0x27, 0xe1, 0x51, 0x38, 0x71, 0xe6, 0xc0,
	0x81, 0x47, 0x40, 0xe5, 0x45, 0x90, 0xc7, 0xbb, 0x9b, 0x56, 0xf4, 0x01, 0x38, 0xad, 0xe7, 0xfb,
	0xe6, 0xf3, 0xcc, 0x37, 0x3b, 0x86, 0x3e, 0x57, 0xa7, 0x52, 0x98, 0xc5, 0x44, 0xe9, 0xdc, 0xe6,
	0xa4, 0x85, 0x9f, 0xd1, 0xb7, 0x00, 0xd6, 0xde, 0x1c, 0x1f, 0x0a, 0xb3, 0x38, 0xc8, 0x2f, 0xb2,
	0x34, 0xc9, 0xce, 0x08, 0x85, 0xd5, 0x38, 0xbf, 0xc8, 0x0e, 0xf9, 0x8c, 0x06, 0xc3, 0xc6, 0x38,
	0x64, 0x55, 0x48, 0x08, 0x34, 0xed, 0x95, 0x12, 0xb4, 0x31, 0x0c, 0xc6, 0x7d, 0x86, 0x67, 0x87,
	0x69, 0x63, 0x12, 0xba, 0x32, 0x0c, 0xc6, 0x2d, 0x86, 0x67, 0x77, 0x83, 0xbd, 0xdc, 0xbf, 0xb2,
	0xc2, 0xd0, 0xe6, 0x30, 0x18, 0x37, 0x59, 0x15, 0x92, 0x07, 0xd0, 0xb1, 0x97, 0xef, 0x34, 0x97,
	0xc2, 0xd0, 0x16, 0x52, 0x75, 0xec, 0x54, 0xba, 0x54, 0xb5, 0xbd, 0x4a, 0x2f, 0x55, 0xba, 0x52,
	0xad, 0x7a, 0x55, 0x15, 0x8f, 0xbe, 0x06, 0xd0, 0xf3, 0x06, 0x3e, 0x28, 0x6c, 0x7f, 0x0b, 0x5a,
	0x85, 0x5a, 0x36, 0xef, 0x83, 0x7f, 0xb2, 0xf5, 0xd7, 0xd5, 0xe8, 0x8f, 0x44, 0x32, 0x5f, 0x4c,
	0x73, 0x4d, 0xd6, 0x61, 0x45, 0xd6, 0x9d, 0xbb, 0x63, 0xdd, 0x63, 0x63, 0xd9, 0xe3, 0xe8, 0x47,
	0x1b, 0xba, 0x5e, 0x78, 0x62, 0xb9, 0xc5, 0xea, 0xe7, 0x42, 0x9b, 0x24, 0xcf, 0x50, 0xd9, 0x67,
	0x55, 0x48, 0xd6, 0xa0, 0xc1, 0x15, 0x6d, 0xe0, 0x75, 0x0d, 0xae, 0xc8, 0x23, 0x08, 0x6d, 0x22,
	0x85, 0xb1, 0x5c, 0x2a, 0xb4, 0xdd, 0x64, 0x4b, 0xc0, 0xb1, 0x46, 0x7c, 0x3a, 0x2a, 0xe4, 0x54,
	0xe8, 0xd2, 0xfd, 0x12, 0x20, 0x3b, 0xb0, 0xfa, 0x39, 0xcf, 0xc4, 0x69, 0x12, 0xa3, 0xfd, 0x90,
	0xb5, 0x5d, 0x18, 0xc5, 0xce, 0xa2, 0xdb, 0x2b, 0x96, 0xa7, 0x02, 0xdd, 0xb7, 0x58, 0x1d, 0x57,
	0xdc, 0xc9, 0x49, 0x74, 0x80, 0xf6, 0x43, 0x56, 0xc7, 0xe4, 0x39, 0x6c, 0xb8, 0xf3, 0x31, 0x37,
	0x46, 0x2d, 0x34, 0x37, 0xe2, 0xf0, 0xe0, 0x15, 0xed, 0x60, 0xd2, 0xdf, 0x84, 0x1b, 0xc4, 0x22,
	0x57, 0x86, 0x86, 0x7e, 0x10, 0xee, 0x4c, 0xf6, 0xa0, 0x93, 0x95, 0xa3, 0xa3, 0x30, 0x5c, 0x19,
	0x77, 0x5f, 0x6e, 0xfb, 0xed, 0x9e, 0xdc, 0x9e, 0x2b, 0xab, 0xd3, 0xc8, 0x33, 0x68, 0x17, 0xb8,
	0x27, 0xb4, 0x8b, 0x82, 0xcd, 0x5b, 0x02, 0xbf, 0x42, 0xac, 0x4c, 0x71, 0xf7, 0xc7, 0xe5, 0xab,
	0xa0, 0xbd, 0x3b, 0xee, 0xaf, 0x9e, 0x0c, 0xab, 0xd3, 0xc8, 0x63, 0x00, 0xae, 0xe6, 0x3a, 0x2f,
	0x94, 0x1b, 0x54, 0x1f, 0xdd, 0x84, 0x25, 0x12, 0xc5, 0x8e, 0x9e, 0xa5, 0x85, 0xb1, 0x42, 0x3b,
	0x7a, 0xcd, 0xd3, 0x25, 0x12, 0xc5, 0xe4, 0x21, 0x84, 0x71, 0x2e, 0x79, 0x92, 0x39, 0xf6, 0x7f,
	0x3f, 0x2f, 0x0f, 0x44, 0x31, 0xd9, 0x85, 0x2e, 0x57, 0x56, 0x64, 0x3c, 0xb3, 0x8e, 0x5e, 0x47,
	0x1a, 0x2a, 0x28, 0x8a, 0xc9, 0x36, 0xb4, 0x25, 0xc7, 0xba, 0x1b, 0xc8, 0xb5, 0x24, 0x77, 0x35,
	0x9f, 0xba, 0xa7, 0x5f, 0xea, 0x32, 0x2e, 0x05, 0x25, 0xc8, 0xf6, 0x2a, 0xf0, 0x88, 0x4b, 0xe1,
	0x2a, 0xe3, 0xdf, 0xc5, 0x84, 0x4d, 0x5f, 0xd9, 0x01, 0x48, 0x3e, 0x81, 0x5e, 0x65, 0x0a, 0xf9,
	0x2d, 0xe4, 0xbb, 0x25, 0x86, 0x29, 0xbb, 0xd0, 0x2d, 0x3b, 0xc7, 0x8c, 0x6d, 0xdf, 0x9c, 0x87,
	0x30, 0x61, 0x00, 0x60, 0xb8, 0x54, 0xa9, 0x78, 0x9f, 0x48, 0x41, 0xef, 0xe1, 0x76, 0xdd, 0x40,
	0xc8, 0x0b, 0xd8, 0xe4, 0xf3, 0xb9, 0x16, 0x73, 0x6e, 0x93, 0x3c, 0x8b, 0x32, 0x2b, 0xf4, 0x39,
	0x4f, 0xe9, 0x0e, 0xbe, 0xd7, 0xbb, 0x28, 0x32, 0x82, 0x5e, 0x62, 0xdc, 0x6f, 0x78, 0x9b, 0xf1,
	0x69, 0x2a, 0x28, 0x1d, 0x06, 0xe3, 0x0e, 0xbb, 0x85, 0xb9, 0x1c, 0x23, 0x74, 0xc2, 0xd3, 0x72,
	0xab, 0xef, 0x7b, 0xeb, 0x37, 0xb1, 0xfd, 0xbd, 0xef, 0xd7, 0x83, 0xe0, 0xe7, 0xf5, 0x20, 0xf8,
	0x75, 0x3d, 0x08, 0xbe, 0xfc, 0x1e, 0xfc, 0x07, 0xbb, 0xb3, 0x5c, 0x4e, 0x74, 0x31, 0x3b, 0x2b,
	0xcc, 0x45, 0xa2, 0x45, 0x2a, 0x8c, 0x99, 0x98, 0xd9, 0xdc, 0xff, 0xfb, 0x69, 0xf1, 0xf1, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x22, 0xb6, 0x00, 0x4c, 0x05, 0x00, 0x00,
}

func (m *APMeshDownlink) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *APMeshDownlink) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *APMeshDownlink) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.RxFrames != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.RxFrames))
		i--
		dAtA[i] = 0x38
	}
	if m.RxBytes != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.RxBytes))
		i--
		dAtA[i] = 0x30
	}
	if m.TxFrames != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.TxFrames))
		i--
		dAtA[i] = 0x28
	}
	if m.TxBytes != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.TxBytes))
		i--
		dAtA[i] = 0x20
	}
	if m.Rssi != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Rssi))
		i--
		dAtA[i] = 0x18
	}
	if m.Type != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Type))
		i--
		dAtA[i] = 0x10
	}
	if m.DownMac == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i -= len(*m.DownMac)
		copy(dAtA[i:], *m.DownMac)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.DownMac)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *APMeshUplink) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *APMeshUplink) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *APMeshUplink) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.RxFrames != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.RxFrames))
		i--
		dAtA[i] = 0x38
	}
	if m.RxBytes != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.RxBytes))
		i--
		dAtA[i] = 0x30
	}
	if m.TxFrames != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.TxFrames))
		i--
		dAtA[i] = 0x28
	}
	if m.TxBytes != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.TxBytes))
		i--
		dAtA[i] = 0x20
	}
	if m.Rssi != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Rssi))
		i--
		dAtA[i] = 0x18
	}
	if m.Type != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Type))
		i--
		dAtA[i] = 0x10
	}
	if m.UpMac == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i -= len(*m.UpMac)
		copy(dAtA[i:], *m.UpMac)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.UpMac)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *APMeshNeighbor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *APMeshNeighbor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *APMeshNeighbor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Rssi != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Rssi))
		i--
		dAtA[i] = 0x10
	}
	if m.Mac == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i -= len(*m.Mac)
		copy(dAtA[i:], *m.Mac)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.Mac)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *APMeshStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *APMeshStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *APMeshStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.SerialNumber != nil {
		i -= len(*m.SerialNumber)
		copy(dAtA[i:], *m.SerialNumber)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.SerialNumber)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if m.IsMeshEnable != nil {
		i--
		if *m.IsMeshEnable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if m.AggregationInterval != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.AggregationInterval))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.SampleTime != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.SampleTime))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.DomainName != nil {
		i -= len(*m.DomainName)
		copy(dAtA[i:], *m.DomainName)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.DomainName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.ApgroupName != nil {
		i -= len(*m.ApgroupName)
		copy(dAtA[i:], *m.ApgroupName)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.ApgroupName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.ZoneName != nil {
		i -= len(*m.ZoneName)
		copy(dAtA[i:], *m.ZoneName)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.ZoneName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.AptenantName != nil {
		i -= len(*m.AptenantName)
		copy(dAtA[i:], *m.AptenantName)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.AptenantName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.MapId != nil {
		i -= len(*m.MapId)
		copy(dAtA[i:], *m.MapId)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.MapId)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.AptenantId != nil {
		i -= len(*m.AptenantId)
		copy(dAtA[i:], *m.AptenantId)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.AptenantId)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.DomainId != nil {
		i -= len(*m.DomainId)
		copy(dAtA[i:], *m.DomainId)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.DomainId)))
		i--
		dAtA[i] = 0x7a
	}
	if m.ClusterId != nil {
		i -= len(*m.ClusterId)
		copy(dAtA[i:], *m.ClusterId)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.ClusterId)))
		i--
		dAtA[i] = 0x72
	}
	if m.ApgroupId != nil {
		i -= len(*m.ApgroupId)
		copy(dAtA[i:], *m.ApgroupId)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.ApgroupId)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Downlink) > 0 {
		for iNdEx := len(m.Downlink) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Downlink[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApMesh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.Uplink) > 0 {
		for iNdEx := len(m.Uplink) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Uplink[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApMesh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.Neighbor) > 0 {
		for iNdEx := len(m.Neighbor) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Neighbor[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApMesh(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.Hops != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Hops))
		i--
		dAtA[i] = 0x48
	}
	if m.MeshPassphraseMD5 != nil {
		i -= len(*m.MeshPassphraseMD5)
		copy(dAtA[i:], *m.MeshPassphraseMD5)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.MeshPassphraseMD5)))
		i--
		dAtA[i] = 0x42
	}
	if m.MeshSSID != nil {
		i -= len(*m.MeshSSID)
		copy(dAtA[i:], *m.MeshSSID)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.MeshSSID)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MeshRole != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.MeshRole))
		i--
		dAtA[i] = 0x30
	}
	if m.ZoneId != nil {
		i -= len(*m.ZoneId)
		copy(dAtA[i:], *m.ZoneId)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.ZoneId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.SeqNumber != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.SeqNumber))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != nil {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.Ap == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i -= len(*m.Ap)
		copy(dAtA[i:], *m.Ap)
		i = encodeVarintApMesh(dAtA, i, uint64(len(*m.Ap)))
		i--
		dAtA[i] = 0x12
	}
	if m.Version == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintApMesh(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApMesh(dAtA []byte, offset int, v uint64) int {
	offset -= sovApMesh(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *APMeshDownlink) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownMac != nil {
		l = len(*m.DownMac)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.Type != nil {
		n += 1 + sovApMesh(uint64(*m.Type))
	}
	if m.Rssi != nil {
		n += 1 + sovApMesh(uint64(*m.Rssi))
	}
	if m.TxBytes != nil {
		n += 1 + sovApMesh(uint64(*m.TxBytes))
	}
	if m.TxFrames != nil {
		n += 1 + sovApMesh(uint64(*m.TxFrames))
	}
	if m.RxBytes != nil {
		n += 1 + sovApMesh(uint64(*m.RxBytes))
	}
	if m.RxFrames != nil {
		n += 1 + sovApMesh(uint64(*m.RxFrames))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *APMeshUplink) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpMac != nil {
		l = len(*m.UpMac)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.Type != nil {
		n += 1 + sovApMesh(uint64(*m.Type))
	}
	if m.Rssi != nil {
		n += 1 + sovApMesh(uint64(*m.Rssi))
	}
	if m.TxBytes != nil {
		n += 1 + sovApMesh(uint64(*m.TxBytes))
	}
	if m.TxFrames != nil {
		n += 1 + sovApMesh(uint64(*m.TxFrames))
	}
	if m.RxBytes != nil {
		n += 1 + sovApMesh(uint64(*m.RxBytes))
	}
	if m.RxFrames != nil {
		n += 1 + sovApMesh(uint64(*m.RxFrames))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *APMeshNeighbor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Mac != nil {
		l = len(*m.Mac)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.Rssi != nil {
		n += 1 + sovApMesh(uint64(*m.Rssi))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *APMeshStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		n += 1 + sovApMesh(uint64(*m.Version))
	}
	if m.Ap != nil {
		l = len(*m.Ap)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.Timestamp != nil {
		n += 1 + sovApMesh(uint64(*m.Timestamp))
	}
	if m.SeqNumber != nil {
		n += 1 + sovApMesh(uint64(*m.SeqNumber))
	}
	if m.ZoneId != nil {
		l = len(*m.ZoneId)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.MeshRole != nil {
		n += 1 + sovApMesh(uint64(*m.MeshRole))
	}
	if m.MeshSSID != nil {
		l = len(*m.MeshSSID)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.MeshPassphraseMD5 != nil {
		l = len(*m.MeshPassphraseMD5)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.Hops != nil {
		n += 1 + sovApMesh(uint64(*m.Hops))
	}
	if len(m.Neighbor) > 0 {
		for _, e := range m.Neighbor {
			l = e.Size()
			n += 1 + l + sovApMesh(uint64(l))
		}
	}
	if len(m.Uplink) > 0 {
		for _, e := range m.Uplink {
			l = e.Size()
			n += 1 + l + sovApMesh(uint64(l))
		}
	}
	if len(m.Downlink) > 0 {
		for _, e := range m.Downlink {
			l = e.Size()
			n += 1 + l + sovApMesh(uint64(l))
		}
	}
	if m.ApgroupId != nil {
		l = len(*m.ApgroupId)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.ClusterId != nil {
		l = len(*m.ClusterId)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.DomainId != nil {
		l = len(*m.DomainId)
		n += 1 + l + sovApMesh(uint64(l))
	}
	if m.AptenantId != nil {
		l = len(*m.AptenantId)
		n += 2 + l + sovApMesh(uint64(l))
	}
	if m.MapId != nil {
		l = len(*m.MapId)
		n += 2 + l + sovApMesh(uint64(l))
	}
	if m.AptenantName != nil {
		l = len(*m.AptenantName)
		n += 2 + l + sovApMesh(uint64(l))
	}
	if m.ZoneName != nil {
		l = len(*m.ZoneName)
		n += 2 + l + sovApMesh(uint64(l))
	}
	if m.ApgroupName != nil {
		l = len(*m.ApgroupName)
		n += 2 + l + sovApMesh(uint64(l))
	}
	if m.DomainName != nil {
		l = len(*m.DomainName)
		n += 2 + l + sovApMesh(uint64(l))
	}
	if m.SampleTime != nil {
		n += 2 + sovApMesh(uint64(*m.SampleTime))
	}
	if m.AggregationInterval != nil {
		n += 2 + sovApMesh(uint64(*m.AggregationInterval))
	}
	if m.IsMeshEnable != nil {
		n += 3
	}
	if m.SerialNumber != nil {
		l = len(*m.SerialNumber)
		n += 2 + l + sovApMesh(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApMesh(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApMesh(x uint64) (n int) {
	return sovApMesh(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *APMeshDownlink) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApMesh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: APMeshDownlink: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: APMeshDownlink: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DownMac = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Type = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rssi", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Rssi = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBytes", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxBytes = &v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxFrames", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxFrames = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxBytes", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxBytes = &v
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxFrames", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxFrames = &v
		default:
			iNdEx = preIndex
			skippy, err := skipApMesh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *APMeshUplink) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApMesh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: APMeshUplink: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: APMeshUplink: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.UpMac = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Type = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rssi", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Rssi = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBytes", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxBytes = &v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxFrames", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxFrames = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxBytes", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxBytes = &v
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxFrames", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxFrames = &v
		default:
			iNdEx = preIndex
			skippy, err := skipApMesh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *APMeshNeighbor) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApMesh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: APMeshNeighbor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: APMeshNeighbor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Mac = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rssi", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Rssi = &v
		default:
			iNdEx = preIndex
			skippy, err := skipApMesh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *APMeshStats) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApMesh
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: APMeshStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: APMeshStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Ap = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeqNumber", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SeqNumber = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneId = &s
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MeshRole", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MeshRole = &v
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MeshSSID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MeshSSID = &s
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MeshPassphraseMD5", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MeshPassphraseMD5 = &s
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hops", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Hops = &v
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Neighbor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Neighbor = append(m.Neighbor, &APMeshNeighbor{})
			if err := m.Neighbor[len(m.Neighbor)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uplink", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uplink = append(m.Uplink, &APMeshUplink{})
			if err := m.Uplink[len(m.Uplink)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Downlink", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Downlink = append(m.Downlink, &APMeshDownlink{})
			if err := m.Downlink[len(m.Downlink)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApgroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApgroupId = &s
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClusterId = &s
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainId = &s
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AptenantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AptenantId = &s
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MapId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MapId = &s
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AptenantName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AptenantName = &s
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneName = &s
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApgroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApgroupName = &s
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainName = &s
			iNdEx = postIndex
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleTime", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SampleTime = &v
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationInterval", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AggregationInterval = &v
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMeshEnable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.IsMeshEnable = &b
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SerialNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApMesh
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApMesh
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SerialNumber = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApMesh(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApMesh
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApMesh(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApMesh
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApMesh
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApMesh
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApMesh
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApMesh
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApMesh        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApMesh          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApMesh = fmt.Errorf("proto: unexpected end of group")
)
