// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ap_rogue.proto

package proto

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReportType_RogueType int32

const (
	//*
	// @description Rogue type possible value
	// @since 3.5
	ReportType_DISCOVERY ReportType_RogueType = 0
	//*
	// @description Rogue type possible value
	// @since 3.5
	ReportType_UPDATE ReportType_RogueType = 1
	//*
	// @description Rogue type possible value
	// @since 3.5
	ReportType_DISAPPEAR ReportType_RogueType = 2
)

var ReportType_RogueType_name = map[int32]string{
	0: "DISCOVERY",
	1: "UPDATE",
	2: "DISAPPEAR",
}

var ReportType_RogueType_value = map[string]int32{
	"DISCOVERY": 0,
	"UPDATE":    1,
	"DISAPPEAR": 2,
}

func (x ReportType_RogueType) Enum() *ReportType_RogueType {
	p := new(ReportType_RogueType)
	*p = x
	return p
}

func (x ReportType_RogueType) String() string {
	return proto.EnumName(ReportType_RogueType_name, int32(x))
}

func (x *ReportType_RogueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReportType_RogueType_value, data, "ReportType_RogueType")
	if err != nil {
		return err
	}
	*x = ReportType_RogueType(value)
	return nil
}

func (ReportType_RogueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8422d846085e8dda, []int{0, 0}
}

type ReportType struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Mac address of rogue AP.
	// @since 3.5
	RogueMac *string `protobuf:"bytes,1,opt,name=rogueMac" json:"rogueMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description peer node rssi value
	// @since 3.5
	Rssi *uint32 `protobuf:"varint,2,opt,name=rssi" json:"rssi,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description is encryption or not (encrypted or open)
	// @since 3.5
	Encryption *string `protobuf:"bytes,3,opt,name=encryption" json:"encryption,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description peer node radio type
	// @since 3.5
	Radio *string `protobuf:"bytes,4,opt,name=radio" json:"radio,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description peer node channel used
	// @since 3.5
	Channel *uint32 `protobuf:"varint,5,opt,name=channel" json:"channel,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description last detected time for this peer node
	// @since 3.5
	TimeStamp *uint64 `protobuf:"varint,6,opt,name=timeStamp" json:"timeStamp,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description peer node ssid
	// @since 3.5
	Ssid *string `protobuf:"bytes,7,opt,name=ssid" json:"ssid,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description peer node wlanId
	// @since 3.5
	WlanId *int32 `protobuf:"varint,8,opt,name=wlanId" json:"wlanId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description peer node mac address
	// @since 3.5
	RogueAPMac *string `protobuf:"bytes,9,opt,name=rogueAPMac" json:"rogueAPMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description is event send out for this peer node
	// @since 3.5
	IsSendEvent *int32 `protobuf:"varint,10,opt,name=isSendEvent" json:"isSendEvent,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description current rouge type for this peer node
	// @since 3.5
	Type *string `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description previous channel is used by peer node
	// @since 3.5
	PrevReportChannel *uint32 `protobuf:"varint,12,opt,name=prevReportChannel" json:"prevReportChannel,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description previous rogue type for this peer node
	// @since 3.5
	PrevReportType *string `protobuf:"bytes,13,opt,name=prevReportType" json:"prevReportType,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description this peer node rogue type status(discover, update, disappear)
	// @since 3.5
	RogueType *ReportType_RogueType `protobuf:"varint,14,opt,name=rogueType,enum=proto.ReportType_RogueType" json:"rogueType,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description current rouge type for this peer node
	// @since 3.5
	RogueTypeInfo        *uint32  `protobuf:"varint,15,opt,name=rogueTypeInfo" json:"rogueTypeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportType) Reset()         { *m = ReportType{} }
func (m *ReportType) String() string { return proto.CompactTextString(m) }
func (*ReportType) ProtoMessage()    {}
func (*ReportType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8422d846085e8dda, []int{0}
}
func (m *ReportType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReportType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReportType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReportType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportType.Merge(m, src)
}
func (m *ReportType) XXX_Size() int {
	return m.Size()
}
func (m *ReportType) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportType.DiscardUnknown(m)
}

var xxx_messageInfo_ReportType proto.InternalMessageInfo

func (m *ReportType) GetRogueMac() string {
	if m != nil && m.RogueMac != nil {
		return *m.RogueMac
	}
	return ""
}

func (m *ReportType) GetRssi() uint32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *ReportType) GetEncryption() string {
	if m != nil && m.Encryption != nil {
		return *m.Encryption
	}
	return ""
}

func (m *ReportType) GetRadio() string {
	if m != nil && m.Radio != nil {
		return *m.Radio
	}
	return ""
}

func (m *ReportType) GetChannel() uint32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

func (m *ReportType) GetTimeStamp() uint64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *ReportType) GetSsid() string {
	if m != nil && m.Ssid != nil {
		return *m.Ssid
	}
	return ""
}

func (m *ReportType) GetWlanId() int32 {
	if m != nil && m.WlanId != nil {
		return *m.WlanId
	}
	return 0
}

func (m *ReportType) GetRogueAPMac() string {
	if m != nil && m.RogueAPMac != nil {
		return *m.RogueAPMac
	}
	return ""
}

func (m *ReportType) GetIsSendEvent() int32 {
	if m != nil && m.IsSendEvent != nil {
		return *m.IsSendEvent
	}
	return 0
}

func (m *ReportType) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ReportType) GetPrevReportChannel() uint32 {
	if m != nil && m.PrevReportChannel != nil {
		return *m.PrevReportChannel
	}
	return 0
}

func (m *ReportType) GetPrevReportType() string {
	if m != nil && m.PrevReportType != nil {
		return *m.PrevReportType
	}
	return ""
}

func (m *ReportType) GetRogueType() ReportType_RogueType {
	if m != nil && m.RogueType != nil {
		return *m.RogueType
	}
	return ReportType_DISCOVERY
}

func (m *ReportType) GetRogueTypeInfo() uint32 {
	if m != nil && m.RogueTypeInfo != nil {
		return *m.RogueTypeInfo
	}
	return 0
}

type RogueAPStats struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description version number for this stats report
	// @since 3.5
	Version *uint32 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description ap mac address
	// @since 3.5
	ApMac *string `protobuf:"bytes,2,opt,name=apMac" json:"apMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description ap name
	// @since 3.5
	ApName *string `protobuf:"bytes,3,opt,name=apName" json:"apName,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description zone UUID
	// @since 3.5
	ZoneId *string `protobuf:"bytes,4,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description is malicious protected or not
	// @since 3.5
	Protect *string `protobuf:"bytes,5,opt,name=protect" json:"protect,omitempty"`
	//*
	// @property Serialization
	// @aggregation NULL
	// @description Serialization data for all of rouge entry
	// @since 3.5
	ApRogueUpdate []*ReportType `protobuf:"bytes,6,rep,name=apRogueUpdate" json:"apRogueUpdate,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP group UUID
	// @since 3.5
	ApgroupId *string `protobuf:"bytes,7,opt,name=apgroup_id,json=apgroupId" json:"apgroup_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Cluster UUID
	// @since 3.5
	ClusterId *string `protobuf:"bytes,8,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain UUID
	// @since 3.5
	DomainId *string `protobuf:"bytes,9,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP tenant UUID
	// @since 3.5
	AptenantId *string `protobuf:"bytes,10,opt,name=aptenant_id,json=aptenantId" json:"aptenant_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description MAP uuid
	// @since 3.5
	MapId *string `protobuf:"bytes,11,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP tenant name
	// @since 3.5
	AptenantName *string `protobuf:"bytes,12,opt,name=aptenant_name,json=aptenantName" json:"aptenant_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone name
	// @since 3.5
	ZoneName *string `protobuf:"bytes,13,opt,name=zone_name,json=zoneName" json:"zone_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP group name
	// @since 3.5
	ApgroupName *string `protobuf:"bytes,14,opt,name=apgroup_name,json=apgroupName" json:"apgroup_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain name
	// @since 3.5
	DomainName *string `protobuf:"bytes,15,opt,name=domain_name,json=domainName" json:"domain_name,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description An indication to flush all rouge stats when first report
	// @since 3.5
	ControllerShouldFlush *int32 `protobuf:"varint,16,opt,name=controllerShouldFlush" json:"controllerShouldFlush,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Timestamp for generating this stats report
	// @since 3.5
	SampleTime *uint64 `protobuf:"varint,17,opt,name=sampleTime" json:"sampleTime,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Interval time for aggregating data
	// @since 3.5
	AggregationInterval *uint32 `protobuf:"varint,18,opt,name=aggregationInterval" json:"aggregationInterval,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Timestamp for generating this stats report
	// @since 3.5
	Timestamp *uint64 `protobuf:"varint,19,opt,name=timestamp" json:"timestamp,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description 1: new rogue ap report, 2: full rogue ap listing report, 3: new rogue client report, 4: full rogue client listing report
	// @since 5.1
	OperationType        *uint32  `protobuf:"varint,20,opt,name=operation_type,json=operationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RogueAPStats) Reset()         { *m = RogueAPStats{} }
func (m *RogueAPStats) String() string { return proto.CompactTextString(m) }
func (*RogueAPStats) ProtoMessage()    {}
func (*RogueAPStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_8422d846085e8dda, []int{1}
}
func (m *RogueAPStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RogueAPStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RogueAPStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RogueAPStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RogueAPStats.Merge(m, src)
}
func (m *RogueAPStats) XXX_Size() int {
	return m.Size()
}
func (m *RogueAPStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RogueAPStats.DiscardUnknown(m)
}

var xxx_messageInfo_RogueAPStats proto.InternalMessageInfo

func (m *RogueAPStats) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *RogueAPStats) GetApMac() string {
	if m != nil && m.ApMac != nil {
		return *m.ApMac
	}
	return ""
}

func (m *RogueAPStats) GetApName() string {
	if m != nil && m.ApName != nil {
		return *m.ApName
	}
	return ""
}

func (m *RogueAPStats) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *RogueAPStats) GetProtect() string {
	if m != nil && m.Protect != nil {
		return *m.Protect
	}
	return ""
}

func (m *RogueAPStats) GetApRogueUpdate() []*ReportType {
	if m != nil {
		return m.ApRogueUpdate
	}
	return nil
}

func (m *RogueAPStats) GetApgroupId() string {
	if m != nil && m.ApgroupId != nil {
		return *m.ApgroupId
	}
	return ""
}

func (m *RogueAPStats) GetClusterId() string {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return ""
}

func (m *RogueAPStats) GetDomainId() string {
	if m != nil && m.DomainId != nil {
		return *m.DomainId
	}
	return ""
}

func (m *RogueAPStats) GetAptenantId() string {
	if m != nil && m.AptenantId != nil {
		return *m.AptenantId
	}
	return ""
}

func (m *RogueAPStats) GetMapId() string {
	if m != nil && m.MapId != nil {
		return *m.MapId
	}
	return ""
}

func (m *RogueAPStats) GetAptenantName() string {
	if m != nil && m.AptenantName != nil {
		return *m.AptenantName
	}
	return ""
}

func (m *RogueAPStats) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *RogueAPStats) GetApgroupName() string {
	if m != nil && m.ApgroupName != nil {
		return *m.ApgroupName
	}
	return ""
}

func (m *RogueAPStats) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *RogueAPStats) GetControllerShouldFlush() int32 {
	if m != nil && m.ControllerShouldFlush != nil {
		return *m.ControllerShouldFlush
	}
	return 0
}

func (m *RogueAPStats) GetSampleTime() uint64 {
	if m != nil && m.SampleTime != nil {
		return *m.SampleTime
	}
	return 0
}

func (m *RogueAPStats) GetAggregationInterval() uint32 {
	if m != nil && m.AggregationInterval != nil {
		return *m.AggregationInterval
	}
	return 0
}

func (m *RogueAPStats) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *RogueAPStats) GetOperationType() uint32 {
	if m != nil && m.OperationType != nil {
		return *m.OperationType
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.ReportType_RogueType", ReportType_RogueType_name, ReportType_RogueType_value)
	proto.RegisterType((*ReportType)(nil), "proto.ReportType")
	proto.RegisterType((*RogueAPStats)(nil), "proto.RogueAPStats")
}

func init() { proto.RegisterFile("ap_rogue.proto", fileDescriptor_8422d846085e8dda) }

var fileDescriptor_8422d846085e8dda = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdb, 0x6e, 0x13, 0x3b,
	0x14, 0xed, 0xa4, 0x49, 0x9a, 0xd9, 0xb9, 0x34, 0x75, 0xdb, 0x73, 0xac, 0xd3, 0x43, 0x3a, 0x94,
	0x8b, 0xf2, 0x80, 0x22, 0xa8, 0x40, 0x88, 0xc7, 0xd0, 0x06, 0x69, 0x1e, 0x80, 0x68, 0xd2, 0x22,
	0xf1, 0x14, 0x99, 0x19, 0x37, 0x1d, 0x31, 0x17, 0xcb, 0xf6, 0xa4, 0x2a, 0x5f, 0x82, 0xf8, 0x02,
	0x3e, 0x85, 0x47, 0x3e, 0x01, 0x95, 0x1f, 0x41, 0xde, 0x9e, 0x24, 0x2d, 0xed, 0x53, 0x66, 0xaf,
	0xb5, 0x6c, 0xef, 0xcb, 0xda, 0x81, 0x0e, 0x13, 0x53, 0x99, 0xcf, 0x0a, 0x3e, 0x10, 0x32, 0xd7,
	0x39, 0xa9, 0xe1, 0xcf, 0xc1, 0xb7, 0x2a, 0x40, 0xc0, 0x45, 0x2e, 0xf5, 0xc9, 0xa5, 0xe0, 0xe4,
	0x3f, 0x68, 0xa0, 0xe8, 0x2d, 0x0b, 0xa9, 0xe3, 0x39, 0x7d, 0x37, 0x58, 0xc6, 0x84, 0x40, 0x55,
	0x2a, 0x15, 0xd3, 0x8a, 0xe7, 0xf4, 0xdb, 0x01, 0x7e, 0x93, 0x1e, 0x00, 0xcf, 0x42, 0x79, 0x29,
	0x74, 0x9c, 0x67, 0x74, 0x1d, 0x4f, 0x5c, 0x43, 0xc8, 0x0e, 0xd4, 0x24, 0x8b, 0xe2, 0x9c, 0x56,
	0x91, 0xb2, 0x01, 0xa1, 0xb0, 0x11, 0x9e, 0xb3, 0x2c, 0xe3, 0x09, 0xad, 0xe1, 0x65, 0x8b, 0x90,
	0xfc, 0x0f, 0xae, 0x8e, 0x53, 0x3e, 0xd1, 0x2c, 0x15, 0xb4, 0xee, 0x39, 0xfd, 0x6a, 0xb0, 0x02,
	0x4c, 0x06, 0x4a, 0xc5, 0x11, 0xdd, 0xc0, 0xcb, 0xf0, 0x9b, 0xfc, 0x03, 0xf5, 0x8b, 0x84, 0x65,
	0x7e, 0x44, 0x1b, 0x9e, 0xd3, 0xaf, 0x05, 0x65, 0x64, 0x32, 0xc3, 0xcc, 0x87, 0x63, 0x53, 0x8b,
	0x6b, 0x33, 0x5b, 0x21, 0xc4, 0x83, 0x66, 0xac, 0x26, 0x3c, 0x8b, 0x46, 0x73, 0x9e, 0x69, 0x0a,
	0x78, 0xf8, 0x3a, 0x64, 0x5e, 0xd3, 0x97, 0x82, 0xd3, 0xa6, 0x7d, 0xcd, 0x7c, 0x93, 0x27, 0xb0,
	0x25, 0x24, 0x9f, 0xdb, 0x8e, 0x1d, 0x95, 0x35, 0xb4, 0xb0, 0x86, 0xdb, 0x04, 0x79, 0x0c, 0x9d,
	0x15, 0x68, 0xfa, 0x4b, 0xdb, 0x78, 0xd7, 0x5f, 0x28, 0x79, 0x05, 0x2e, 0x66, 0x86, 0x92, 0x8e,
	0xe7, 0xf4, 0x3b, 0x87, 0x7b, 0x76, 0x4c, 0x83, 0x95, 0x6a, 0x10, 0x2c, 0x24, 0xc1, 0x4a, 0x4d,
	0x1e, 0x42, 0x7b, 0x19, 0xf8, 0xd9, 0x59, 0x4e, 0x37, 0x31, 0x99, 0x9b, 0xe0, 0xc1, 0x0b, 0x70,
	0x97, 0xa7, 0x49, 0x1b, 0xdc, 0x63, 0x7f, 0x72, 0xf4, 0xfe, 0xc3, 0x28, 0xf8, 0xd8, 0x5d, 0x23,
	0x00, 0xf5, 0xd3, 0xf1, 0xf1, 0xf0, 0x64, 0xd4, 0x75, 0x4a, 0x6a, 0x38, 0x1e, 0x8f, 0x86, 0x41,
	0xb7, 0x72, 0xf0, 0xbd, 0x06, 0xad, 0xc0, 0xb6, 0x6c, 0xa2, 0x99, 0x56, 0x66, 0x70, 0x73, 0x2e,
	0x95, 0x99, 0xb5, 0xe3, 0x55, 0xcc, 0xe0, 0xca, 0xd0, 0x0c, 0x9a, 0x09, 0xd3, 0xe9, 0x8a, 0x1d,
	0x34, 0x06, 0x66, 0x38, 0x4c, 0xbc, 0x63, 0x29, 0x2f, 0xad, 0x51, 0x46, 0xe4, 0x5f, 0xd8, 0xf8,
	0x92, 0x67, 0x7c, 0x1a, 0x47, 0xa5, 0x31, 0xea, 0x26, 0xf4, 0x23, 0xf3, 0x80, 0xa9, 0x9b, 0x87,
	0x1a, 0x9d, 0xe1, 0x06, 0x8b, 0x90, 0xbc, 0x84, 0x36, 0x13, 0x98, 0xcc, 0xa9, 0x88, 0x98, 0xe6,
	0xb4, 0xee, 0xad, 0xf7, 0x9b, 0x87, 0x5b, 0xb7, 0xfa, 0x14, 0xdc, 0xd4, 0x91, 0x7b, 0x00, 0x4c,
	0xcc, 0x64, 0x5e, 0x88, 0xe9, 0xd2, 0x3a, 0x6e, 0x89, 0xf8, 0x91, 0xa1, 0xc3, 0xa4, 0x50, 0x9a,
	0x4b, 0x43, 0x37, 0x2c, 0x5d, 0x22, 0x7e, 0x44, 0xf6, 0xc0, 0x8d, 0xf2, 0x94, 0xc5, 0x99, 0x61,
	0xad, 0x8b, 0x1a, 0x16, 0xf0, 0x23, 0xb2, 0x0f, 0x4d, 0x26, 0x34, 0xcf, 0x58, 0xa6, 0x0d, 0x0d,
	0xd6, 0x64, 0x0b, 0xc8, 0x8f, 0xc8, 0x2e, 0xd4, 0x53, 0x86, 0xef, 0x5a, 0x13, 0xd5, 0x52, 0x66,
	0xde, 0x7c, 0x60, 0x6a, 0x29, 0xcf, 0x65, 0xa6, 0x3b, 0x2d, 0x64, 0x5b, 0x0b, 0x10, 0x7b, 0xb4,
	0x07, 0x2e, 0xf6, 0x08, 0x05, 0xd6, 0x37, 0x0d, 0x03, 0x20, 0x79, 0x1f, 0x5a, 0x8b, 0xa2, 0x90,
	0xef, 0x20, 0xdf, 0x2c, 0x31, 0x94, 0xec, 0x43, 0xb3, 0xcc, 0x1c, 0x15, 0x9b, 0x36, 0x39, 0x0b,
	0xa1, 0xe0, 0x39, 0xec, 0x86, 0x79, 0xa6, 0x65, 0x9e, 0x24, 0x5c, 0x4e, 0xce, 0xf3, 0x22, 0x89,
	0xde, 0x24, 0x85, 0x3a, 0xa7, 0x5d, 0xdc, 0x85, 0xbb, 0x49, 0xb3, 0x57, 0x8a, 0xa5, 0x22, 0xe1,
	0x27, 0x71, 0xca, 0xe9, 0x16, 0xae, 0xe8, 0x35, 0x84, 0x3c, 0x85, 0x6d, 0x36, 0x9b, 0x49, 0x3e,
	0x63, 0xe6, 0x0f, 0xc0, 0xcf, 0x34, 0x97, 0x73, 0x96, 0x50, 0x82, 0xb6, 0xbc, 0x8b, 0x5a, 0xec,
	0xbc, 0xc2, 0x9d, 0xdf, 0x5e, 0xed, 0x3c, 0x02, 0xe4, 0x11, 0x74, 0x72, 0xc1, 0x25, 0x1e, 0x99,
	0xe2, 0x3e, 0xee, 0x58, 0x87, 0x2f, 0x51, 0x33, 0xf4, 0xd7, 0xcf, 0x7e, 0x5c, 0xf5, 0x9c, 0x9f,
	0x57, 0x3d, 0xe7, 0xd7, 0x55, 0xcf, 0xf9, 0xfa, 0xbb, 0xb7, 0x06, 0xfb, 0x61, 0x9e, 0x0e, 0x64,
	0x11, 0x7e, 0x2e, 0xd4, 0x45, 0x2c, 0x79, 0xc2, 0x95, 0x1a, 0xa8, 0x70, 0x66, 0xfd, 0xf2, 0xa9,
	0x38, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xae, 0x5e, 0x63, 0xe0, 0x12, 0x05, 0x00, 0x00,
}

func (m *ReportType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReportType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReportType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.RogueTypeInfo != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.RogueTypeInfo))
		i--
		dAtA[i] = 0x78
	}
	if m.RogueType != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.RogueType))
		i--
		dAtA[i] = 0x70
	}
	if m.PrevReportType != nil {
		i -= len(*m.PrevReportType)
		copy(dAtA[i:], *m.PrevReportType)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.PrevReportType)))
		i--
		dAtA[i] = 0x6a
	}
	if m.PrevReportChannel != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.PrevReportChannel))
		i--
		dAtA[i] = 0x60
	}
	if m.Type != nil {
		i -= len(*m.Type)
		copy(dAtA[i:], *m.Type)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.Type)))
		i--
		dAtA[i] = 0x5a
	}
	if m.IsSendEvent != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.IsSendEvent))
		i--
		dAtA[i] = 0x50
	}
	if m.RogueAPMac != nil {
		i -= len(*m.RogueAPMac)
		copy(dAtA[i:], *m.RogueAPMac)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.RogueAPMac)))
		i--
		dAtA[i] = 0x4a
	}
	if m.WlanId != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.WlanId))
		i--
		dAtA[i] = 0x40
	}
	if m.Ssid != nil {
		i -= len(*m.Ssid)
		copy(dAtA[i:], *m.Ssid)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.Ssid)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TimeStamp != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.TimeStamp))
		i--
		dAtA[i] = 0x30
	}
	if m.Channel != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.Channel))
		i--
		dAtA[i] = 0x28
	}
	if m.Radio != nil {
		i -= len(*m.Radio)
		copy(dAtA[i:], *m.Radio)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.Radio)))
		i--
		dAtA[i] = 0x22
	}
	if m.Encryption != nil {
		i -= len(*m.Encryption)
		copy(dAtA[i:], *m.Encryption)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.Encryption)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Rssi != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.Rssi))
		i--
		dAtA[i] = 0x10
	}
	if m.RogueMac != nil {
		i -= len(*m.RogueMac)
		copy(dAtA[i:], *m.RogueMac)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.RogueMac)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RogueAPStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RogueAPStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RogueAPStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.OperationType != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.OperationType))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.Timestamp != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.AggregationInterval != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.AggregationInterval))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.SampleTime != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.SampleTime))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.ControllerShouldFlush != nil {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.ControllerShouldFlush))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.DomainName != nil {
		i -= len(*m.DomainName)
		copy(dAtA[i:], *m.DomainName)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.DomainName)))
		i--
		dAtA[i] = 0x7a
	}
	if m.ApgroupName != nil {
		i -= len(*m.ApgroupName)
		copy(dAtA[i:], *m.ApgroupName)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.ApgroupName)))
		i--
		dAtA[i] = 0x72
	}
	if m.ZoneName != nil {
		i -= len(*m.ZoneName)
		copy(dAtA[i:], *m.ZoneName)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.ZoneName)))
		i--
		dAtA[i] = 0x6a
	}
	if m.AptenantName != nil {
		i -= len(*m.AptenantName)
		copy(dAtA[i:], *m.AptenantName)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.AptenantName)))
		i--
		dAtA[i] = 0x62
	}
	if m.MapId != nil {
		i -= len(*m.MapId)
		copy(dAtA[i:], *m.MapId)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.MapId)))
		i--
		dAtA[i] = 0x5a
	}
	if m.AptenantId != nil {
		i -= len(*m.AptenantId)
		copy(dAtA[i:], *m.AptenantId)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.AptenantId)))
		i--
		dAtA[i] = 0x52
	}
	if m.DomainId != nil {
		i -= len(*m.DomainId)
		copy(dAtA[i:], *m.DomainId)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.DomainId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ClusterId != nil {
		i -= len(*m.ClusterId)
		copy(dAtA[i:], *m.ClusterId)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.ClusterId)))
		i--
		dAtA[i] = 0x42
	}
	if m.ApgroupId != nil {
		i -= len(*m.ApgroupId)
		copy(dAtA[i:], *m.ApgroupId)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.ApgroupId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ApRogueUpdate) > 0 {
		for iNdEx := len(m.ApRogueUpdate) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApRogueUpdate[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApRogue(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Protect != nil {
		i -= len(*m.Protect)
		copy(dAtA[i:], *m.Protect)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.Protect)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ZoneId != nil {
		i -= len(*m.ZoneId)
		copy(dAtA[i:], *m.ZoneId)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.ZoneId)))
		i--
		dAtA[i] = 0x22
	}
	if m.ApName != nil {
		i -= len(*m.ApName)
		copy(dAtA[i:], *m.ApName)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.ApName)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ApMac != nil {
		i -= len(*m.ApMac)
		copy(dAtA[i:], *m.ApMac)
		i = encodeVarintApRogue(dAtA, i, uint64(len(*m.ApMac)))
		i--
		dAtA[i] = 0x12
	}
	if m.Version == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintApRogue(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApRogue(dAtA []byte, offset int, v uint64) int {
	offset -= sovApRogue(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReportType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RogueMac != nil {
		l = len(*m.RogueMac)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.Rssi != nil {
		n += 1 + sovApRogue(uint64(*m.Rssi))
	}
	if m.Encryption != nil {
		l = len(*m.Encryption)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.Radio != nil {
		l = len(*m.Radio)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.Channel != nil {
		n += 1 + sovApRogue(uint64(*m.Channel))
	}
	if m.TimeStamp != nil {
		n += 1 + sovApRogue(uint64(*m.TimeStamp))
	}
	if m.Ssid != nil {
		l = len(*m.Ssid)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.WlanId != nil {
		n += 1 + sovApRogue(uint64(*m.WlanId))
	}
	if m.RogueAPMac != nil {
		l = len(*m.RogueAPMac)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.IsSendEvent != nil {
		n += 1 + sovApRogue(uint64(*m.IsSendEvent))
	}
	if m.Type != nil {
		l = len(*m.Type)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.PrevReportChannel != nil {
		n += 1 + sovApRogue(uint64(*m.PrevReportChannel))
	}
	if m.PrevReportType != nil {
		l = len(*m.PrevReportType)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.RogueType != nil {
		n += 1 + sovApRogue(uint64(*m.RogueType))
	}
	if m.RogueTypeInfo != nil {
		n += 1 + sovApRogue(uint64(*m.RogueTypeInfo))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RogueAPStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		n += 1 + sovApRogue(uint64(*m.Version))
	}
	if m.ApMac != nil {
		l = len(*m.ApMac)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.ApName != nil {
		l = len(*m.ApName)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.ZoneId != nil {
		l = len(*m.ZoneId)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.Protect != nil {
		l = len(*m.Protect)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if len(m.ApRogueUpdate) > 0 {
		for _, e := range m.ApRogueUpdate {
			l = e.Size()
			n += 1 + l + sovApRogue(uint64(l))
		}
	}
	if m.ApgroupId != nil {
		l = len(*m.ApgroupId)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.ClusterId != nil {
		l = len(*m.ClusterId)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.DomainId != nil {
		l = len(*m.DomainId)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.AptenantId != nil {
		l = len(*m.AptenantId)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.MapId != nil {
		l = len(*m.MapId)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.AptenantName != nil {
		l = len(*m.AptenantName)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.ZoneName != nil {
		l = len(*m.ZoneName)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.ApgroupName != nil {
		l = len(*m.ApgroupName)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.DomainName != nil {
		l = len(*m.DomainName)
		n += 1 + l + sovApRogue(uint64(l))
	}
	if m.ControllerShouldFlush != nil {
		n += 2 + sovApRogue(uint64(*m.ControllerShouldFlush))
	}
	if m.SampleTime != nil {
		n += 2 + sovApRogue(uint64(*m.SampleTime))
	}
	if m.AggregationInterval != nil {
		n += 2 + sovApRogue(uint64(*m.AggregationInterval))
	}
	if m.Timestamp != nil {
		n += 2 + sovApRogue(uint64(*m.Timestamp))
	}
	if m.OperationType != nil {
		n += 2 + sovApRogue(uint64(*m.OperationType))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApRogue(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApRogue(x uint64) (n int) {
	return sovApRogue(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReportType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApRogue
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReportType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReportType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RogueMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RogueMac = &s
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rssi", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Rssi = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encryption", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Encryption = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Radio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Radio = &s
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Channel = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeStamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimeStamp = &v
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ssid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Ssid = &s
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlanId", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WlanId = &v
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RogueAPMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RogueAPMac = &s
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSendEvent", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSendEvent = &v
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Type = &s
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevReportChannel", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PrevReportChannel = &v
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevReportType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.PrevReportType = &s
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RogueType", wireType)
			}
			var v ReportType_RogueType
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= ReportType_RogueType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RogueType = &v
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RogueTypeInfo", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RogueTypeInfo = &v
		default:
			iNdEx = preIndex
			skippy, err := skipApRogue(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApRogue
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApRogue
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RogueAPStats) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApRogue
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RogueAPStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RogueAPStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApMac = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApName = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneId = &s
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protect", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Protect = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApRogueUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApRogueUpdate = append(m.ApRogueUpdate, &ReportType{})
			if err := m.ApRogueUpdate[len(m.ApRogueUpdate)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApgroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApgroupId = &s
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClusterId = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainId = &s
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AptenantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AptenantId = &s
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MapId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MapId = &s
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AptenantName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AptenantName = &s
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneName = &s
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApgroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApgroupName = &s
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApRogue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApRogue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainName = &s
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerShouldFlush", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ControllerShouldFlush = &v
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleTime", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SampleTime = &v
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationInterval", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AggregationInterval = &v
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationType", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OperationType = &v
		default:
			iNdEx = preIndex
			skippy, err := skipApRogue(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApRogue
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApRogue
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApRogue(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApRogue
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApRogue
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApRogue
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApRogue
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApRogue
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApRogue        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApRogue          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApRogue = fmt.Errorf("proto: unexpected end of group")
)
