// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ap_wired_client.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type APWiredClientInfo_AUTH_STATUS int32

const (
	//*
	// @description authStatus possible value
	// @since 3.5.1
	APWiredClientInfo_UNAUTH APWiredClientInfo_AUTH_STATUS = 0
	//*
	// @description authStatus possible value
	// @since 3.5.1
	APWiredClientInfo_AUTHENTICATED APWiredClientInfo_AUTH_STATUS = 1
)

var APWiredClientInfo_AUTH_STATUS_name = map[int32]string{
	0: "UNAUTH",
	1: "AUTHENTICATED",
}

var APWiredClientInfo_AUTH_STATUS_value = map[string]int32{
	"UNAUTH":        0,
	"AUTHENTICATED": 1,
}

func (x APWiredClientInfo_AUTH_STATUS) Enum() *APWiredClientInfo_AUTH_STATUS {
	p := new(APWiredClientInfo_AUTH_STATUS)
	*p = x
	return p
}

func (x APWiredClientInfo_AUTH_STATUS) String() string {
	return proto.EnumName(APWiredClientInfo_AUTH_STATUS_name, int32(x))
}

func (x *APWiredClientInfo_AUTH_STATUS) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(APWiredClientInfo_AUTH_STATUS_value, data, "APWiredClientInfo_AUTH_STATUS")
	if err != nil {
		return err
	}
	*x = APWiredClientInfo_AUTH_STATUS(value)
	return nil
}

func (APWiredClientInfo_AUTH_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d868ebf0a0ace347, []int{0, 0}
}

type APWiredClientInfo struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Wired Client MAC address
	// @since 3.5.1
	ClientMac *string `protobuf:"bytes,1,opt,name=clientMac" json:"clientMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Wired Client IPv4 address
	// @since 3.5.1
	IpAddress *string `protobuf:"bytes,2,opt,name=ipAddress" json:"ipAddress,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Wired Client IPv6 address
	// @since 3.5.1
	Ipv6Address *string `protobuf:"bytes,3,opt,name=ipv6Address" json:"ipv6Address,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Wired Client VLAN
	// @since 3.5.1
	Vlan *int32 `protobuf:"varint,4,opt,name=vlan" json:"vlan,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Receive packet frames
	// @since 3.5.1
	RxFrames *uint64 `protobuf:"varint,5,opt,name=rxFrames" json:"rxFrames,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Receive packet bytes
	// @since 3.5.1
	RxBytes *uint64 `protobuf:"varint,6,opt,name=rxBytes" json:"rxBytes,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Receive unicast packets
	// @since 3.5.1
	RxUcast *uint64 `protobuf:"varint,7,opt,name=rxUcast" json:"rxUcast,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Receive multicast packets
	// @since 3.5.1
	RxMcast *uint64 `protobuf:"varint,8,opt,name=rxMcast" json:"rxMcast,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Receive Broadcast packets
	// @since 3.5.1
	RxBcast *uint64 `protobuf:"varint,9,opt,name=rxBcast" json:"rxBcast,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Drop packets on receive side
	// @since 3.5.1
	RxDrop *uint64 `protobuf:"varint,10,opt,name=rxDrop" json:"rxDrop,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Receive EAPOL packets
	// @since 3.5.1
	RxEapol *uint64 `protobuf:"varint,11,opt,name=rxEapol" json:"rxEapol,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Receive legacy multicast packets
	// @since 3.5.1
	RxMcastLegacy *uint64 `protobuf:"varint,12,opt,name=rxMcastLegacy" json:"rxMcastLegacy,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Transmit packet frames
	// @since 3.5.1
	TxFrames *uint64 `protobuf:"varint,13,opt,name=txFrames" json:"txFrames,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Transmit packet bytes
	// @since 3.5.1
	TxBytes *uint64 `protobuf:"varint,14,opt,name=txBytes" json:"txBytes,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Transmit unicast packets
	// @since 3.5.1
	TxUcast *uint64 `protobuf:"varint,15,opt,name=txUcast" json:"txUcast,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Transmit multicast packets
	// @since 3.5.1
	TxMcast *uint64 `protobuf:"varint,16,opt,name=txMcast" json:"txMcast,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Transmit Broadcast packets
	// @since 3.5.1
	TxBcast *uint64 `protobuf:"varint,17,opt,name=txBcast" json:"txBcast,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Transmit Drop packets
	// @since 3.5.1
	TxDrop *uint64 `protobuf:"varint,18,opt,name=txDrop" json:"txDrop,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Transmit EAPOL packets
	// @since 3.5.1
	TxEapol *uint64 `protobuf:"varint,19,opt,name=txEapol" json:"txEapol,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Wired client authentication status(UNAUTH or AUTHENTICATED)
	// @since 3.5.1
	AuthStatus *APWiredClientInfo_AUTH_STATUS `protobuf:"varint,20,opt,name=authStatus,enum=proto.APWiredClientInfo_AUTH_STATUS" json:"authStatus,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description interface name which wired client associated
	// @since 3.5.1
	EthIF                *string  `protobuf:"bytes,21,opt,name=ethIF" json:"ethIF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APWiredClientInfo) Reset()         { *m = APWiredClientInfo{} }
func (m *APWiredClientInfo) String() string { return proto.CompactTextString(m) }
func (*APWiredClientInfo) ProtoMessage()    {}
func (*APWiredClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d868ebf0a0ace347, []int{0}
}
func (m *APWiredClientInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *APWiredClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_APWiredClientInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *APWiredClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APWiredClientInfo.Merge(m, src)
}
func (m *APWiredClientInfo) XXX_Size() int {
	return m.Size()
}
func (m *APWiredClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_APWiredClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_APWiredClientInfo proto.InternalMessageInfo

func (m *APWiredClientInfo) GetClientMac() string {
	if m != nil && m.ClientMac != nil {
		return *m.ClientMac
	}
	return ""
}

func (m *APWiredClientInfo) GetIpAddress() string {
	if m != nil && m.IpAddress != nil {
		return *m.IpAddress
	}
	return ""
}

func (m *APWiredClientInfo) GetIpv6Address() string {
	if m != nil && m.Ipv6Address != nil {
		return *m.Ipv6Address
	}
	return ""
}

func (m *APWiredClientInfo) GetVlan() int32 {
	if m != nil && m.Vlan != nil {
		return *m.Vlan
	}
	return 0
}

func (m *APWiredClientInfo) GetRxFrames() uint64 {
	if m != nil && m.RxFrames != nil {
		return *m.RxFrames
	}
	return 0
}

func (m *APWiredClientInfo) GetRxBytes() uint64 {
	if m != nil && m.RxBytes != nil {
		return *m.RxBytes
	}
	return 0
}

func (m *APWiredClientInfo) GetRxUcast() uint64 {
	if m != nil && m.RxUcast != nil {
		return *m.RxUcast
	}
	return 0
}

func (m *APWiredClientInfo) GetRxMcast() uint64 {
	if m != nil && m.RxMcast != nil {
		return *m.RxMcast
	}
	return 0
}

func (m *APWiredClientInfo) GetRxBcast() uint64 {
	if m != nil && m.RxBcast != nil {
		return *m.RxBcast
	}
	return 0
}

func (m *APWiredClientInfo) GetRxDrop() uint64 {
	if m != nil && m.RxDrop != nil {
		return *m.RxDrop
	}
	return 0
}

func (m *APWiredClientInfo) GetRxEapol() uint64 {
	if m != nil && m.RxEapol != nil {
		return *m.RxEapol
	}
	return 0
}

func (m *APWiredClientInfo) GetRxMcastLegacy() uint64 {
	if m != nil && m.RxMcastLegacy != nil {
		return *m.RxMcastLegacy
	}
	return 0
}

func (m *APWiredClientInfo) GetTxFrames() uint64 {
	if m != nil && m.TxFrames != nil {
		return *m.TxFrames
	}
	return 0
}

func (m *APWiredClientInfo) GetTxBytes() uint64 {
	if m != nil && m.TxBytes != nil {
		return *m.TxBytes
	}
	return 0
}

func (m *APWiredClientInfo) GetTxUcast() uint64 {
	if m != nil && m.TxUcast != nil {
		return *m.TxUcast
	}
	return 0
}

func (m *APWiredClientInfo) GetTxMcast() uint64 {
	if m != nil && m.TxMcast != nil {
		return *m.TxMcast
	}
	return 0
}

func (m *APWiredClientInfo) GetTxBcast() uint64 {
	if m != nil && m.TxBcast != nil {
		return *m.TxBcast
	}
	return 0
}

func (m *APWiredClientInfo) GetTxDrop() uint64 {
	if m != nil && m.TxDrop != nil {
		return *m.TxDrop
	}
	return 0
}

func (m *APWiredClientInfo) GetTxEapol() uint64 {
	if m != nil && m.TxEapol != nil {
		return *m.TxEapol
	}
	return 0
}

func (m *APWiredClientInfo) GetAuthStatus() APWiredClientInfo_AUTH_STATUS {
	if m != nil && m.AuthStatus != nil {
		return *m.AuthStatus
	}
	return APWiredClientInfo_UNAUTH
}

func (m *APWiredClientInfo) GetEthIF() string {
	if m != nil && m.EthIF != nil {
		return *m.EthIF
	}
	return ""
}

type APWiredClientStats struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description GPB version
	// @since 3.5.1
	Version *uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	//*
	// @property Serialization
	// @aggregation NULL
	// @description Serialization data for all of wired client information
	// @since 3.5.1
	Clients []*APWiredClientInfo `protobuf:"bytes,2,rep,name=clients" json:"clients,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description time for this report
	// @since 3.5.1
	Timestamp *uint64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description sample time for these stats
	// @since 3.5.1
	SampleTime *uint64 `protobuf:"varint,4,opt,name=sampleTime" json:"sampleTime,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description aggregation interval for report
	// @since 3.5.1
	AggregationInterval *uint32 `protobuf:"varint,5,opt,name=aggregationInterval" json:"aggregationInterval,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description zone UUID
	// @since 3.5.1
	ZoneId *string `protobuf:"bytes,6,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description doamin UUID
	// @since 3.5.1
	DomainId *string `protobuf:"bytes,7,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP device name
	// @since 3.5.1
	DeviceName *string `protobuf:"bytes,8,opt,name=deviceName" json:"deviceName,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description ap group UUID
	// @since 3.5.1
	ApgroupId *string `protobuf:"bytes,9,opt,name=apgroup_id,json=apgroupId" json:"apgroup_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description ap tenant UUID
	// @since 3.5.1
	AptenantId *string `protobuf:"bytes,10,opt,name=aptenant_id,json=aptenantId" json:"aptenant_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description map UUID
	// @since 3.5.1
	MapId *string `protobuf:"bytes,11,opt,name=map_id,json=mapId" json:"map_id,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description cluster UUID
	// @since 3.5.1
	ClusterId            *string  `protobuf:"bytes,12,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APWiredClientStats) Reset()         { *m = APWiredClientStats{} }
func (m *APWiredClientStats) String() string { return proto.CompactTextString(m) }
func (*APWiredClientStats) ProtoMessage()    {}
func (*APWiredClientStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_d868ebf0a0ace347, []int{1}
}
func (m *APWiredClientStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *APWiredClientStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_APWiredClientStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *APWiredClientStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APWiredClientStats.Merge(m, src)
}
func (m *APWiredClientStats) XXX_Size() int {
	return m.Size()
}
func (m *APWiredClientStats) XXX_DiscardUnknown() {
	xxx_messageInfo_APWiredClientStats.DiscardUnknown(m)
}

var xxx_messageInfo_APWiredClientStats proto.InternalMessageInfo

func (m *APWiredClientStats) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *APWiredClientStats) GetClients() []*APWiredClientInfo {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *APWiredClientStats) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *APWiredClientStats) GetSampleTime() uint64 {
	if m != nil && m.SampleTime != nil {
		return *m.SampleTime
	}
	return 0
}

func (m *APWiredClientStats) GetAggregationInterval() uint32 {
	if m != nil && m.AggregationInterval != nil {
		return *m.AggregationInterval
	}
	return 0
}

func (m *APWiredClientStats) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *APWiredClientStats) GetDomainId() string {
	if m != nil && m.DomainId != nil {
		return *m.DomainId
	}
	return ""
}

func (m *APWiredClientStats) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *APWiredClientStats) GetApgroupId() string {
	if m != nil && m.ApgroupId != nil {
		return *m.ApgroupId
	}
	return ""
}

func (m *APWiredClientStats) GetAptenantId() string {
	if m != nil && m.AptenantId != nil {
		return *m.AptenantId
	}
	return ""
}

func (m *APWiredClientStats) GetMapId() string {
	if m != nil && m.MapId != nil {
		return *m.MapId
	}
	return ""
}

func (m *APWiredClientStats) GetClusterId() string {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.APWiredClientInfo_AUTH_STATUS", APWiredClientInfo_AUTH_STATUS_name, APWiredClientInfo_AUTH_STATUS_value)
	proto.RegisterType((*APWiredClientInfo)(nil), "proto.APWiredClientInfo")
	proto.RegisterType((*APWiredClientStats)(nil), "proto.APWiredClientStats")
}

func init() { proto.RegisterFile("ap_wired_client.proto", fileDescriptor_d868ebf0a0ace347) }

var fileDescriptor_d868ebf0a0ace347 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0x6b, 0x9a, 0x9f, 0xfa, 0xa6, 0x29, 0xed, 0xb4, 0x85, 0x11, 0xd0, 0x34, 0xaa, 0xba,
	0xc8, 0x02, 0x45, 0xd0, 0x05, 0xfb, 0xf4, 0x4f, 0x58, 0x22, 0x15, 0x72, 0x13, 0xb1, 0x8c, 0x06,
	0x7b, 0x9a, 0x5a, 0xf8, 0x4f, 0x33, 0xd7, 0xa1, 0xe5, 0x49, 0x58, 0x21, 0xf1, 0x36, 0x2c, 0x79,
	0x04, 0x14, 0x5e, 0x04, 0xcd, 0x8c, 0xc7, 0x71, 0x05, 0xac, 0xe2, 0x7b, 0x3e, 0x9f, 0x1b, 0x9f,
	0xf8, 0x64, 0x60, 0x9f, 0xe5, 0xb3, 0xcf, 0x91, 0xe0, 0xe1, 0x2c, 0x88, 0x23, 0x9e, 0xe2, 0x30,
	0x17, 0x19, 0x66, 0xa4, 0xa9, 0x3f, 0x8e, 0xbe, 0x37, 0x61, 0x67, 0xf4, 0xfe, 0x83, 0xe2, 0x67,
	0x1a, 0x7b, 0xe9, 0x4d, 0x46, 0x5e, 0x80, 0x6b, 0x6e, 0x1e, 0xb3, 0x80, 0x3a, 0x7d, 0x67, 0xe0,
	0xfa, 0x2b, 0x41, 0xd1, 0x28, 0x1f, 0x85, 0xa1, 0xe0, 0x52, 0xd2, 0x47, 0x86, 0x56, 0x02, 0xe9,
	0x43, 0x27, 0xca, 0x17, 0x6f, 0x2c, 0x5f, 0xd7, 0xbc, 0x2e, 0x11, 0x02, 0x8d, 0x45, 0xcc, 0x52,
	0xda, 0xe8, 0x3b, 0x83, 0xa6, 0xaf, 0xaf, 0xc9, 0x33, 0xd8, 0x10, 0x77, 0x97, 0x82, 0x25, 0x5c,
	0xd2, 0x66, 0xdf, 0x19, 0x34, 0xfc, 0x6a, 0x26, 0x14, 0xda, 0xe2, 0xee, 0xf4, 0x1e, 0xb9, 0xa4,
	0x2d, 0x8d, 0xec, 0x68, 0xc8, 0x34, 0x60, 0x12, 0x69, 0xdb, 0x12, 0x3d, 0x1a, 0x32, 0xd6, 0x64,
	0xc3, 0x92, 0xf1, 0x8a, 0x9c, 0x6a, 0xe2, 0x56, 0xdb, 0x34, 0x79, 0x02, 0x2d, 0x71, 0x77, 0x2e,
	0xb2, 0x9c, 0x82, 0x06, 0xe5, 0x64, 0x1c, 0x17, 0x2c, 0xcf, 0x62, 0xda, 0xb1, 0x0e, 0x3d, 0x92,
	0x63, 0xe8, 0x96, 0x6b, 0xdf, 0xf1, 0x39, 0x0b, 0xee, 0xe9, 0xa6, 0xe6, 0x0f, 0x45, 0x95, 0x0d,
	0x6d, 0xb6, 0xae, 0xc9, 0x86, 0xb5, 0x6c, 0x58, 0x66, 0xdb, 0x32, 0xbb, 0x71, 0x95, 0x0d, 0xcb,
	0x6c, 0x8f, 0x2d, 0xa9, 0xb2, 0x61, 0x99, 0x6d, 0xdb, 0x92, 0xf1, 0x8a, 0x98, 0x6c, 0x3b, 0xd5,
	0x36, 0x9b, 0x0d, 0x4d, 0x36, 0x62, 0xb2, 0x61, 0x95, 0x0d, 0xcb, 0x6c, 0xbb, 0xd6, 0x61, 0xb2,
	0x9d, 0x03, 0xb0, 0x02, 0x6f, 0xaf, 0x91, 0x61, 0x21, 0xe9, 0x5e, 0xdf, 0x19, 0x6c, 0x9d, 0x1c,
	0x9b, 0xf2, 0x0c, 0xff, 0x6a, 0xcc, 0x70, 0x34, 0x9d, 0xbc, 0x9d, 0x5d, 0x4f, 0x46, 0x93, 0xe9,
	0xb5, 0x5f, 0xf3, 0x91, 0x3d, 0x68, 0x72, 0xbc, 0xf5, 0x2e, 0xe9, 0xbe, 0xee, 0x81, 0x19, 0x8e,
	0x5e, 0x42, 0xa7, 0x66, 0x20, 0x00, 0xad, 0xe9, 0x95, 0x12, 0xb6, 0xd7, 0xc8, 0x0e, 0x74, 0xd5,
	0xd5, 0xc5, 0xd5, 0xc4, 0x3b, 0x1b, 0x4d, 0x2e, 0xce, 0xb7, 0x9d, 0xa3, 0x6f, 0xeb, 0x40, 0x1e,
	0x7c, 0xa3, 0xda, 0xad, 0x7f, 0xa0, 0x05, 0x17, 0x32, 0xca, 0x52, 0x5d, 0xd1, 0xae, 0x6f, 0x47,
	0x72, 0x02, 0x6d, 0xd3, 0x56, 0x55, 0xcf, 0xf5, 0x41, 0xe7, 0x84, 0xfe, 0xef, 0xb9, 0x7d, 0x7b,
	0xa3, 0x2a, 0x35, 0x46, 0x09, 0x97, 0xc8, 0x92, 0x5c, 0x97, 0xb6, 0xe1, 0xaf, 0x04, 0xd2, 0x03,
	0x90, 0x2c, 0xc9, 0x63, 0x3e, 0x89, 0x12, 0xae, 0x8b, 0xdb, 0xf0, 0x6b, 0x0a, 0x79, 0x05, 0xbb,
	0x6c, 0x3e, 0x17, 0x7c, 0xce, 0x30, 0xca, 0x52, 0x2f, 0x45, 0x2e, 0x16, 0x2c, 0xd6, 0x4d, 0xee,
	0xfa, 0xff, 0x42, 0xe4, 0x29, 0xb4, 0xbf, 0x64, 0x29, 0x9f, 0x45, 0xa1, 0x2e, 0xb5, 0xeb, 0xb7,
	0xd4, 0xe8, 0x85, 0xe4, 0x39, 0xb8, 0x61, 0x96, 0xb0, 0x28, 0x55, 0xa8, 0xad, 0xd1, 0x86, 0x11,
	0xbc, 0x50, 0x3d, 0x47, 0xc8, 0x17, 0x51, 0xc0, 0xaf, 0x58, 0xc2, 0x75, 0xb3, 0x5d, 0xbf, 0xa6,
	0x90, 0x03, 0x00, 0x96, 0xcf, 0x45, 0x56, 0xe4, 0xca, 0xed, 0x9a, 0xff, 0x66, 0xa9, 0x78, 0x21,
	0x39, 0x84, 0x0e, 0xcb, 0x91, 0xa7, 0x2c, 0x45, 0xc5, 0xc1, 0xf8, 0xad, 0xe4, 0x85, 0x64, 0x1f,
	0x5a, 0x09, 0xd3, 0xde, 0x8e, 0x79, 0x5f, 0x09, 0x53, 0xbe, 0x03, 0x80, 0x20, 0x2e, 0x24, 0x72,
	0xa1, 0xd0, 0xa6, 0x3d, 0x10, 0xb4, 0xe2, 0x85, 0xa7, 0xaf, 0x7f, 0x2c, 0x7b, 0xce, 0xcf, 0x65,
	0xcf, 0xf9, 0xb5, 0xec, 0x39, 0x5f, 0x7f, 0xf7, 0xd6, 0xe0, 0x30, 0xc8, 0x92, 0xa1, 0x28, 0x82,
	0x4f, 0x85, 0x54, 0x67, 0x4f, 0xcc, 0xa5, 0x1c, 0xca, 0x60, 0x6e, 0x5e, 0xc3, 0xc7, 0xe2, 0xe6,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xa7, 0x60, 0xc6, 0x96, 0x04, 0x00, 0x00,
}

func (m *APWiredClientInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *APWiredClientInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *APWiredClientInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.EthIF != nil {
		i -= len(*m.EthIF)
		copy(dAtA[i:], *m.EthIF)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.EthIF)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.AuthStatus != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.AuthStatus))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.TxEapol != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.TxEapol))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.TxDrop != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.TxDrop))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.TxBcast != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.TxBcast))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.TxMcast != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.TxMcast))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.TxUcast != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.TxUcast))
		i--
		dAtA[i] = 0x78
	}
	if m.TxBytes != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.TxBytes))
		i--
		dAtA[i] = 0x70
	}
	if m.TxFrames != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.TxFrames))
		i--
		dAtA[i] = 0x68
	}
	if m.RxMcastLegacy != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxMcastLegacy))
		i--
		dAtA[i] = 0x60
	}
	if m.RxEapol != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxEapol))
		i--
		dAtA[i] = 0x58
	}
	if m.RxDrop != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxDrop))
		i--
		dAtA[i] = 0x50
	}
	if m.RxBcast != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxBcast))
		i--
		dAtA[i] = 0x48
	}
	if m.RxMcast != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxMcast))
		i--
		dAtA[i] = 0x40
	}
	if m.RxUcast != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxUcast))
		i--
		dAtA[i] = 0x38
	}
	if m.RxBytes != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxBytes))
		i--
		dAtA[i] = 0x30
	}
	if m.RxFrames != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.RxFrames))
		i--
		dAtA[i] = 0x28
	}
	if m.Vlan != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.Vlan))
		i--
		dAtA[i] = 0x20
	}
	if m.Ipv6Address != nil {
		i -= len(*m.Ipv6Address)
		copy(dAtA[i:], *m.Ipv6Address)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.Ipv6Address)))
		i--
		dAtA[i] = 0x1a
	}
	if m.IpAddress != nil {
		i -= len(*m.IpAddress)
		copy(dAtA[i:], *m.IpAddress)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.IpAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.ClientMac != nil {
		i -= len(*m.ClientMac)
		copy(dAtA[i:], *m.ClientMac)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.ClientMac)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *APWiredClientStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *APWiredClientStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *APWiredClientStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ClusterId != nil {
		i -= len(*m.ClusterId)
		copy(dAtA[i:], *m.ClusterId)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.ClusterId)))
		i--
		dAtA[i] = 0x62
	}
	if m.MapId != nil {
		i -= len(*m.MapId)
		copy(dAtA[i:], *m.MapId)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.MapId)))
		i--
		dAtA[i] = 0x5a
	}
	if m.AptenantId != nil {
		i -= len(*m.AptenantId)
		copy(dAtA[i:], *m.AptenantId)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.AptenantId)))
		i--
		dAtA[i] = 0x52
	}
	if m.ApgroupId != nil {
		i -= len(*m.ApgroupId)
		copy(dAtA[i:], *m.ApgroupId)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.ApgroupId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.DeviceName != nil {
		i -= len(*m.DeviceName)
		copy(dAtA[i:], *m.DeviceName)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.DeviceName)))
		i--
		dAtA[i] = 0x42
	}
	if m.DomainId != nil {
		i -= len(*m.DomainId)
		copy(dAtA[i:], *m.DomainId)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.DomainId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ZoneId != nil {
		i -= len(*m.ZoneId)
		copy(dAtA[i:], *m.ZoneId)
		i = encodeVarintApWiredClient(dAtA, i, uint64(len(*m.ZoneId)))
		i--
		dAtA[i] = 0x32
	}
	if m.AggregationInterval != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.AggregationInterval))
		i--
		dAtA[i] = 0x28
	}
	if m.SampleTime != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.SampleTime))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Clients) > 0 {
		for iNdEx := len(m.Clients) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Clients[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApWiredClient(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Version != nil {
		i = encodeVarintApWiredClient(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApWiredClient(dAtA []byte, offset int, v uint64) int {
	offset -= sovApWiredClient(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *APWiredClientInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClientMac != nil {
		l = len(*m.ClientMac)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.IpAddress != nil {
		l = len(*m.IpAddress)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.Ipv6Address != nil {
		l = len(*m.Ipv6Address)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.Vlan != nil {
		n += 1 + sovApWiredClient(uint64(*m.Vlan))
	}
	if m.RxFrames != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxFrames))
	}
	if m.RxBytes != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxBytes))
	}
	if m.RxUcast != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxUcast))
	}
	if m.RxMcast != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxMcast))
	}
	if m.RxBcast != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxBcast))
	}
	if m.RxDrop != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxDrop))
	}
	if m.RxEapol != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxEapol))
	}
	if m.RxMcastLegacy != nil {
		n += 1 + sovApWiredClient(uint64(*m.RxMcastLegacy))
	}
	if m.TxFrames != nil {
		n += 1 + sovApWiredClient(uint64(*m.TxFrames))
	}
	if m.TxBytes != nil {
		n += 1 + sovApWiredClient(uint64(*m.TxBytes))
	}
	if m.TxUcast != nil {
		n += 1 + sovApWiredClient(uint64(*m.TxUcast))
	}
	if m.TxMcast != nil {
		n += 2 + sovApWiredClient(uint64(*m.TxMcast))
	}
	if m.TxBcast != nil {
		n += 2 + sovApWiredClient(uint64(*m.TxBcast))
	}
	if m.TxDrop != nil {
		n += 2 + sovApWiredClient(uint64(*m.TxDrop))
	}
	if m.TxEapol != nil {
		n += 2 + sovApWiredClient(uint64(*m.TxEapol))
	}
	if m.AuthStatus != nil {
		n += 2 + sovApWiredClient(uint64(*m.AuthStatus))
	}
	if m.EthIF != nil {
		l = len(*m.EthIF)
		n += 2 + l + sovApWiredClient(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *APWiredClientStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		n += 1 + sovApWiredClient(uint64(*m.Version))
	}
	if len(m.Clients) > 0 {
		for _, e := range m.Clients {
			l = e.Size()
			n += 1 + l + sovApWiredClient(uint64(l))
		}
	}
	if m.Timestamp != nil {
		n += 1 + sovApWiredClient(uint64(*m.Timestamp))
	}
	if m.SampleTime != nil {
		n += 1 + sovApWiredClient(uint64(*m.SampleTime))
	}
	if m.AggregationInterval != nil {
		n += 1 + sovApWiredClient(uint64(*m.AggregationInterval))
	}
	if m.ZoneId != nil {
		l = len(*m.ZoneId)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.DomainId != nil {
		l = len(*m.DomainId)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.DeviceName != nil {
		l = len(*m.DeviceName)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.ApgroupId != nil {
		l = len(*m.ApgroupId)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.AptenantId != nil {
		l = len(*m.AptenantId)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.MapId != nil {
		l = len(*m.MapId)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.ClusterId != nil {
		l = len(*m.ClusterId)
		n += 1 + l + sovApWiredClient(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApWiredClient(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApWiredClient(x uint64) (n int) {
	return sovApWiredClient(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *APWiredClientInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApWiredClient
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: APWiredClientInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: APWiredClientInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClientMac = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.IpAddress = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ipv6Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Ipv6Address = &s
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vlan", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Vlan = &v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxFrames", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxFrames = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxBytes", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxBytes = &v
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxUcast", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxUcast = &v
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxMcast", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxMcast = &v
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxBcast", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxBcast = &v
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxDrop", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxDrop = &v
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxEapol", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxEapol = &v
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxMcastLegacy", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxMcastLegacy = &v
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxFrames", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxFrames = &v
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBytes", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxBytes = &v
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxUcast", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxUcast = &v
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxMcast", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxMcast = &v
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBcast", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxBcast = &v
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxDrop", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxDrop = &v
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxEapol", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxEapol = &v
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthStatus", wireType)
			}
			var v APWiredClientInfo_AUTH_STATUS
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= APWiredClientInfo_AUTH_STATUS(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AuthStatus = &v
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthIF", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.EthIF = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApWiredClient(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *APWiredClientStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApWiredClient
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: APWiredClientStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: APWiredClientStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Clients", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Clients = append(m.Clients, &APWiredClientInfo{})
			if err := m.Clients[len(m.Clients)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleTime", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SampleTime = &v
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationInterval", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AggregationInterval = &v
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneId = &s
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainId = &s
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DeviceName = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApgroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApgroupId = &s
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AptenantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AptenantId = &s
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MapId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MapId = &s
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApWiredClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClusterId = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApWiredClient(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApWiredClient
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApWiredClient(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApWiredClient
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApWiredClient
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApWiredClient
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApWiredClient
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApWiredClient
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApWiredClient        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApWiredClient          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApWiredClient = fmt.Errorf("proto: unexpected end of group")
)
