// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nanopb.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldType int32

const (
	FieldType_FT_DEFAULT  FieldType = 0
	FieldType_FT_CALLBACK FieldType = 1
	FieldType_FT_POINTER  FieldType = 4
	FieldType_FT_STATIC   FieldType = 2
	FieldType_FT_IGNORE   FieldType = 3
	FieldType_FT_INLINE   FieldType = 5
)

var FieldType_name = map[int32]string{
	0: "FT_DEFAULT",
	1: "FT_CALLBACK",
	4: "FT_POINTER",
	2: "FT_STATIC",
	3: "FT_IGNORE",
	5: "FT_INLINE",
}

var FieldType_value = map[string]int32{
	"FT_DEFAULT":  0,
	"FT_CALLBACK": 1,
	"FT_POINTER":  4,
	"FT_STATIC":   2,
	"FT_IGNORE":   3,
	"FT_INLINE":   5,
}

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return proto.EnumName(FieldType_name, int32(x))
}

func (x *FieldType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FieldType_value, data, "FieldType")
	if err != nil {
		return err
	}
	*x = FieldType(value)
	return nil
}

func (FieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad06422d55f23f27, []int{0}
}

type IntSize int32

const (
	IntSize_IS_DEFAULT IntSize = 0
	IntSize_IS_8       IntSize = 8
	IntSize_IS_16      IntSize = 16
	IntSize_IS_32      IntSize = 32
	IntSize_IS_64      IntSize = 64
)

var IntSize_name = map[int32]string{
	0:  "IS_DEFAULT",
	8:  "IS_8",
	16: "IS_16",
	32: "IS_32",
	64: "IS_64",
}

var IntSize_value = map[string]int32{
	"IS_DEFAULT": 0,
	"IS_8":       8,
	"IS_16":      16,
	"IS_32":      32,
	"IS_64":      64,
}

func (x IntSize) Enum() *IntSize {
	p := new(IntSize)
	*p = x
	return p
}

func (x IntSize) String() string {
	return proto.EnumName(IntSize_name, int32(x))
}

func (x *IntSize) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IntSize_value, data, "IntSize")
	if err != nil {
		return err
	}
	*x = IntSize(value)
	return nil
}

func (IntSize) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad06422d55f23f27, []int{1}
}

// This is the inner options message, which basically defines options for
// a field. When it is used in message or file scope, it applies to all
// fields.
type NanoPBOptions struct {
	// Allocated size for 'bytes' and 'string' fields.
	// For string fields, this should include the space for null terminator.
	MaxSize *int32 `protobuf:"varint,1,opt,name=max_size,json=maxSize" json:"max_size,omitempty"`
	// Maximum length for 'string' fields. Setting this is equivalent
	// to setting max_size to a value of length+1.
	MaxLength *int32 `protobuf:"varint,14,opt,name=max_length,json=maxLength" json:"max_length,omitempty"`
	// Allocated number of entries in arrays ('repeated' fields)
	MaxCount *int32 `protobuf:"varint,2,opt,name=max_count,json=maxCount" json:"max_count,omitempty"`
	// Size of integer fields. Can save some memory if you don't need
	// full 32 bits for the value.
	IntSize *IntSize `protobuf:"varint,7,opt,name=int_size,json=intSize,enum=proto.IntSize,def=0" json:"int_size,omitempty"`
	// Force type of field (callback or static allocation)
	Type *FieldType `protobuf:"varint,3,opt,name=type,enum=proto.FieldType,def=0" json:"type,omitempty"`
	// Use long names for enums, i.e. EnumName_EnumValue.
	LongNames *bool `protobuf:"varint,4,opt,name=long_names,json=longNames,def=1" json:"long_names,omitempty"`
	// Add 'packed' attribute to generated structs.
	// Note: this cannot be used on CPUs that break on unaligned
	// accesses to variables.
	PackedStruct *bool `protobuf:"varint,5,opt,name=packed_struct,json=packedStruct,def=0" json:"packed_struct,omitempty"`
	// Add 'packed' attribute to generated enums.
	PackedEnum *bool `protobuf:"varint,10,opt,name=packed_enum,json=packedEnum,def=0" json:"packed_enum,omitempty"`
	// Skip this message
	SkipMessage *bool `protobuf:"varint,6,opt,name=skip_message,json=skipMessage,def=0" json:"skip_message,omitempty"`
	// Generate oneof fields as normal optional fields instead of union.
	NoUnions *bool `protobuf:"varint,8,opt,name=no_unions,json=noUnions,def=0" json:"no_unions,omitempty"`
	// integer type tag for a message
	Msgid *uint32 `protobuf:"varint,9,opt,name=msgid" json:"msgid,omitempty"`
	// decode oneof as anonymous union
	AnonymousOneof *bool `protobuf:"varint,11,opt,name=anonymous_oneof,json=anonymousOneof,def=0" json:"anonymous_oneof,omitempty"`
	// Proto3 singular field does not generate a "has_" flag
	Proto3 *bool `protobuf:"varint,12,opt,name=proto3,def=0" json:"proto3,omitempty"`
	// Generate an enum->string mapping function (can take up lots of space).
	EnumToString *bool `protobuf:"varint,13,opt,name=enum_to_string,json=enumToString,def=0" json:"enum_to_string,omitempty"`
	// Generate bytes arrays with fixed length
	FixedLength          *bool    `protobuf:"varint,15,opt,name=fixed_length,json=fixedLength,def=0" json:"fixed_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NanoPBOptions) Reset()         { *m = NanoPBOptions{} }
func (m *NanoPBOptions) String() string { return proto.CompactTextString(m) }
func (*NanoPBOptions) ProtoMessage()    {}
func (*NanoPBOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad06422d55f23f27, []int{0}
}
func (m *NanoPBOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NanoPBOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NanoPBOptions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NanoPBOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NanoPBOptions.Merge(m, src)
}
func (m *NanoPBOptions) XXX_Size() int {
	return m.Size()
}
func (m *NanoPBOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_NanoPBOptions.DiscardUnknown(m)
}

var xxx_messageInfo_NanoPBOptions proto.InternalMessageInfo

const Default_NanoPBOptions_IntSize IntSize = IntSize_IS_DEFAULT
const Default_NanoPBOptions_Type FieldType = FieldType_FT_DEFAULT
const Default_NanoPBOptions_LongNames bool = true
const Default_NanoPBOptions_PackedStruct bool = false
const Default_NanoPBOptions_PackedEnum bool = false
const Default_NanoPBOptions_SkipMessage bool = false
const Default_NanoPBOptions_NoUnions bool = false
const Default_NanoPBOptions_AnonymousOneof bool = false
const Default_NanoPBOptions_Proto3 bool = false
const Default_NanoPBOptions_EnumToString bool = false
const Default_NanoPBOptions_FixedLength bool = false

func (m *NanoPBOptions) GetMaxSize() int32 {
	if m != nil && m.MaxSize != nil {
		return *m.MaxSize
	}
	return 0
}

func (m *NanoPBOptions) GetMaxLength() int32 {
	if m != nil && m.MaxLength != nil {
		return *m.MaxLength
	}
	return 0
}

func (m *NanoPBOptions) GetMaxCount() int32 {
	if m != nil && m.MaxCount != nil {
		return *m.MaxCount
	}
	return 0
}

func (m *NanoPBOptions) GetIntSize() IntSize {
	if m != nil && m.IntSize != nil {
		return *m.IntSize
	}
	return Default_NanoPBOptions_IntSize
}

func (m *NanoPBOptions) GetType() FieldType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_NanoPBOptions_Type
}

func (m *NanoPBOptions) GetLongNames() bool {
	if m != nil && m.LongNames != nil {
		return *m.LongNames
	}
	return Default_NanoPBOptions_LongNames
}

func (m *NanoPBOptions) GetPackedStruct() bool {
	if m != nil && m.PackedStruct != nil {
		return *m.PackedStruct
	}
	return Default_NanoPBOptions_PackedStruct
}

func (m *NanoPBOptions) GetPackedEnum() bool {
	if m != nil && m.PackedEnum != nil {
		return *m.PackedEnum
	}
	return Default_NanoPBOptions_PackedEnum
}

func (m *NanoPBOptions) GetSkipMessage() bool {
	if m != nil && m.SkipMessage != nil {
		return *m.SkipMessage
	}
	return Default_NanoPBOptions_SkipMessage
}

func (m *NanoPBOptions) GetNoUnions() bool {
	if m != nil && m.NoUnions != nil {
		return *m.NoUnions
	}
	return Default_NanoPBOptions_NoUnions
}

func (m *NanoPBOptions) GetMsgid() uint32 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return 0
}

func (m *NanoPBOptions) GetAnonymousOneof() bool {
	if m != nil && m.AnonymousOneof != nil {
		return *m.AnonymousOneof
	}
	return Default_NanoPBOptions_AnonymousOneof
}

func (m *NanoPBOptions) GetProto3() bool {
	if m != nil && m.Proto3 != nil {
		return *m.Proto3
	}
	return Default_NanoPBOptions_Proto3
}

func (m *NanoPBOptions) GetEnumToString() bool {
	if m != nil && m.EnumToString != nil {
		return *m.EnumToString
	}
	return Default_NanoPBOptions_EnumToString
}

func (m *NanoPBOptions) GetFixedLength() bool {
	if m != nil && m.FixedLength != nil {
		return *m.FixedLength
	}
	return Default_NanoPBOptions_FixedLength
}

var E_NanopbFileopt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*NanoPBOptions)(nil),
	Field:         1010,
	Name:          "proto.nanopb_fileopt",
	Tag:           "bytes,1010,opt,name=nanopb_fileopt",
	Filename:      "nanopb.proto",
}

var E_NanopbMsgopt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*NanoPBOptions)(nil),
	Field:         1010,
	Name:          "proto.nanopb_msgopt",
	Tag:           "bytes,1010,opt,name=nanopb_msgopt",
	Filename:      "nanopb.proto",
}

var E_NanopbEnumopt = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*NanoPBOptions)(nil),
	Field:         1010,
	Name:          "proto.nanopb_enumopt",
	Tag:           "bytes,1010,opt,name=nanopb_enumopt",
	Filename:      "nanopb.proto",
}

var E_Nanopb = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*NanoPBOptions)(nil),
	Field:         1010,
	Name:          "proto.nanopb",
	Tag:           "bytes,1010,opt,name=nanopb",
	Filename:      "nanopb.proto",
}

func init() {
	proto.RegisterEnum("proto.FieldType", FieldType_name, FieldType_value)
	proto.RegisterEnum("proto.IntSize", IntSize_name, IntSize_value)
	proto.RegisterType((*NanoPBOptions)(nil), "proto.NanoPBOptions")
	proto.RegisterExtension(E_NanopbFileopt)
	proto.RegisterExtension(E_NanopbMsgopt)
	proto.RegisterExtension(E_NanopbEnumopt)
	proto.RegisterExtension(E_Nanopb)
}

func init() { proto.RegisterFile("nanopb.proto", fileDescriptor_ad06422d55f23f27) }

var fileDescriptor_ad06422d55f23f27 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x90, 0x90, 0xe4, 0xe6, 0x07, 0x6b, 0xc4, 0x62, 0xbe, 0x1f, 0xf2, 0x45, 0x7c, 0x52,
	0x15, 0xa5, 0x92, 0x69, 0xa1, 0x45, 0x55, 0x56, 0x0d, 0x21, 0xa9, 0xac, 0x86, 0x04, 0x39, 0x66,
	0xd3, 0x2e, 0x46, 0x26, 0x99, 0xb8, 0xd3, 0xd8, 0x33, 0x56, 0x6c, 0x4b, 0x81, 0x27, 0xe9, 0x23,
	0x75, 0x59, 0xf5, 0x09, 0x2a, 0xfa, 0x06, 0x7d, 0x82, 0x6a, 0x3c, 0x03, 0x35, 0x2a, 0x0b, 0xba,
	0xb2, 0xef, 0x39, 0xe7, 0x1e, 0xdd, 0xb9, 0x3f, 0x50, 0xe3, 0x1e, 0x17, 0xd1, 0xa5, 0x15, 0xad,
	0x44, 0x22, 0x50, 0x31, 0xfb, 0xfc, 0xdd, 0xf2, 0x85, 0xf0, 0x03, 0x7a, 0x90, 0x45, 0x97, 0xe9,
	0xe2, 0x60, 0x4e, 0xe3, 0xd9, 0x8a, 0x45, 0x89, 0x58, 0x29, 0xe1, 0xfe, 0xd7, 0x02, 0xd4, 0xc7,
	0x1e, 0x17, 0xe7, 0x27, 0x93, 0x28, 0x61, 0x82, 0xc7, 0xe8, 0x2f, 0x28, 0x87, 0xde, 0x9a, 0xc4,
	0xec, 0x9a, 0x62, 0xa3, 0x65, 0xb4, 0x8b, 0x4e, 0x29, 0xf4, 0xd6, 0x53, 0x76, 0x4d, 0xd1, 0x1e,
	0x80, 0xa4, 0x02, 0xca, 0xfd, 0xe4, 0x03, 0x6e, 0x64, 0x64, 0x25, 0xf4, 0xd6, 0xa3, 0x0c, 0x40,
	0xff, 0x80, 0x0c, 0xc8, 0x4c, 0xa4, 0x3c, 0xc1, 0x9b, 0x19, 0x2b, 0xad, 0xfa, 0x32, 0x46, 0x2f,
	0xa1, 0xcc, 0x78, 0xa2, 0x6c, 0x4b, 0x2d, 0xa3, 0xdd, 0x38, 0x6c, 0xa8, 0x12, 0x2c, 0x9b, 0x27,
	0xd2, 0xbd, 0x0b, 0xf6, 0x94, 0x9c, 0x0e, 0x86, 0xbd, 0x8b, 0x91, 0xeb, 0x94, 0x98, 0x02, 0xd1,
	0x33, 0x28, 0x24, 0x57, 0x11, 0xc5, 0x5b, 0x59, 0x8a, 0xa9, 0x53, 0x86, 0x8c, 0x06, 0x73, 0xf7,
	0x2a, 0xa2, 0x5d, 0x18, 0xba, 0x77, 0x49, 0x99, 0x12, 0xfd, 0x0f, 0x10, 0x08, 0xee, 0x13, 0xee,
	0x85, 0x34, 0xc6, 0x85, 0x96, 0xd1, 0x2e, 0x77, 0x0b, 0xc9, 0x2a, 0xa5, 0x4e, 0x45, 0xe2, 0x63,
	0x09, 0xa3, 0x0e, 0xd4, 0x23, 0x6f, 0xb6, 0xa4, 0x73, 0x12, 0x27, 0xab, 0x74, 0x96, 0xe0, 0x62,
	0xa6, 0x2b, 0x2e, 0xbc, 0x20, 0xa6, 0x4e, 0x4d, 0x71, 0xd3, 0x8c, 0x42, 0x4f, 0xa0, 0xaa, 0xb5,
	0x94, 0xa7, 0x21, 0x86, 0xbc, 0x12, 0x14, 0x33, 0xe0, 0x69, 0x88, 0xda, 0x50, 0x8b, 0x97, 0x2c,
	0x22, 0x21, 0x8d, 0x63, 0xcf, 0xa7, 0x78, 0x3b, 0x2f, 0xac, 0x4a, 0xea, 0x4c, 0x31, 0x68, 0x1f,
	0x2a, 0x5c, 0x90, 0x94, 0xcb, 0x7e, 0xe3, 0x72, 0x5e, 0x56, 0xe6, 0xe2, 0x22, 0x83, 0xd1, 0x2e,
	0x14, 0xc3, 0xd8, 0x67, 0x73, 0x5c, 0x69, 0x19, 0xed, 0xba, 0xa3, 0x02, 0x64, 0xc1, 0x8e, 0xc7,
	0x05, 0xbf, 0x0a, 0x45, 0x1a, 0x13, 0xc1, 0xa9, 0x58, 0xe0, 0x6a, 0x3e, 0xbf, 0x71, 0xc7, 0x4e,
	0x24, 0x89, 0xf6, 0x60, 0x3b, 0xeb, 0xd8, 0x11, 0xae, 0xe5, 0x65, 0x1a, 0x44, 0x4f, 0xa1, 0x21,
	0xdf, 0x44, 0x12, 0x21, 0xfb, 0xc0, 0xb8, 0x8f, 0xeb, 0xf7, 0xfa, 0x20, 0x49, 0x57, 0x4c, 0x33,
	0x4a, 0xbe, 0x6f, 0xc1, 0xd6, 0x74, 0x7e, 0x3b, 0xff, 0x9d, 0x7b, 0xef, 0xcb, 0x28, 0xb5, 0x08,
	0x1d, 0x06, 0x95, 0xbb, 0x09, 0xa1, 0x06, 0xe4, 0x66, 0x64, 0x6e, 0xa0, 0x1d, 0xa8, 0x0e, 0x5d,
	0xd2, 0xef, 0x8d, 0x46, 0x27, 0xbd, 0xfe, 0x5b, 0xd3, 0xd0, 0x82, 0xf3, 0x89, 0x3d, 0x76, 0x07,
	0x8e, 0x59, 0x40, 0x75, 0xa8, 0x0c, 0x5d, 0x32, 0x75, 0x7b, 0xae, 0xdd, 0x37, 0x37, 0x75, 0x68,
	0xbf, 0x19, 0x4f, 0x9c, 0x81, 0xb9, 0x75, 0x1b, 0x8e, 0x47, 0xf6, 0x78, 0x60, 0x16, 0x3b, 0xa7,
	0x50, 0xd2, 0xfb, 0x23, 0x7d, 0x7e, 0x6d, 0x90, 0xb9, 0x81, 0xca, 0x50, 0xb0, 0xa7, 0xe4, 0x95,
	0x59, 0x46, 0x15, 0x28, 0xda, 0x53, 0xf2, 0xfc, 0xd8, 0x34, 0xf5, 0xef, 0xd1, 0xa1, 0xd9, 0xd2,
	0xbf, 0xc7, 0x2f, 0xcc, 0xd7, 0xdd, 0x77, 0xd0, 0x50, 0xe7, 0x43, 0x16, 0x2c, 0xa0, 0x22, 0x4a,
	0xd0, 0xbf, 0x96, 0x3a, 0x1d, 0xeb, 0xf6, 0x74, 0xac, 0x21, 0x0b, 0xa8, 0xbe, 0x11, 0xfc, 0x43,
	0x6e, 0x70, 0xf5, 0x70, 0x57, 0xaf, 0xe3, 0xbd, 0x03, 0x72, 0xea, 0xca, 0x6a, 0xa8, 0x9c, 0xba,
	0xef, 0x41, 0x03, 0x24, 0x8c, 0x7d, 0x69, 0xfd, 0xdf, 0x6f, 0xd6, 0x7a, 0x2f, 0x1e, 0xe5, 0xae,
	0xef, 0xfc, 0x2c, 0xf3, 0xca, 0x15, 0x2e, 0x47, 0xf5, 0x70, 0xe1, 0x72, 0x39, 0xff, 0xa4, 0xf0,
	0x81, 0x72, 0xea, 0x8e, 0x60, 0x5b, 0x01, 0x68, 0xef, 0x81, 0x66, 0xd0, 0x60, 0xfe, 0x28, 0x53,
	0xed, 0x71, 0xd2, 0xf9, 0x7c, 0xd3, 0x34, 0xbe, 0xdc, 0x34, 0x8d, 0x6f, 0x37, 0x4d, 0xe3, 0xd3,
	0xf7, 0xe6, 0x06, 0xe0, 0x05, 0xb3, 0x96, 0x5e, 0x14, 0x33, 0x6b, 0x29, 0x12, 0x66, 0x7d, 0x8c,
	0x3c, 0x4b, 0x69, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x63, 0x8d, 0x68, 0x7a, 0xcc, 0x04, 0x00,
	0x00,
}

func (m *NanoPBOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NanoPBOptions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NanoPBOptions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.FixedLength != nil {
		i--
		if *m.FixedLength {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x78
	}
	if m.MaxLength != nil {
		i = encodeVarintNanopb(dAtA, i, uint64(*m.MaxLength))
		i--
		dAtA[i] = 0x70
	}
	if m.EnumToString != nil {
		i--
		if *m.EnumToString {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.Proto3 != nil {
		i--
		if *m.Proto3 {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.AnonymousOneof != nil {
		i--
		if *m.AnonymousOneof {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.PackedEnum != nil {
		i--
		if *m.PackedEnum {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.Msgid != nil {
		i = encodeVarintNanopb(dAtA, i, uint64(*m.Msgid))
		i--
		dAtA[i] = 0x48
	}
	if m.NoUnions != nil {
		i--
		if *m.NoUnions {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.IntSize != nil {
		i = encodeVarintNanopb(dAtA, i, uint64(*m.IntSize))
		i--
		dAtA[i] = 0x38
	}
	if m.SkipMessage != nil {
		i--
		if *m.SkipMessage {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.PackedStruct != nil {
		i--
		if *m.PackedStruct {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.LongNames != nil {
		i--
		if *m.LongNames {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Type != nil {
		i = encodeVarintNanopb(dAtA, i, uint64(*m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxCount != nil {
		i = encodeVarintNanopb(dAtA, i, uint64(*m.MaxCount))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxSize != nil {
		i = encodeVarintNanopb(dAtA, i, uint64(*m.MaxSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNanopb(dAtA []byte, offset int, v uint64) int {
	offset -= sovNanopb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NanoPBOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxSize != nil {
		n += 1 + sovNanopb(uint64(*m.MaxSize))
	}
	if m.MaxCount != nil {
		n += 1 + sovNanopb(uint64(*m.MaxCount))
	}
	if m.Type != nil {
		n += 1 + sovNanopb(uint64(*m.Type))
	}
	if m.LongNames != nil {
		n += 2
	}
	if m.PackedStruct != nil {
		n += 2
	}
	if m.SkipMessage != nil {
		n += 2
	}
	if m.IntSize != nil {
		n += 1 + sovNanopb(uint64(*m.IntSize))
	}
	if m.NoUnions != nil {
		n += 2
	}
	if m.Msgid != nil {
		n += 1 + sovNanopb(uint64(*m.Msgid))
	}
	if m.PackedEnum != nil {
		n += 2
	}
	if m.AnonymousOneof != nil {
		n += 2
	}
	if m.Proto3 != nil {
		n += 2
	}
	if m.EnumToString != nil {
		n += 2
	}
	if m.MaxLength != nil {
		n += 1 + sovNanopb(uint64(*m.MaxLength))
	}
	if m.FixedLength != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovNanopb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNanopb(x uint64) (n int) {
	return sovNanopb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NanoPBOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNanopb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NanoPBOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NanoPBOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSize", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxSize = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCount", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxCount = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var v FieldType
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= FieldType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Type = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LongNames", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.LongNames = &b
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackedStruct", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.PackedStruct = &b
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipMessage", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.SkipMessage = &b
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntSize", wireType)
			}
			var v IntSize
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= IntSize(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IntSize = &v
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoUnions", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.NoUnions = &b
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Msgid = &v
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackedEnum", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.PackedEnum = &b
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnonymousOneof", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.AnonymousOneof = &b
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proto3", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Proto3 = &b
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnumToString", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.EnumToString = &b
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLength", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxLength = &v
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedLength", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.FixedLength = &b
		default:
			iNdEx = preIndex
			skippy, err := skipNanopb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNanopb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNanopb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNanopb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNanopb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNanopb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNanopb
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNanopb
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNanopb
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNanopb        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNanopb          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNanopb = fmt.Errorf("proto: unexpected end of group")
)
