// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sci-alarm.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AlarmMessage_AlarmState int32

const (
	//*
	// @description OUTSTANDING
	// @since 3.5.1
	AlarmMessage_OUTSTANDING AlarmMessage_AlarmState = 0
	//*
	// @description CLEARED
	// @since 3.5.1
	AlarmMessage_CLEARED AlarmMessage_AlarmState = 1
)

var AlarmMessage_AlarmState_name = map[int32]string{
	0: "OUTSTANDING",
	1: "CLEARED",
}

var AlarmMessage_AlarmState_value = map[string]int32{
	"OUTSTANDING": 0,
	"CLEARED":     1,
}

func (x AlarmMessage_AlarmState) Enum() *AlarmMessage_AlarmState {
	p := new(AlarmMessage_AlarmState)
	*p = x
	return p
}

func (x AlarmMessage_AlarmState) String() string {
	return proto.EnumName(AlarmMessage_AlarmState_name, int32(x))
}

func (x *AlarmMessage_AlarmState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AlarmMessage_AlarmState_value, data, "AlarmMessage_AlarmState")
	if err != nil {
		return err
	}
	*x = AlarmMessage_AlarmState(value)
	return nil
}

func (AlarmMessage_AlarmState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48e55434ad3a669e, []int{0, 0}
}

type AlarmMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description GPB version
	// @since 3.5.1
	Version *uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Alarm UUID
	// @since 3.5.1
	AlarmUuid *string `protobuf:"bytes,2,opt,name=alarmUuid" json:"alarmUuid,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Alarm Code defined by AlarmEnum
	// @since 3.5.1
	AlarmCode *uint32 `protobuf:"varint,3,opt,name=alarmCode" json:"alarmCode,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Alarm severity defined by AlarmEnum
	// @since 3.5.1
	AlarmSeverity *string `protobuf:"bytes,4,opt,name=alarmSeverity" json:"alarmSeverity,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Alarm main categorty defined by AlarmCategory
	// @since 3.5.1
	MainCategory *string `protobuf:"bytes,5,opt,name=mainCategory" json:"mainCategory,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Alarm type description defined by AlarmEnum represented with String.
	// @since 3.5.1
	AlarmType *string `protobuf:"bytes,6,opt,name=alarmType" json:"alarmType,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description The triggerring event code number for this alarm.
	// @since 3.5.1
	InitEventCode *uint32 `protobuf:"varint,7,opt,name=initEventCode" json:"initEventCode,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description The timestamp of this alarm's creation.
	// @since 3.5.1
	Timestamp *uint64 `protobuf:"varint,8,opt,name=timestamp" json:"timestamp,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description The AlarmState of current triggering alarm which contains (OUTSTANDING/CLEARED).
	// @since 3.5.1
	AlarmState *AlarmMessage_AlarmState `protobuf:"varint,9,opt,name=alarmState,enum=proto.AlarmMessage_AlarmState" json:"alarmState,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description The AlarmMessageEntry contains additional attribute values required by outer service.
	// @since 3.5.1
	Attributes []*AlarmMessageEntry `protobuf:"bytes,10,rep,name=attributes" json:"attributes,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain UUID.
	// @since 3.5.1
	DomainId *string `protobuf:"bytes,11,opt,name=domainId" json:"domainId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone UUID. Unique zone ID assigned by SZ controller.
	// @since 3.5.1
	ZoneId *string `protobuf:"bytes,12,opt,name=zoneId" json:"zoneId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP Group identifier.
	// @since 3.5.1
	ApGroupId *string `protobuf:"bytes,13,opt,name=apGroupId" json:"apGroupId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Access Point  MAC address.
	// @since 3.5.1
	ApMac *string `protobuf:"bytes,14,opt,name=apMac" json:"apMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description UE/Client MAC address if the events are related to client.
	// @since 3.5.1
	ClientMac *string `protobuf:"bytes,15,opt,name=clientMac" json:"clientMac,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Reason for the alarm to occur.
	// @since 3.5.1
	Reason *string `protobuf:"bytes,16,opt,name=reason" json:"reason,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain name.
	// @since 3.5.1
	DomainName *string `protobuf:"bytes,17,opt,name=domainName" json:"domainName,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone name assigned by the controller. The admin configures the Zone name via the contoller's user interface.
	// @since 3.5.1
	ZoneName *string `protobuf:"bytes,18,opt,name=zoneName" json:"zoneName,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP Group name.
	// @since 3.5.1
	ApGroupName *string `protobuf:"bytes,19,opt,name=apGroupName" json:"apGroupName,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description IPv4 address of the AP.
	// @since 3.5.1
	ApIpAddress *string `protobuf:"bytes,20,opt,name=apIpAddress" json:"apIpAddress,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description IPv6 address of the AP.
	// @since 3.5.1
	ApIpv6Address *string `protobuf:"bytes,21,opt,name=apIpv6Address" json:"apIpv6Address,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Description of the alarm represented by string.
	// @since 3.5.1
	Description *string `protobuf:"bytes,22,opt,name=description" json:"description,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Sub category of the alarm.
	// @since 3.5.1
	SubCategory *string `protobuf:"bytes,23,opt,name=subCategory" json:"subCategory,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Blade ID information from which node alarm created.
	// @since 3.5.1
	BladeId              *string  `protobuf:"bytes,24,opt,name=bladeId" json:"bladeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmMessage) Reset()         { *m = AlarmMessage{} }
func (m *AlarmMessage) String() string { return proto.CompactTextString(m) }
func (*AlarmMessage) ProtoMessage()    {}
func (*AlarmMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e55434ad3a669e, []int{0}
}
func (m *AlarmMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AlarmMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AlarmMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AlarmMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmMessage.Merge(m, src)
}
func (m *AlarmMessage) XXX_Size() int {
	return m.Size()
}
func (m *AlarmMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmMessage proto.InternalMessageInfo

func (m *AlarmMessage) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AlarmMessage) GetAlarmUuid() string {
	if m != nil && m.AlarmUuid != nil {
		return *m.AlarmUuid
	}
	return ""
}

func (m *AlarmMessage) GetAlarmCode() uint32 {
	if m != nil && m.AlarmCode != nil {
		return *m.AlarmCode
	}
	return 0
}

func (m *AlarmMessage) GetAlarmSeverity() string {
	if m != nil && m.AlarmSeverity != nil {
		return *m.AlarmSeverity
	}
	return ""
}

func (m *AlarmMessage) GetMainCategory() string {
	if m != nil && m.MainCategory != nil {
		return *m.MainCategory
	}
	return ""
}

func (m *AlarmMessage) GetAlarmType() string {
	if m != nil && m.AlarmType != nil {
		return *m.AlarmType
	}
	return ""
}

func (m *AlarmMessage) GetInitEventCode() uint32 {
	if m != nil && m.InitEventCode != nil {
		return *m.InitEventCode
	}
	return 0
}

func (m *AlarmMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *AlarmMessage) GetAlarmState() AlarmMessage_AlarmState {
	if m != nil && m.AlarmState != nil {
		return *m.AlarmState
	}
	return AlarmMessage_OUTSTANDING
}

func (m *AlarmMessage) GetAttributes() []*AlarmMessageEntry {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *AlarmMessage) GetDomainId() string {
	if m != nil && m.DomainId != nil {
		return *m.DomainId
	}
	return ""
}

func (m *AlarmMessage) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *AlarmMessage) GetApGroupId() string {
	if m != nil && m.ApGroupId != nil {
		return *m.ApGroupId
	}
	return ""
}

func (m *AlarmMessage) GetApMac() string {
	if m != nil && m.ApMac != nil {
		return *m.ApMac
	}
	return ""
}

func (m *AlarmMessage) GetClientMac() string {
	if m != nil && m.ClientMac != nil {
		return *m.ClientMac
	}
	return ""
}

func (m *AlarmMessage) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *AlarmMessage) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *AlarmMessage) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *AlarmMessage) GetApGroupName() string {
	if m != nil && m.ApGroupName != nil {
		return *m.ApGroupName
	}
	return ""
}

func (m *AlarmMessage) GetApIpAddress() string {
	if m != nil && m.ApIpAddress != nil {
		return *m.ApIpAddress
	}
	return ""
}

func (m *AlarmMessage) GetApIpv6Address() string {
	if m != nil && m.ApIpv6Address != nil {
		return *m.ApIpv6Address
	}
	return ""
}

func (m *AlarmMessage) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *AlarmMessage) GetSubCategory() string {
	if m != nil && m.SubCategory != nil {
		return *m.SubCategory
	}
	return ""
}

func (m *AlarmMessage) GetBladeId() string {
	if m != nil && m.BladeId != nil {
		return *m.BladeId
	}
	return ""
}

type AlarmMessageEntry struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Alarm message entry key.
	// @since 3.5.1
	Key *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Alarm message entry value.
	// @since 3.5.1
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmMessageEntry) Reset()         { *m = AlarmMessageEntry{} }
func (m *AlarmMessageEntry) String() string { return proto.CompactTextString(m) }
func (*AlarmMessageEntry) ProtoMessage()    {}
func (*AlarmMessageEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_48e55434ad3a669e, []int{1}
}
func (m *AlarmMessageEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AlarmMessageEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AlarmMessageEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AlarmMessageEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmMessageEntry.Merge(m, src)
}
func (m *AlarmMessageEntry) XXX_Size() int {
	return m.Size()
}
func (m *AlarmMessageEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmMessageEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmMessageEntry proto.InternalMessageInfo

func (m *AlarmMessageEntry) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AlarmMessageEntry) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.AlarmMessage_AlarmState", AlarmMessage_AlarmState_name, AlarmMessage_AlarmState_value)
	proto.RegisterType((*AlarmMessage)(nil), "proto.AlarmMessage")
	proto.RegisterType((*AlarmMessageEntry)(nil), "proto.AlarmMessageEntry")
}

func init() { proto.RegisterFile("sci-alarm.proto", fileDescriptor_48e55434ad3a669e) }

var fileDescriptor_48e55434ad3a669e = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xee, 0xda, 0x26, 0x69, 0x4e, 0x92, 0x26, 0x1d, 0x6b, 0x1d, 0x44, 0x96, 0x25, 0x7a, 0x11,
	0x04, 0x73, 0x51, 0x50, 0x04, 0x41, 0x88, 0x69, 0x28, 0x0b, 0x36, 0xc2, 0x36, 0x7d, 0x80, 0xc9,
	0xee, 0x31, 0x0c, 0xcd, 0xfe, 0x30, 0x33, 0x1b, 0x89, 0x4f, 0xe2, 0x23, 0x79, 0xe9, 0xa5, 0x97,
	0x12, 0x5f, 0x44, 0x66, 0x66, 0x77, 0xb3, 0x41, 0xaf, 0x92, 0xef, 0xe7, 0xcc, 0xf9, 0xf6, 0xcc,
	0x19, 0xe8, 0xcb, 0x90, 0xbf, 0x66, 0x6b, 0x26, 0xe2, 0x71, 0x26, 0x52, 0x95, 0x92, 0x86, 0xf9,
	0x19, 0xfe, 0x6a, 0x42, 0x77, 0xa2, 0xe9, 0x5b, 0x94, 0x92, 0xad, 0x90, 0x50, 0x68, 0x6d, 0x50,
	0x48, 0x9e, 0x26, 0xd4, 0xf1, 0x9c, 0x51, 0x2f, 0x28, 0x21, 0x79, 0x0e, 0x6d, 0x73, 0xc0, 0x7d,
	0xce, 0x23, 0xfa, 0xc8, 0x73, 0x46, 0xed, 0x60, 0x4f, 0x54, 0xea, 0x34, 0x8d, 0x90, 0x1e, 0x9b,
	0xca, 0x3d, 0x41, 0x5e, 0x42, 0xcf, 0x80, 0x3b, 0xdc, 0xa0, 0xe0, 0x6a, 0x4b, 0x4f, 0x4c, 0xfd,
	0x21, 0x49, 0x86, 0xd0, 0x8d, 0x19, 0x4f, 0xa6, 0x4c, 0xe1, 0x2a, 0x15, 0x5b, 0xda, 0x30, 0xa6,
	0x03, 0xae, 0xea, 0xb3, 0xd8, 0x66, 0x48, 0x9b, 0xb5, 0x14, 0x9a, 0xd0, 0x7d, 0x78, 0xc2, 0xd5,
	0x6c, 0x83, 0x89, 0x32, 0x49, 0x5a, 0x26, 0xc9, 0x21, 0xa9, 0xcf, 0x50, 0x3c, 0x46, 0xa9, 0x58,
	0x9c, 0xd1, 0x53, 0xcf, 0x19, 0x9d, 0x04, 0x7b, 0x82, 0x7c, 0x00, 0xb0, 0xb1, 0x14, 0x53, 0x48,
	0xdb, 0x9e, 0x33, 0x3a, 0xbb, 0x72, 0xed, 0xd4, 0xc6, 0xf5, 0x51, 0x59, 0x60, 0x5c, 0x41, 0xad,
	0x82, 0xbc, 0x03, 0x60, 0x4a, 0x09, 0xbe, 0xcc, 0x15, 0x4a, 0x0a, 0xde, 0xf1, 0xa8, 0x73, 0x45,
	0xff, 0x53, 0x3f, 0x4b, 0x94, 0xd8, 0x06, 0x35, 0x2f, 0x79, 0x06, 0xa7, 0x51, 0xaa, 0xbf, 0xd6,
	0x8f, 0x68, 0xc7, 0x7c, 0x5a, 0x85, 0xc9, 0x25, 0x34, 0xbf, 0xa5, 0x09, 0xfa, 0x11, 0xed, 0x1a,
	0xa5, 0x40, 0x66, 0x1e, 0xd9, 0x8d, 0x48, 0xf3, 0xcc, 0x8f, 0x68, 0xaf, 0x98, 0x47, 0x49, 0x90,
	0x0b, 0x68, 0xb0, 0xec, 0x96, 0x85, 0xf4, 0xcc, 0x28, 0x16, 0xe8, 0x9a, 0x70, 0xcd, 0x31, 0x51,
	0x5a, 0xe9, 0xdb, 0x9a, 0x8a, 0xd0, 0x9d, 0x04, 0x32, 0x99, 0x26, 0x74, 0x60, 0x3b, 0x59, 0x44,
	0x5c, 0x00, 0x9b, 0x66, 0xce, 0x62, 0xa4, 0xe7, 0x46, 0xab, 0x31, 0x3a, 0xbd, 0xce, 0x64, 0x54,
	0x62, 0xd3, 0x97, 0x98, 0x78, 0xd0, 0x29, 0x42, 0x19, 0xf9, 0xb1, 0x91, 0xeb, 0x94, 0x75, 0xf8,
	0xd9, 0x24, 0x8a, 0x04, 0x4a, 0x49, 0x2f, 0x4a, 0x47, 0x45, 0x99, 0x1d, 0xca, 0xfc, 0x6c, 0xf3,
	0xb6, 0xf4, 0x3c, 0x29, 0x76, 0xa8, 0x4e, 0xea, 0x73, 0x22, 0x94, 0xa1, 0xe0, 0x99, 0xd2, 0x3b,
	0x7c, 0x69, 0xcf, 0xa9, 0x51, 0xda, 0x21, 0xf3, 0x65, 0xb5, 0x64, 0x4f, 0xad, 0xa3, 0x46, 0xe9,
	0x37, 0xb0, 0x5c, 0xb3, 0x48, 0x0f, 0x9b, 0x1a, 0xb5, 0x84, 0xc3, 0x57, 0x00, 0xfb, 0x5b, 0x27,
	0x7d, 0xe8, 0x7c, 0xbe, 0x5f, 0xdc, 0x2d, 0x26, 0xf3, 0x6b, 0x7f, 0x7e, 0x33, 0x38, 0x22, 0x1d,
	0x68, 0x4d, 0x3f, 0xcd, 0x26, 0xc1, 0xec, 0x7a, 0xe0, 0x0c, 0xdf, 0xc3, 0xf9, 0x3f, 0xd7, 0x4d,
	0x06, 0x70, 0xfc, 0x80, 0x5b, 0xf3, 0xb4, 0xda, 0x81, 0xfe, 0xab, 0xaf, 0x68, 0xc3, 0xd6, 0x39,
	0x16, 0x4f, 0xca, 0x82, 0x8f, 0x6f, 0x7e, 0xec, 0x5c, 0xe7, 0xe7, 0xce, 0x75, 0x7e, 0xef, 0x5c,
	0xe7, 0xfb, 0x1f, 0xf7, 0x08, 0x5e, 0x84, 0x69, 0x3c, 0x16, 0x79, 0xf8, 0x90, 0xcb, 0xaf, 0x5c,
	0xe0, 0x1a, 0xa5, 0x1c, 0xcb, 0x70, 0x65, 0x17, 0x6b, 0x99, 0x7f, 0x19, 0xcb, 0x90, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x07, 0x4c, 0x47, 0xff, 0xe7, 0x03, 0x00, 0x00,
}

func (m *AlarmMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AlarmMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AlarmMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.BladeId != nil {
		i -= len(*m.BladeId)
		copy(dAtA[i:], *m.BladeId)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.BladeId)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if m.SubCategory != nil {
		i -= len(*m.SubCategory)
		copy(dAtA[i:], *m.SubCategory)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.SubCategory)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if m.Description != nil {
		i -= len(*m.Description)
		copy(dAtA[i:], *m.Description)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.Description)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb2
	}
	if m.ApIpv6Address != nil {
		i -= len(*m.ApIpv6Address)
		copy(dAtA[i:], *m.ApIpv6Address)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ApIpv6Address)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.ApIpAddress != nil {
		i -= len(*m.ApIpAddress)
		copy(dAtA[i:], *m.ApIpAddress)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ApIpAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.ApGroupName != nil {
		i -= len(*m.ApGroupName)
		copy(dAtA[i:], *m.ApGroupName)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ApGroupName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.ZoneName != nil {
		i -= len(*m.ZoneName)
		copy(dAtA[i:], *m.ZoneName)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ZoneName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.DomainName != nil {
		i -= len(*m.DomainName)
		copy(dAtA[i:], *m.DomainName)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.DomainName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.Reason != nil {
		i -= len(*m.Reason)
		copy(dAtA[i:], *m.Reason)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.Reason)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.ClientMac != nil {
		i -= len(*m.ClientMac)
		copy(dAtA[i:], *m.ClientMac)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ClientMac)))
		i--
		dAtA[i] = 0x7a
	}
	if m.ApMac != nil {
		i -= len(*m.ApMac)
		copy(dAtA[i:], *m.ApMac)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ApMac)))
		i--
		dAtA[i] = 0x72
	}
	if m.ApGroupId != nil {
		i -= len(*m.ApGroupId)
		copy(dAtA[i:], *m.ApGroupId)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ApGroupId)))
		i--
		dAtA[i] = 0x6a
	}
	if m.ZoneId != nil {
		i -= len(*m.ZoneId)
		copy(dAtA[i:], *m.ZoneId)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.ZoneId)))
		i--
		dAtA[i] = 0x62
	}
	if m.DomainId != nil {
		i -= len(*m.DomainId)
		copy(dAtA[i:], *m.DomainId)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.DomainId)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Attributes) > 0 {
		for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSciAlarm(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.AlarmState != nil {
		i = encodeVarintSciAlarm(dAtA, i, uint64(*m.AlarmState))
		i--
		dAtA[i] = 0x48
	}
	if m.Timestamp != nil {
		i = encodeVarintSciAlarm(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.InitEventCode != nil {
		i = encodeVarintSciAlarm(dAtA, i, uint64(*m.InitEventCode))
		i--
		dAtA[i] = 0x38
	}
	if m.AlarmType != nil {
		i -= len(*m.AlarmType)
		copy(dAtA[i:], *m.AlarmType)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.AlarmType)))
		i--
		dAtA[i] = 0x32
	}
	if m.MainCategory != nil {
		i -= len(*m.MainCategory)
		copy(dAtA[i:], *m.MainCategory)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.MainCategory)))
		i--
		dAtA[i] = 0x2a
	}
	if m.AlarmSeverity != nil {
		i -= len(*m.AlarmSeverity)
		copy(dAtA[i:], *m.AlarmSeverity)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.AlarmSeverity)))
		i--
		dAtA[i] = 0x22
	}
	if m.AlarmCode != nil {
		i = encodeVarintSciAlarm(dAtA, i, uint64(*m.AlarmCode))
		i--
		dAtA[i] = 0x18
	}
	if m.AlarmUuid != nil {
		i -= len(*m.AlarmUuid)
		copy(dAtA[i:], *m.AlarmUuid)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.AlarmUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Version != nil {
		i = encodeVarintSciAlarm(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AlarmMessageEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AlarmMessageEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AlarmMessageEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Value != nil {
		i -= len(*m.Value)
		copy(dAtA[i:], *m.Value)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if m.Key != nil {
		i -= len(*m.Key)
		copy(dAtA[i:], *m.Key)
		i = encodeVarintSciAlarm(dAtA, i, uint64(len(*m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSciAlarm(dAtA []byte, offset int, v uint64) int {
	offset -= sovSciAlarm(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AlarmMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		n += 1 + sovSciAlarm(uint64(*m.Version))
	}
	if m.AlarmUuid != nil {
		l = len(*m.AlarmUuid)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.AlarmCode != nil {
		n += 1 + sovSciAlarm(uint64(*m.AlarmCode))
	}
	if m.AlarmSeverity != nil {
		l = len(*m.AlarmSeverity)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.MainCategory != nil {
		l = len(*m.MainCategory)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.AlarmType != nil {
		l = len(*m.AlarmType)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.InitEventCode != nil {
		n += 1 + sovSciAlarm(uint64(*m.InitEventCode))
	}
	if m.Timestamp != nil {
		n += 1 + sovSciAlarm(uint64(*m.Timestamp))
	}
	if m.AlarmState != nil {
		n += 1 + sovSciAlarm(uint64(*m.AlarmState))
	}
	if len(m.Attributes) > 0 {
		for _, e := range m.Attributes {
			l = e.Size()
			n += 1 + l + sovSciAlarm(uint64(l))
		}
	}
	if m.DomainId != nil {
		l = len(*m.DomainId)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.ZoneId != nil {
		l = len(*m.ZoneId)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.ApGroupId != nil {
		l = len(*m.ApGroupId)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.ApMac != nil {
		l = len(*m.ApMac)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.ClientMac != nil {
		l = len(*m.ClientMac)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.Reason != nil {
		l = len(*m.Reason)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.DomainName != nil {
		l = len(*m.DomainName)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.ZoneName != nil {
		l = len(*m.ZoneName)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.ApGroupName != nil {
		l = len(*m.ApGroupName)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.ApIpAddress != nil {
		l = len(*m.ApIpAddress)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.ApIpv6Address != nil {
		l = len(*m.ApIpv6Address)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.Description != nil {
		l = len(*m.Description)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.SubCategory != nil {
		l = len(*m.SubCategory)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.BladeId != nil {
		l = len(*m.BladeId)
		n += 2 + l + sovSciAlarm(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AlarmMessageEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Key != nil {
		l = len(*m.Key)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.Value != nil {
		l = len(*m.Value)
		n += 1 + l + sovSciAlarm(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSciAlarm(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSciAlarm(x uint64) (n int) {
	return sovSciAlarm(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AlarmMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciAlarm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AlarmMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AlarmMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AlarmUuid = &s
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmCode", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AlarmCode = &v
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmSeverity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AlarmSeverity = &s
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainCategory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MainCategory = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.AlarmType = &s
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitEventCode", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InitEventCode = &v
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlarmState", wireType)
			}
			var v AlarmMessage_AlarmState
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= AlarmMessage_AlarmState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AlarmState = &v
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, &AlarmMessageEntry{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainId = &s
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneId = &s
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApGroupId = &s
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApMac = &s
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClientMac = &s
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Reason = &s
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainName = &s
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneName = &s
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApGroupName = &s
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApIpAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApIpAddress = &s
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApIpv6Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApIpv6Address = &s
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Description = &s
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubCategory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SubCategory = &s
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BladeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.BladeId = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciAlarm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AlarmMessageEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciAlarm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AlarmMessageEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AlarmMessageEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Key = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciAlarm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Value = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciAlarm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciAlarm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSciAlarm(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSciAlarm
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSciAlarm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSciAlarm
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSciAlarm
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSciAlarm
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSciAlarm        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSciAlarm          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSciAlarm = fmt.Errorf("proto: unexpected end of group")
)
