// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sci-event.proto

package proto

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventMessage struct {
	Version              *uint32         `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	EventCode            *uint32         `protobuf:"varint,2,opt,name=eventCode" json:"eventCode,omitempty"`
	EventType            *string         `protobuf:"bytes,3,opt,name=eventType" json:"eventType,omitempty"`
	MainCategory         *string         `protobuf:"bytes,4,opt,name=mainCategory" json:"mainCategory,omitempty"`
	SubCategory          *string         `protobuf:"bytes,5,opt,name=subCategory" json:"subCategory,omitempty"`
	DomainId             *string         `protobuf:"bytes,6,opt,name=domainId" json:"domainId,omitempty"`
	ZoneId               *string         `protobuf:"bytes,7,opt,name=zoneId" json:"zoneId,omitempty"`
	ApGroupId            *string         `protobuf:"bytes,8,opt,name=apGroupId" json:"apGroupId,omitempty"`
	ApMac                *string         `protobuf:"bytes,9,opt,name=apMac" json:"apMac,omitempty"`
	ClientMac            *string         `protobuf:"bytes,10,opt,name=clientMac" json:"clientMac,omitempty"`
	Timestamp            *uint64         `protobuf:"varint,11,opt,name=timestamp" json:"timestamp,omitempty"`
	Attributes           []*MessageEntry `protobuf:"bytes,12,rep,name=attributes" json:"attributes,omitempty"`
	Severity             *string         `protobuf:"bytes,13,opt,name=severity" json:"severity,omitempty"`
	Reason               *string         `protobuf:"bytes,14,opt,name=reason" json:"reason,omitempty"`
	DomainName           *string         `protobuf:"bytes,15,opt,name=domainName" json:"domainName,omitempty"`
	ZoneName             *string         `protobuf:"bytes,16,opt,name=zoneName" json:"zoneName,omitempty"`
	ApGroupName          *string         `protobuf:"bytes,17,opt,name=apGroupName" json:"apGroupName,omitempty"`
	ApIpAddress          *string         `protobuf:"bytes,18,opt,name=apIpAddress" json:"apIpAddress,omitempty"`
	ApIpv6Address        *string         `protobuf:"bytes,19,opt,name=apIpv6Address" json:"apIpv6Address,omitempty"`
	Description          *string         `protobuf:"bytes,20,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EventMessage) Reset()         { *m = EventMessage{} }
func (m *EventMessage) String() string { return proto.CompactTextString(m) }
func (*EventMessage) ProtoMessage()    {}
func (*EventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_14f390539c919996, []int{0}
}
func (m *EventMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMessage.Merge(m, src)
}
func (m *EventMessage) XXX_Size() int {
	return m.Size()
}
func (m *EventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EventMessage proto.InternalMessageInfo

func (m *EventMessage) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *EventMessage) GetEventCode() uint32 {
	if m != nil && m.EventCode != nil {
		return *m.EventCode
	}
	return 0
}

func (m *EventMessage) GetEventType() string {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return ""
}

func (m *EventMessage) GetMainCategory() string {
	if m != nil && m.MainCategory != nil {
		return *m.MainCategory
	}
	return ""
}

func (m *EventMessage) GetSubCategory() string {
	if m != nil && m.SubCategory != nil {
		return *m.SubCategory
	}
	return ""
}

func (m *EventMessage) GetDomainId() string {
	if m != nil && m.DomainId != nil {
		return *m.DomainId
	}
	return ""
}

func (m *EventMessage) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *EventMessage) GetApGroupId() string {
	if m != nil && m.ApGroupId != nil {
		return *m.ApGroupId
	}
	return ""
}

func (m *EventMessage) GetApMac() string {
	if m != nil && m.ApMac != nil {
		return *m.ApMac
	}
	return ""
}

func (m *EventMessage) GetClientMac() string {
	if m != nil && m.ClientMac != nil {
		return *m.ClientMac
	}
	return ""
}

func (m *EventMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *EventMessage) GetAttributes() []*MessageEntry {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *EventMessage) GetSeverity() string {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return ""
}

func (m *EventMessage) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *EventMessage) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *EventMessage) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *EventMessage) GetApGroupName() string {
	if m != nil && m.ApGroupName != nil {
		return *m.ApGroupName
	}
	return ""
}

func (m *EventMessage) GetApIpAddress() string {
	if m != nil && m.ApIpAddress != nil {
		return *m.ApIpAddress
	}
	return ""
}

func (m *EventMessage) GetApIpv6Address() string {
	if m != nil && m.ApIpv6Address != nil {
		return *m.ApIpv6Address
	}
	return ""
}

func (m *EventMessage) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type MessageEntry struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageEntry) Reset()         { *m = MessageEntry{} }
func (m *MessageEntry) String() string { return proto.CompactTextString(m) }
func (*MessageEntry) ProtoMessage()    {}
func (*MessageEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_14f390539c919996, []int{1}
}
func (m *MessageEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessageEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MessageEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEntry.Merge(m, src)
}
func (m *MessageEntry) XXX_Size() int {
	return m.Size()
}
func (m *MessageEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEntry proto.InternalMessageInfo

func (m *MessageEntry) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *MessageEntry) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*EventMessage)(nil), "proto.EventMessage")
	proto.RegisterType((*MessageEntry)(nil), "proto.MessageEntry")
}

func init() { proto.RegisterFile("sci-event.proto", fileDescriptor_14f390539c919996) }

var fileDescriptor_14f390539c919996 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0x93, 0xb4, 0xcd, 0x24, 0xa1, 0x61, 0x5b, 0xa1, 0x11, 0x42, 0x96, 0x15, 0x71,
	0xf0, 0x85, 0x1e, 0x40, 0xea, 0x1d, 0xaa, 0x0a, 0xe5, 0x50, 0x0e, 0x16, 0x2f, 0xb0, 0xb5, 0x47,
	0xd5, 0x8a, 0xc6, 0xbb, 0xda, 0x5d, 0x5b, 0x32, 0x4f, 0xc2, 0x23, 0x71, 0xe4, 0x11, 0x50, 0x78,
	0x10, 0xd0, 0xec, 0xc6, 0x8e, 0x7b, 0x4a, 0xfe, 0xef, 0xff, 0x77, 0xb4, 0xf3, 0x7b, 0xe1, 0xc2,
	0x95, 0xea, 0x3d, 0xb5, 0x54, 0xfb, 0x6b, 0x63, 0xb5, 0xd7, 0x62, 0x16, 0x7e, 0x36, 0xff, 0xa6,
	0xb0, 0xbc, 0x63, 0x7c, 0x4f, 0xce, 0xc9, 0x47, 0x12, 0x08, 0x67, 0x2d, 0x59, 0xa7, 0x74, 0x8d,
	0x49, 0x76, 0x92, 0xaf, 0x8a, 0x5e, 0x8a, 0xb7, 0x30, 0x0f, 0x03, 0x6e, 0x75, 0x45, 0x78, 0x92,
	0x25, 0xf9, 0xaa, 0x38, 0x82, 0xc1, 0xfd, 0xd6, 0x19, 0xc2, 0x49, 0x96, 0xe4, 0xf3, 0xe2, 0x08,
	0xc4, 0x06, 0x96, 0x3b, 0xa9, 0xea, 0x5b, 0xe9, 0xe9, 0x51, 0xdb, 0x0e, 0xa7, 0x21, 0xf0, 0x8c,
	0x89, 0x0c, 0x16, 0xae, 0x79, 0x18, 0x22, 0xb3, 0x10, 0x19, 0x23, 0xf1, 0x06, 0xce, 0x2b, 0xcd,
	0x67, 0xb6, 0x15, 0x9e, 0x06, 0x7b, 0xd0, 0xe2, 0x35, 0x9c, 0xfe, 0xd0, 0x35, 0x6d, 0x2b, 0x3c,
	0x0b, 0xce, 0x41, 0xf1, 0xbd, 0xa4, 0xf9, 0x62, 0x75, 0x63, 0xb6, 0x15, 0x9e, 0xc7, 0x7b, 0x0d,
	0x40, 0x5c, 0xc1, 0x4c, 0x9a, 0x7b, 0x59, 0xe2, 0x3c, 0x38, 0x51, 0xf0, 0x99, 0xf2, 0x49, 0x71,
	0x29, 0xb2, 0x44, 0x88, 0x67, 0x06, 0xc0, 0xae, 0x57, 0x3b, 0x72, 0x5e, 0xee, 0x0c, 0x2e, 0xb2,
	0x24, 0x9f, 0x16, 0x47, 0x20, 0x3e, 0x02, 0x48, 0xef, 0xad, 0x7a, 0x68, 0x3c, 0x39, 0x5c, 0x66,
	0x93, 0x7c, 0xf1, 0xe1, 0x32, 0x76, 0x7e, 0x7d, 0xe8, 0xf8, 0xae, 0xf6, 0xb6, 0x2b, 0x46, 0x31,
	0x5e, 0xcc, 0x51, 0x4b, 0x56, 0xf9, 0x0e, 0x57, 0x71, 0xb1, 0x5e, 0xf3, 0x62, 0x96, 0xa4, 0xd3,
	0x35, 0xbe, 0x8c, 0x8b, 0x45, 0x25, 0x52, 0x80, 0xb8, 0xfc, 0x57, 0xb9, 0x23, 0xbc, 0x08, 0xde,
	0x88, 0xf0, 0x4c, 0xae, 0x20, 0xb8, 0xeb, 0x38, 0xb3, 0xd7, 0x5c, 0xf5, 0xa1, 0x83, 0x60, 0xbf,
	0x8a, 0x55, 0x8f, 0x50, 0x4c, 0x6c, 0xcd, 0xa7, 0xaa, 0xb2, 0xe4, 0x1c, 0x8a, 0x3e, 0x31, 0x20,
	0xf1, 0x0e, 0x56, 0x2c, 0xdb, 0x9b, 0x3e, 0x73, 0x19, 0x32, 0xcf, 0x21, 0xcf, 0xa9, 0xc8, 0x95,
	0x56, 0x19, 0xcf, 0x4f, 0xea, 0x2a, 0xce, 0x19, 0xa1, 0xcd, 0x0d, 0x2c, 0xc7, 0xbd, 0x88, 0x35,
	0x4c, 0xbe, 0x53, 0x87, 0x49, 0x48, 0xf2, 0x5f, 0xfe, 0x48, 0xad, 0x7c, 0x6a, 0xe2, 0xa3, 0x9b,
	0x17, 0x51, 0x7c, 0x5e, 0xff, 0xda, 0xa7, 0xc9, 0xef, 0x7d, 0x9a, 0xfc, 0xd9, 0xa7, 0xc9, 0xcf,
	0xbf, 0xe9, 0x8b, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xef, 0x9c, 0xe8, 0x9f, 0xe4, 0x02, 0x00,
	0x00,
}

func (m *EventMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Description != nil {
		i -= len(*m.Description)
		copy(dAtA[i:], *m.Description)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.Description)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.ApIpv6Address != nil {
		i -= len(*m.ApIpv6Address)
		copy(dAtA[i:], *m.ApIpv6Address)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ApIpv6Address)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.ApIpAddress != nil {
		i -= len(*m.ApIpAddress)
		copy(dAtA[i:], *m.ApIpAddress)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ApIpAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.ApGroupName != nil {
		i -= len(*m.ApGroupName)
		copy(dAtA[i:], *m.ApGroupName)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ApGroupName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.ZoneName != nil {
		i -= len(*m.ZoneName)
		copy(dAtA[i:], *m.ZoneName)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ZoneName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.DomainName != nil {
		i -= len(*m.DomainName)
		copy(dAtA[i:], *m.DomainName)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.DomainName)))
		i--
		dAtA[i] = 0x7a
	}
	if m.Reason != nil {
		i -= len(*m.Reason)
		copy(dAtA[i:], *m.Reason)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.Reason)))
		i--
		dAtA[i] = 0x72
	}
	if m.Severity != nil {
		i -= len(*m.Severity)
		copy(dAtA[i:], *m.Severity)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.Severity)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Attributes) > 0 {
		for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSciEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.Timestamp != nil {
		i = encodeVarintSciEvent(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x58
	}
	if m.ClientMac != nil {
		i -= len(*m.ClientMac)
		copy(dAtA[i:], *m.ClientMac)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ClientMac)))
		i--
		dAtA[i] = 0x52
	}
	if m.ApMac != nil {
		i -= len(*m.ApMac)
		copy(dAtA[i:], *m.ApMac)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ApMac)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ApGroupId != nil {
		i -= len(*m.ApGroupId)
		copy(dAtA[i:], *m.ApGroupId)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ApGroupId)))
		i--
		dAtA[i] = 0x42
	}
	if m.ZoneId != nil {
		i -= len(*m.ZoneId)
		copy(dAtA[i:], *m.ZoneId)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.ZoneId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.DomainId != nil {
		i -= len(*m.DomainId)
		copy(dAtA[i:], *m.DomainId)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.DomainId)))
		i--
		dAtA[i] = 0x32
	}
	if m.SubCategory != nil {
		i -= len(*m.SubCategory)
		copy(dAtA[i:], *m.SubCategory)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.SubCategory)))
		i--
		dAtA[i] = 0x2a
	}
	if m.MainCategory != nil {
		i -= len(*m.MainCategory)
		copy(dAtA[i:], *m.MainCategory)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.MainCategory)))
		i--
		dAtA[i] = 0x22
	}
	if m.EventType != nil {
		i -= len(*m.EventType)
		copy(dAtA[i:], *m.EventType)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.EventType)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EventCode != nil {
		i = encodeVarintSciEvent(dAtA, i, uint64(*m.EventCode))
		i--
		dAtA[i] = 0x10
	}
	if m.Version == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintSciEvent(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MessageEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Value != nil {
		i -= len(*m.Value)
		copy(dAtA[i:], *m.Value)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if m.Key != nil {
		i -= len(*m.Key)
		copy(dAtA[i:], *m.Key)
		i = encodeVarintSciEvent(dAtA, i, uint64(len(*m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSciEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovSciEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		n += 1 + sovSciEvent(uint64(*m.Version))
	}
	if m.EventCode != nil {
		n += 1 + sovSciEvent(uint64(*m.EventCode))
	}
	if m.EventType != nil {
		l = len(*m.EventType)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.MainCategory != nil {
		l = len(*m.MainCategory)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.SubCategory != nil {
		l = len(*m.SubCategory)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.DomainId != nil {
		l = len(*m.DomainId)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.ZoneId != nil {
		l = len(*m.ZoneId)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.ApGroupId != nil {
		l = len(*m.ApGroupId)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.ApMac != nil {
		l = len(*m.ApMac)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.ClientMac != nil {
		l = len(*m.ClientMac)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.Timestamp != nil {
		n += 1 + sovSciEvent(uint64(*m.Timestamp))
	}
	if len(m.Attributes) > 0 {
		for _, e := range m.Attributes {
			l = e.Size()
			n += 1 + l + sovSciEvent(uint64(l))
		}
	}
	if m.Severity != nil {
		l = len(*m.Severity)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.Reason != nil {
		l = len(*m.Reason)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.DomainName != nil {
		l = len(*m.DomainName)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.ZoneName != nil {
		l = len(*m.ZoneName)
		n += 2 + l + sovSciEvent(uint64(l))
	}
	if m.ApGroupName != nil {
		l = len(*m.ApGroupName)
		n += 2 + l + sovSciEvent(uint64(l))
	}
	if m.ApIpAddress != nil {
		l = len(*m.ApIpAddress)
		n += 2 + l + sovSciEvent(uint64(l))
	}
	if m.ApIpv6Address != nil {
		l = len(*m.ApIpv6Address)
		n += 2 + l + sovSciEvent(uint64(l))
	}
	if m.Description != nil {
		l = len(*m.Description)
		n += 2 + l + sovSciEvent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MessageEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Key != nil {
		l = len(*m.Key)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.Value != nil {
		l = len(*m.Value)
		n += 1 + l + sovSciEvent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSciEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSciEvent(x uint64) (n int) {
	return sovSciEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventMessage) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventCode", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EventCode = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.EventType = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainCategory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.MainCategory = &s
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubCategory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SubCategory = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainId = &s
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneId = &s
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApGroupId = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApMac = &s
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientMac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClientMac = &s
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, &MessageEntry{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Severity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Severity = &s
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Reason = &s
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainName = &s
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneName = &s
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApGroupName = &s
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApIpAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApIpAddress = &s
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApIpv6Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApIpv6Address = &s
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Description = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciEvent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessageEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessageEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessageEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Key = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Value = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciEvent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSciEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSciEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSciEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSciEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSciEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSciEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSciEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSciEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSciEvent = fmt.Errorf("proto: unexpected end of group")
)
