// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sci-configuration.proto

package proto

import (
	fmt "fmt"
	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigurationMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description GPB version
	// @since 3.5
	Version *uint32 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	//*
	// @property
	// @aggregation
	// @description
	// @since 3.5
	ClusterInfo *ClusterMessage `protobuf:"bytes,2,opt,name=clusterInfo" json:"clusterInfo,omitempty"`
	//*
	// @property
	// @aggregation
	// @description
	// @since 3.5
	Timestamp            *uint64  `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigurationMessage) Reset()         { *m = ConfigurationMessage{} }
func (m *ConfigurationMessage) String() string { return proto.CompactTextString(m) }
func (*ConfigurationMessage) ProtoMessage()    {}
func (*ConfigurationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_651f73f9ae065d0c, []int{0}
}
func (m *ConfigurationMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigurationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigurationMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigurationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationMessage.Merge(m, src)
}
func (m *ConfigurationMessage) XXX_Size() int {
	return m.Size()
}
func (m *ConfigurationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationMessage proto.InternalMessageInfo

func (m *ConfigurationMessage) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ConfigurationMessage) GetClusterInfo() *ClusterMessage {
	if m != nil {
		return m.ClusterInfo
	}
	return nil
}

func (m *ConfigurationMessage) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ClusterMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Cluster UUID
	// @since 3.5
	ClusterUuid *string `protobuf:"bytes,1,opt,name=clusterUuid" json:"clusterUuid,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Cluster name
	// @since 3.5
	ClusterName *string `protobuf:"bytes,2,opt,name=clusterName" json:"clusterName,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of control node information
	// @since 3.5
	ControlBlades *string `protobuf:"bytes,3,opt,name=controlBlades" json:"controlBlades,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of system resource utilization
	// @since 3.5
	ControllerUtilizations *string `protobuf:"bytes,4,opt,name=controllerUtilizations" json:"controllerUtilizations,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of system summary
	// @since 3.5
	SystemSummary *string `protobuf:"bytes,5,opt,name=systemSummary" json:"systemSummary,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of domain list
	// @since 3.5
	Domains *string `protobuf:"bytes,100,opt,name=domains" json:"domains,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of zone list
	// @since 3.5
	Zones *string `protobuf:"bytes,101,opt,name=zones" json:"zones,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of AP group list
	// @since 3.5
	ApGroups *string `protobuf:"bytes,102,opt,name=apGroups" json:"apGroups,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of wlan group list
	// @since 3.5
	WlanGroups *string `protobuf:"bytes,103,opt,name=wlanGroups" json:"wlanGroups,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of WLAN list
	// @since 3.5
	Wlans *string `protobuf:"bytes,104,opt,name=wlans" json:"wlans,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description JSON string of AP list
	// @since 3.5
	Aps *string `protobuf:"bytes,105,opt,name=aps" json:"aps,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description System Hierarchy [Group Tree]
	// @since 3.5
	TenantInfos          []*TenantMessage `protobuf:"bytes,200,rep,name=tenantInfos" json:"tenantInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClusterMessage) Reset()         { *m = ClusterMessage{} }
func (m *ClusterMessage) String() string { return proto.CompactTextString(m) }
func (*ClusterMessage) ProtoMessage()    {}
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_651f73f9ae065d0c, []int{1}
}
func (m *ClusterMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClusterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMessage.Merge(m, src)
}
func (m *ClusterMessage) XXX_Size() int {
	return m.Size()
}
func (m *ClusterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMessage proto.InternalMessageInfo

func (m *ClusterMessage) GetClusterUuid() string {
	if m != nil && m.ClusterUuid != nil {
		return *m.ClusterUuid
	}
	return ""
}

func (m *ClusterMessage) GetClusterName() string {
	if m != nil && m.ClusterName != nil {
		return *m.ClusterName
	}
	return ""
}

func (m *ClusterMessage) GetControlBlades() string {
	if m != nil && m.ControlBlades != nil {
		return *m.ControlBlades
	}
	return ""
}

func (m *ClusterMessage) GetControllerUtilizations() string {
	if m != nil && m.ControllerUtilizations != nil {
		return *m.ControllerUtilizations
	}
	return ""
}

func (m *ClusterMessage) GetSystemSummary() string {
	if m != nil && m.SystemSummary != nil {
		return *m.SystemSummary
	}
	return ""
}

func (m *ClusterMessage) GetDomains() string {
	if m != nil && m.Domains != nil {
		return *m.Domains
	}
	return ""
}

func (m *ClusterMessage) GetZones() string {
	if m != nil && m.Zones != nil {
		return *m.Zones
	}
	return ""
}

func (m *ClusterMessage) GetApGroups() string {
	if m != nil && m.ApGroups != nil {
		return *m.ApGroups
	}
	return ""
}

func (m *ClusterMessage) GetWlanGroups() string {
	if m != nil && m.WlanGroups != nil {
		return *m.WlanGroups
	}
	return ""
}

func (m *ClusterMessage) GetWlans() string {
	if m != nil && m.Wlans != nil {
		return *m.Wlans
	}
	return ""
}

func (m *ClusterMessage) GetAps() string {
	if m != nil && m.Aps != nil {
		return *m.Aps
	}
	return ""
}

func (m *ClusterMessage) GetTenantInfos() []*TenantMessage {
	if m != nil {
		return m.TenantInfos
	}
	return nil
}

type TenantMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Tenant UUID
	// @since 3.5
	TenantId *string `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Tenant name
	// @since 3.5
	TenantName *string `protobuf:"bytes,2,opt,name=tenantName" json:"tenantName,omitempty"`
	//*
	// @property
	// @aggregation
	// @description
	// @since 3.5
	AdminDomain          *DomainMessage `protobuf:"bytes,3,opt,name=adminDomain" json:"adminDomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TenantMessage) Reset()         { *m = TenantMessage{} }
func (m *TenantMessage) String() string { return proto.CompactTextString(m) }
func (*TenantMessage) ProtoMessage()    {}
func (*TenantMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_651f73f9ae065d0c, []int{2}
}
func (m *TenantMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TenantMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TenantMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TenantMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantMessage.Merge(m, src)
}
func (m *TenantMessage) XXX_Size() int {
	return m.Size()
}
func (m *TenantMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TenantMessage proto.InternalMessageInfo

func (m *TenantMessage) GetTenantId() string {
	if m != nil && m.TenantId != nil {
		return *m.TenantId
	}
	return ""
}

func (m *TenantMessage) GetTenantName() string {
	if m != nil && m.TenantName != nil {
		return *m.TenantName
	}
	return ""
}

func (m *TenantMessage) GetAdminDomain() *DomainMessage {
	if m != nil {
		return m.AdminDomain
	}
	return nil
}

type DomainMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain UUID
	// @since 3.5
	DomainId *string `protobuf:"bytes,1,opt,name=domainId" json:"domainId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Domain name
	// @since 3.5
	DomainName *string `protobuf:"bytes,2,opt,name=domainName" json:"domainName,omitempty"`
	//*
	// @property
	// @aggregation
	// @description
	// @since 3.5
	ZoneInfos []*ZoneMessage `protobuf:"bytes,3,rep,name=zoneInfos" json:"zoneInfos,omitempty"`
	//*
	// @property
	// @aggregation
	// @description
	// @since 3.5
	SubDomainInfos       []*DomainMessage `protobuf:"bytes,4,rep,name=subDomainInfos" json:"subDomainInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DomainMessage) Reset()         { *m = DomainMessage{} }
func (m *DomainMessage) String() string { return proto.CompactTextString(m) }
func (*DomainMessage) ProtoMessage()    {}
func (*DomainMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_651f73f9ae065d0c, []int{3}
}
func (m *DomainMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainMessage.Merge(m, src)
}
func (m *DomainMessage) XXX_Size() int {
	return m.Size()
}
func (m *DomainMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DomainMessage proto.InternalMessageInfo

func (m *DomainMessage) GetDomainId() string {
	if m != nil && m.DomainId != nil {
		return *m.DomainId
	}
	return ""
}

func (m *DomainMessage) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *DomainMessage) GetZoneInfos() []*ZoneMessage {
	if m != nil {
		return m.ZoneInfos
	}
	return nil
}

func (m *DomainMessage) GetSubDomainInfos() []*DomainMessage {
	if m != nil {
		return m.SubDomainInfos
	}
	return nil
}

type ZoneMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone UUID
	// @since 3.5
	ZoneId *string `protobuf:"bytes,1,opt,name=zoneId" json:"zoneId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description Zone name
	// @since 3.5
	ZoneName *string `protobuf:"bytes,2,opt,name=zoneName" json:"zoneName,omitempty"`
	//*
	// @property
	// @aggregation
	// @description
	// @since 3.5
	ApGroupInfos []*ApGroupMessage `protobuf:"bytes,3,rep,name=apGroupInfos" json:"apGroupInfos,omitempty"`
	//*
	// @property
	// @aggregation
	// @description
	// @since 3.5
	WlanGroupInfos       []*WlanGroupMessage `protobuf:"bytes,4,rep,name=wlanGroupInfos" json:"wlanGroupInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ZoneMessage) Reset()         { *m = ZoneMessage{} }
func (m *ZoneMessage) String() string { return proto.CompactTextString(m) }
func (*ZoneMessage) ProtoMessage()    {}
func (*ZoneMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_651f73f9ae065d0c, []int{4}
}
func (m *ZoneMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ZoneMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ZoneMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ZoneMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneMessage.Merge(m, src)
}
func (m *ZoneMessage) XXX_Size() int {
	return m.Size()
}
func (m *ZoneMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneMessage proto.InternalMessageInfo

func (m *ZoneMessage) GetZoneId() string {
	if m != nil && m.ZoneId != nil {
		return *m.ZoneId
	}
	return ""
}

func (m *ZoneMessage) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *ZoneMessage) GetApGroupInfos() []*ApGroupMessage {
	if m != nil {
		return m.ApGroupInfos
	}
	return nil
}

func (m *ZoneMessage) GetWlanGroupInfos() []*WlanGroupMessage {
	if m != nil {
		return m.WlanGroupInfos
	}
	return nil
}

type ApGroupMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP Group UUID
	// @since 3.5
	ApGroupId *string `protobuf:"bytes,1,opt,name=apGroupId" json:"apGroupId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description AP Group name
	// @since 3.5
	ApGroupName          *string  `protobuf:"bytes,2,opt,name=apGroupName" json:"apGroupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApGroupMessage) Reset()         { *m = ApGroupMessage{} }
func (m *ApGroupMessage) String() string { return proto.CompactTextString(m) }
func (*ApGroupMessage) ProtoMessage()    {}
func (*ApGroupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_651f73f9ae065d0c, []int{5}
}
func (m *ApGroupMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApGroupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApGroupMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApGroupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApGroupMessage.Merge(m, src)
}
func (m *ApGroupMessage) XXX_Size() int {
	return m.Size()
}
func (m *ApGroupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApGroupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApGroupMessage proto.InternalMessageInfo

func (m *ApGroupMessage) GetApGroupId() string {
	if m != nil && m.ApGroupId != nil {
		return *m.ApGroupId
	}
	return ""
}

func (m *ApGroupMessage) GetApGroupName() string {
	if m != nil && m.ApGroupName != nil {
		return *m.ApGroupName
	}
	return ""
}

type WlanGroupMessage struct {
	//*
	// @property snapshot
	// @aggregation NULL
	// @description WLAN Group UUID
	// @since 3.5
	WlanGroupId *string `protobuf:"bytes,1,opt,name=wlanGroupId" json:"wlanGroupId,omitempty"`
	//*
	// @property snapshot
	// @aggregation NULL
	// @description WLAN Group name
	// @since 3.5
	WlanGroupName        *string  `protobuf:"bytes,2,opt,name=wlanGroupName" json:"wlanGroupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WlanGroupMessage) Reset()         { *m = WlanGroupMessage{} }
func (m *WlanGroupMessage) String() string { return proto.CompactTextString(m) }
func (*WlanGroupMessage) ProtoMessage()    {}
func (*WlanGroupMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_651f73f9ae065d0c, []int{6}
}
func (m *WlanGroupMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WlanGroupMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WlanGroupMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WlanGroupMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WlanGroupMessage.Merge(m, src)
}
func (m *WlanGroupMessage) XXX_Size() int {
	return m.Size()
}
func (m *WlanGroupMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WlanGroupMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WlanGroupMessage proto.InternalMessageInfo

func (m *WlanGroupMessage) GetWlanGroupId() string {
	if m != nil && m.WlanGroupId != nil {
		return *m.WlanGroupId
	}
	return ""
}

func (m *WlanGroupMessage) GetWlanGroupName() string {
	if m != nil && m.WlanGroupName != nil {
		return *m.WlanGroupName
	}
	return ""
}

func init() {
	proto.RegisterType((*ConfigurationMessage)(nil), "proto.ConfigurationMessage")
	proto.RegisterType((*ClusterMessage)(nil), "proto.ClusterMessage")
	proto.RegisterType((*TenantMessage)(nil), "proto.TenantMessage")
	proto.RegisterType((*DomainMessage)(nil), "proto.DomainMessage")
	proto.RegisterType((*ZoneMessage)(nil), "proto.ZoneMessage")
	proto.RegisterType((*ApGroupMessage)(nil), "proto.ApGroupMessage")
	proto.RegisterType((*WlanGroupMessage)(nil), "proto.WlanGroupMessage")
}

func init() { proto.RegisterFile("sci-configuration.proto", fileDescriptor_651f73f9ae065d0c) }

var fileDescriptor_651f73f9ae065d0c = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xd1, 0x6a, 0x14, 0x3d,
	0x14, 0xfe, 0xd3, 0x6d, 0x7f, 0xdd, 0xb3, 0xee, 0x52, 0xc2, 0xda, 0x06, 0x91, 0x65, 0x18, 0xbd,
	0xd8, 0x1b, 0x17, 0x29, 0x58, 0x11, 0x04, 0xb1, 0x15, 0xc4, 0x0b, 0x45, 0x56, 0x8b, 0xd0, 0xbb,
	0x74, 0x36, 0xbb, 0x06, 0x67, 0x92, 0x65, 0xce, 0x8c, 0xa5, 0xbd, 0xf5, 0xc2, 0x57, 0xf0, 0x05,
	0x7c, 0x0a, 0xf1, 0xbe, 0x97, 0x3e, 0x82, 0xac, 0x2f, 0x22, 0x49, 0x26, 0x33, 0x49, 0xc1, 0xab,
	0xc9, 0xf7, 0x7d, 0x27, 0xe7, 0x7c, 0x39, 0x67, 0x0e, 0xec, 0x63, 0x26, 0x1f, 0x64, 0x5a, 0x2d,
	0xe5, 0xaa, 0x2e, 0x79, 0x25, 0xb5, 0x9a, 0xad, 0x4b, 0x5d, 0x69, 0xba, 0x63, 0x3f, 0xe9, 0x57,
	0x02, 0xe3, 0xe3, 0x50, 0x7e, 0x2d, 0x10, 0xf9, 0x4a, 0x50, 0x06, 0x37, 0x3e, 0x8b, 0x12, 0xa5,
	0x56, 0x8c, 0x24, 0x5b, 0xd3, 0xe1, 0xdc, 0x43, 0xfa, 0x18, 0x06, 0x59, 0x5e, 0x63, 0x25, 0xca,
	0x57, 0x6a, 0xa9, 0xd9, 0x56, 0x42, 0xa6, 0x83, 0x83, 0xdb, 0x2e, 0xed, 0xec, 0xd8, 0x29, 0x4d,
	0x96, 0x79, 0x18, 0x49, 0xef, 0x42, 0xbf, 0x92, 0x85, 0xc0, 0x8a, 0x17, 0x6b, 0xd6, 0x4b, 0xc8,
	0x74, 0x7b, 0xde, 0x11, 0xe9, 0xf7, 0x1e, 0x8c, 0xe2, 0xdb, 0x34, 0x69, 0x2b, 0x9d, 0xd4, 0x72,
	0xc1, 0x48, 0x42, 0xa6, 0xfd, 0x79, 0x48, 0x05, 0x11, 0x6f, 0x78, 0x21, 0xac, 0x97, 0x2e, 0xc2,
	0x50, 0xf4, 0x3e, 0x0c, 0x33, 0xad, 0xaa, 0x52, 0xe7, 0x47, 0x39, 0x5f, 0x08, 0xb4, 0x85, 0xfb,
	0xf3, 0x98, 0xa4, 0x87, 0xb0, 0xd7, 0x10, 0xb9, 0x28, 0x4f, 0x2a, 0x99, 0xcb, 0x4b, 0xdb, 0x0d,
	0x64, 0xdb, 0x36, 0xfc, 0x1f, 0xaa, 0xc9, 0x8e, 0x17, 0x58, 0x89, 0xe2, 0x5d, 0x5d, 0x14, 0xbc,
	0xbc, 0x60, 0x3b, 0x2e, 0x7b, 0x44, 0x9a, 0x5e, 0x2e, 0x74, 0xc1, 0xa5, 0x42, 0xb6, 0xb0, 0xba,
	0x87, 0x74, 0x0c, 0x3b, 0x97, 0x5a, 0x09, 0x64, 0xc2, 0xf2, 0x0e, 0xd0, 0x3b, 0x70, 0x93, 0xaf,
	0x5f, 0x96, 0xba, 0x5e, 0x23, 0x5b, 0x5a, 0xa1, 0xc5, 0x74, 0x02, 0x70, 0x9e, 0x73, 0xd5, 0xa8,
	0x2b, 0xab, 0x06, 0x8c, 0xc9, 0x68, 0x10, 0xb2, 0x8f, 0x2e, 0xa3, 0x05, 0x74, 0x17, 0x7a, 0x7c,
	0x8d, 0x4c, 0x5a, 0xce, 0x1c, 0xcd, 0x14, 0x2b, 0xa1, 0xb8, 0xaa, 0xcc, 0x68, 0x90, 0x5d, 0x91,
	0xa4, 0x37, 0x1d, 0x1c, 0x8c, 0x9b, 0x31, 0xbe, 0xb7, 0x52, 0x3b, 0xc5, 0x20, 0x32, 0xfd, 0x42,
	0x60, 0x18, 0xc9, 0xc6, 0x6e, 0x13, 0xe0, 0x67, 0xd4, 0x62, 0x63, 0xd7, 0x9d, 0x83, 0xf9, 0x04,
	0x0c, 0x3d, 0x84, 0x01, 0x5f, 0x14, 0x52, 0xbd, 0xb0, 0x0d, 0xb1, 0xc3, 0xe9, 0x5c, 0x38, 0xb2,
	0x75, 0x11, 0x04, 0xa6, 0x3f, 0x08, 0x0c, 0x23, 0xd9, 0xb8, 0x70, 0x5d, 0xed, 0x5c, 0x78, 0x6c,
	0x5c, 0xb8, 0x73, 0xe8, 0xa2, 0x63, 0xe8, 0x43, 0xe8, 0x9b, 0xce, 0xbb, 0x56, 0xf4, 0x6c, 0x27,
	0x68, 0xe3, 0xe1, 0x54, 0x2b, 0xe1, 0x1d, 0x74, 0x41, 0xf4, 0x29, 0x8c, 0xb0, 0x3e, 0x73, 0x0e,
	0xdc, 0xb5, 0xed, 0xa8, 0x81, 0xb1, 0xf5, 0x6b, 0xb1, 0xe9, 0x4f, 0x02, 0x83, 0x20, 0x31, 0xdd,
	0x83, 0xff, 0x6d, 0x6a, 0xef, 0xbc, 0x41, 0xe6, 0x4d, 0xe6, 0x14, 0xb8, 0x6e, 0x31, 0x7d, 0x02,
	0xb7, 0x9a, 0x9f, 0x22, 0xb4, 0xed, 0xf7, 0xf0, 0xb9, 0x93, 0xbc, 0x81, 0x28, 0x94, 0x3e, 0x83,
	0x51, 0xfb, 0xc7, 0x84, 0xe6, 0xf7, 0x9b, 0xcb, 0x1f, 0xbc, 0xd8, 0xfa, 0x8f, 0xc3, 0xd3, 0xb7,
	0x30, 0x8a, 0x0b, 0x98, 0xdd, 0xf6, 0x25, 0xfc, 0x23, 0x3a, 0xc2, 0xac, 0x69, 0x03, 0xc2, 0x35,
	0x0d, 0xa8, 0xf4, 0x14, 0x76, 0xaf, 0x57, 0x35, 0xb7, 0xba, 0xba, 0xed, 0xfa, 0x07, 0x94, 0x59,
	0xbf, 0x16, 0x06, 0x99, 0x63, 0xf2, 0xe8, 0xd1, 0xd5, 0x66, 0x42, 0x7e, 0x6d, 0x26, 0xe4, 0xf7,
	0x66, 0x42, 0xbe, 0xfd, 0x99, 0xfc, 0x07, 0xf7, 0x32, 0x5d, 0xcc, 0xca, 0x3a, 0xfb, 0x54, 0xe3,
	0xb9, 0x2c, 0x45, 0x2e, 0x10, 0x67, 0x98, 0xad, 0xdc, 0xf3, 0xcf, 0xea, 0xe5, 0x0c, 0x33, 0xf9,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xf2, 0x76, 0x33, 0x3b, 0x05, 0x00, 0x00,
}

func (m *ConfigurationMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigurationMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigurationMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Timestamp != nil {
		i = encodeVarintSciConfiguration(dAtA, i, uint64(*m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.ClusterInfo != nil {
		{
			size, err := m.ClusterInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSciConfiguration(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Version == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		i = encodeVarintSciConfiguration(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClusterMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClusterMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.TenantInfos) > 0 {
		for iNdEx := len(m.TenantInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TenantInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSciConfiguration(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xc
			i--
			dAtA[i] = 0xc2
		}
	}
	if m.Aps != nil {
		i -= len(*m.Aps)
		copy(dAtA[i:], *m.Aps)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.Aps)))
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0xca
	}
	if m.Wlans != nil {
		i -= len(*m.Wlans)
		copy(dAtA[i:], *m.Wlans)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.Wlans)))
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0xc2
	}
	if m.WlanGroups != nil {
		i -= len(*m.WlanGroups)
		copy(dAtA[i:], *m.WlanGroups)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.WlanGroups)))
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0xba
	}
	if m.ApGroups != nil {
		i -= len(*m.ApGroups)
		copy(dAtA[i:], *m.ApGroups)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ApGroups)))
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0xb2
	}
	if m.Zones != nil {
		i -= len(*m.Zones)
		copy(dAtA[i:], *m.Zones)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.Zones)))
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0xaa
	}
	if m.Domains != nil {
		i -= len(*m.Domains)
		copy(dAtA[i:], *m.Domains)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.Domains)))
		i--
		dAtA[i] = 0x6
		i--
		dAtA[i] = 0xa2
	}
	if m.SystemSummary != nil {
		i -= len(*m.SystemSummary)
		copy(dAtA[i:], *m.SystemSummary)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.SystemSummary)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ControllerUtilizations != nil {
		i -= len(*m.ControllerUtilizations)
		copy(dAtA[i:], *m.ControllerUtilizations)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ControllerUtilizations)))
		i--
		dAtA[i] = 0x22
	}
	if m.ControlBlades != nil {
		i -= len(*m.ControlBlades)
		copy(dAtA[i:], *m.ControlBlades)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ControlBlades)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ClusterName != nil {
		i -= len(*m.ClusterName)
		copy(dAtA[i:], *m.ClusterName)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ClusterName)))
		i--
		dAtA[i] = 0x12
	}
	if m.ClusterUuid != nil {
		i -= len(*m.ClusterUuid)
		copy(dAtA[i:], *m.ClusterUuid)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ClusterUuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TenantMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TenantMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TenantMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.AdminDomain != nil {
		{
			size, err := m.AdminDomain.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSciConfiguration(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.TenantName != nil {
		i -= len(*m.TenantName)
		copy(dAtA[i:], *m.TenantName)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.TenantName)))
		i--
		dAtA[i] = 0x12
	}
	if m.TenantId != nil {
		i -= len(*m.TenantId)
		copy(dAtA[i:], *m.TenantId)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.TenantId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DomainMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.SubDomainInfos) > 0 {
		for iNdEx := len(m.SubDomainInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SubDomainInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSciConfiguration(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ZoneInfos) > 0 {
		for iNdEx := len(m.ZoneInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ZoneInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSciConfiguration(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.DomainName != nil {
		i -= len(*m.DomainName)
		copy(dAtA[i:], *m.DomainName)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.DomainName)))
		i--
		dAtA[i] = 0x12
	}
	if m.DomainId != nil {
		i -= len(*m.DomainId)
		copy(dAtA[i:], *m.DomainId)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.DomainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ZoneMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ZoneMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZoneMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.WlanGroupInfos) > 0 {
		for iNdEx := len(m.WlanGroupInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WlanGroupInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSciConfiguration(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ApGroupInfos) > 0 {
		for iNdEx := len(m.ApGroupInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApGroupInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSciConfiguration(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ZoneName != nil {
		i -= len(*m.ZoneName)
		copy(dAtA[i:], *m.ZoneName)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ZoneName)))
		i--
		dAtA[i] = 0x12
	}
	if m.ZoneId != nil {
		i -= len(*m.ZoneId)
		copy(dAtA[i:], *m.ZoneId)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ZoneId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ApGroupMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApGroupMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApGroupMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ApGroupName != nil {
		i -= len(*m.ApGroupName)
		copy(dAtA[i:], *m.ApGroupName)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ApGroupName)))
		i--
		dAtA[i] = 0x12
	}
	if m.ApGroupId != nil {
		i -= len(*m.ApGroupId)
		copy(dAtA[i:], *m.ApGroupId)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.ApGroupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WlanGroupMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WlanGroupMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WlanGroupMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.WlanGroupName != nil {
		i -= len(*m.WlanGroupName)
		copy(dAtA[i:], *m.WlanGroupName)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.WlanGroupName)))
		i--
		dAtA[i] = 0x12
	}
	if m.WlanGroupId != nil {
		i -= len(*m.WlanGroupId)
		copy(dAtA[i:], *m.WlanGroupId)
		i = encodeVarintSciConfiguration(dAtA, i, uint64(len(*m.WlanGroupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSciConfiguration(dAtA []byte, offset int, v uint64) int {
	offset -= sovSciConfiguration(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConfigurationMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		n += 1 + sovSciConfiguration(uint64(*m.Version))
	}
	if m.ClusterInfo != nil {
		l = m.ClusterInfo.Size()
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.Timestamp != nil {
		n += 1 + sovSciConfiguration(uint64(*m.Timestamp))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ClusterMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterUuid != nil {
		l = len(*m.ClusterUuid)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.ClusterName != nil {
		l = len(*m.ClusterName)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.ControlBlades != nil {
		l = len(*m.ControlBlades)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.ControllerUtilizations != nil {
		l = len(*m.ControllerUtilizations)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.SystemSummary != nil {
		l = len(*m.SystemSummary)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.Domains != nil {
		l = len(*m.Domains)
		n += 2 + l + sovSciConfiguration(uint64(l))
	}
	if m.Zones != nil {
		l = len(*m.Zones)
		n += 2 + l + sovSciConfiguration(uint64(l))
	}
	if m.ApGroups != nil {
		l = len(*m.ApGroups)
		n += 2 + l + sovSciConfiguration(uint64(l))
	}
	if m.WlanGroups != nil {
		l = len(*m.WlanGroups)
		n += 2 + l + sovSciConfiguration(uint64(l))
	}
	if m.Wlans != nil {
		l = len(*m.Wlans)
		n += 2 + l + sovSciConfiguration(uint64(l))
	}
	if m.Aps != nil {
		l = len(*m.Aps)
		n += 2 + l + sovSciConfiguration(uint64(l))
	}
	if len(m.TenantInfos) > 0 {
		for _, e := range m.TenantInfos {
			l = e.Size()
			n += 2 + l + sovSciConfiguration(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TenantMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TenantId != nil {
		l = len(*m.TenantId)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.TenantName != nil {
		l = len(*m.TenantName)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.AdminDomain != nil {
		l = m.AdminDomain.Size()
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DomainMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DomainId != nil {
		l = len(*m.DomainId)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.DomainName != nil {
		l = len(*m.DomainName)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if len(m.ZoneInfos) > 0 {
		for _, e := range m.ZoneInfos {
			l = e.Size()
			n += 1 + l + sovSciConfiguration(uint64(l))
		}
	}
	if len(m.SubDomainInfos) > 0 {
		for _, e := range m.SubDomainInfos {
			l = e.Size()
			n += 1 + l + sovSciConfiguration(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ZoneMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ZoneId != nil {
		l = len(*m.ZoneId)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.ZoneName != nil {
		l = len(*m.ZoneName)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if len(m.ApGroupInfos) > 0 {
		for _, e := range m.ApGroupInfos {
			l = e.Size()
			n += 1 + l + sovSciConfiguration(uint64(l))
		}
	}
	if len(m.WlanGroupInfos) > 0 {
		for _, e := range m.WlanGroupInfos {
			l = e.Size()
			n += 1 + l + sovSciConfiguration(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ApGroupMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApGroupId != nil {
		l = len(*m.ApGroupId)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.ApGroupName != nil {
		l = len(*m.ApGroupName)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WlanGroupMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WlanGroupId != nil {
		l = len(*m.WlanGroupId)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.WlanGroupName != nil {
		l = len(*m.WlanGroupName)
		n += 1 + l + sovSciConfiguration(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSciConfiguration(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSciConfiguration(x uint64) (n int) {
	return sovSciConfiguration(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConfigurationMessage) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigurationMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigurationMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClusterInfo == nil {
				m.ClusterInfo = &ClusterMessage{}
			}
			if err := m.ClusterInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Timestamp = &v
		default:
			iNdEx = preIndex
			skippy, err := skipSciConfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClusterUuid = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ClusterName = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlBlades", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ControlBlades = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerUtilizations", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ControllerUtilizations = &s
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemSummary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SystemSummary = &s
			iNdEx = postIndex
		case 100:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domains", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Domains = &s
			iNdEx = postIndex
		case 101:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zones", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Zones = &s
			iNdEx = postIndex
		case 102:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroups", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApGroups = &s
			iNdEx = postIndex
		case 103:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlanGroups", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.WlanGroups = &s
			iNdEx = postIndex
		case 104:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wlans", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Wlans = &s
			iNdEx = postIndex
		case 105:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aps", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Aps = &s
			iNdEx = postIndex
		case 200:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TenantInfos = append(m.TenantInfos, &TenantMessage{})
			if err := m.TenantInfos[len(m.TenantInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciConfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TenantMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TenantMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TenantMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.TenantId = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.TenantName = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminDomain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AdminDomain == nil {
				m.AdminDomain = &DomainMessage{}
			}
			if err := m.AdminDomain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciConfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DomainMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainId = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.DomainName = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZoneInfos = append(m.ZoneInfos, &ZoneMessage{})
			if err := m.ZoneInfos[len(m.ZoneInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubDomainInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubDomainInfos = append(m.SubDomainInfos, &DomainMessage{})
			if err := m.SubDomainInfos[len(m.SubDomainInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciConfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ZoneMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ZoneMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ZoneMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneId = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ZoneName = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroupInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApGroupInfos = append(m.ApGroupInfos, &ApGroupMessage{})
			if err := m.ApGroupInfos[len(m.ApGroupInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlanGroupInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WlanGroupInfos = append(m.WlanGroupInfos, &WlanGroupMessage{})
			if err := m.WlanGroupInfos[len(m.WlanGroupInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciConfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApGroupMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApGroupMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApGroupMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApGroupId = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApGroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ApGroupName = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciConfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WlanGroupMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WlanGroupMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WlanGroupMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlanGroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.WlanGroupId = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WlanGroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.WlanGroupName = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSciConfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSciConfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSciConfiguration(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSciConfiguration
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSciConfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSciConfiguration
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSciConfiguration
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSciConfiguration
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSciConfiguration        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSciConfiguration          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSciConfiguration = fmt.Errorf("proto: unexpected end of group")
)
